stakwork/sphinx-nav-fiber

Dockerfile

We do this because otherwise we copy the .git file which is for the submodule and it doesnt install the nodemodules in the correct spot then fails on the docker build from SecondBrainSwarm

docker: moved the yarn install before the copy

---

craco.config.js

I was getting this error when running docker build
```
#15 174.4 ./node_modules/react-hook-form/dist/index.esm.mjs
#15 174.4 Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
```
and these changes helped fix it, but I'm not too certain what they do tbh

fix: docker build was failing this fixes the error

---

src/components/Universe/Controls/CameraAnimations/index.ts

The gsap rotation animation was removed here because rotation is already handled in useFrame.

fix: remove legacy camera animations

---

src/components/Universe/Controls/CameraAnimations/useAutoNavigate.ts
src/components/Universe/Graph/Cubes/BlurryInstances/index.tsx
src/components/Universe/Graph/Cubes/Highlights/animated.tsx
src/components/Universe/Graph/Cubes/Highlights/index.tsx

I added a timeout for camera animation to prevent an eternal loop bug. also added index to the keys of nodes to prevent duplicate key issues (seems like the backend is providing nodes with identical ref_ids). 
I reorganized code in useAutoNavigate, so it looks like a lot has changed, but things are just moved around.

fix: camera animation safeguards

---

babel.config.js
package.json
src/utils/assertNever/__tests__/index.ts
src/utils/colors/__tests__/index.ts
src/utils/formatDescription/__tests__/index.ts
src/utils/formatTimestamp/__tests__/index.ts
src/utils/getLSat/__tests__/index.ts
yarn.lock

Currently the test coverage on the `./src/utils` branch is 9.63% I propose we add a min coverage with jest of 6% and we can try to increase the percentage higher. This will insure that our utils will always work the way we expect it to

test: adding coverage on the utils branch

---

src/components/AddNodeModal/Location/index.tsx
src/components/AddNodeModal/SourceUrl/index.tsx
src/components/AddNodeModal/TweetId/index.tsx
src/components/AddNodeModal/index.tsx
src/components/App/SideBar/TwitData/index.tsx

feat: add latitude longitude for add source modal

---

package.json
src/components/Universe/Controls/CameraAnimations/constants.ts
src/components/Universe/Controls/CameraAnimations/useAutoNavigate.ts
yarn.lock

This change rotates the camera so that both the selected text and it's children are in view. May need to tweak how far the camera zooms out since right now it depends on how far the children nodes are from the parent.
Closes #473

Focus on node children

---

package.json
src/components/SourcesTableModal/SourcesView/QueuedSources/Table/index.tsx
src/components/SourcesTableModal/SourcesView/Sources/Table/index.tsx
src/components/SourcesTableModal/SourcesView/Sources/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/index.tsx
src/components/SourcesTableModal/SourcesView/index.tsx
src/components/SourcesTableModal/SourcesView/types.ts
src/network/fetchSourcesData/index.ts
src/stores/useDataStore/index.ts
src/types/index.ts

This adds a new feature of the topics table which you can mute and unmute topics

feat: added Topics in popup to mute unrelated topics

---

build/index.html
src/components/App/SideBar/AudioClip/index.tsx
src/components/App/SideBar/Description/index.tsx
src/components/App/SideBar/Relevance/Episode/index.tsx
src/components/App/SideBar/Relevance/index.tsx
src/components/App/SideBar/Transcript/index.tsx
src/components/App/SideBar/YouTube/index.tsx

- Refactored audio, video and search results to show the title of the resource instead of the description. 
- Added the description above transcript in the youtube element. 
- Fixed youtube scroll div to reset to the top when selecting a new node

Sidebar rework

---

src/components/Universe/Graph/Cubes/Cube/components/Tooltip/index.tsx

PR closes https://github.com/stakwork/sphinx-nav-fiber/issues/513

fix: remove timestamp from tooltip

---

src/components/common/TypeBadge/index.tsx

Changed label for youtube and twitter space to 'Clip'
Fixes #431

Update label for node types Youtube and Twitterspace

---

src/components/AddContentModal/__tests__/index.ts
src/components/AddContentModal/index.tsx
src/components/AddContentModal/utils/index.ts

Moving some functional stuff out of the AddModalComponent into a utils file that we can test, going to move some more stuff

test: moved some regex and made a new function that we test

---

src/components/App/SideBar/AudioClip/index.tsx
src/components/App/SideBar/Transcript/index.tsx
src/components/App/SideBar/YouTube/index.tsx

feat: add feedback for copy

---

src/components/SourcesTableModal/SourcesView/Topics/Search/index.tsx

closes https://github.com/stakwork/sphinx-nav-fiber/issues/585
https://www.loom.com/share/67f06cf1f3a64c10a2f6e17de178032e?sid=f6687130-9663-4d67-8c9e-c6145f440485

fix: remove autocorrect on search input

---

src/components/App/SideBar/YouTube/index.tsx

closes #466
- This PR adds a loading state to ensure that the player is ready before seeking to the timestamp.
- Also removes the auto play prop from the player. Video is automatically played after seeking to a specific timestamp

Update video player functionality

---

src/components/App/SideBar/Trending/BriefDescriptionModal/index.tsx
src/components/App/SideBar/Trending/index.tsx
src/stores/useDataStore/index.ts
src/stores/useModalStore/index.ts
src/types/index.ts

feat: add tldr for trending topics

---

src/components/App/SideBar/Creator/index.tsx
src/components/App/SideBar/SidebarSubView/index.tsx

closes https://github.com/stakwork/sphinx-nav-fiber/issues/608
https://www.loom.com/share/1c1cd90b0c2447d2b06aa19986e15df5?sid=4e172070-1d7e-458b-b267-fced3e0eafc3

Add scrollable wrapper to component

---

src/network/fetchGraphData/__tests__/index.ts
src/network/fetchGraphData/index.ts
src/types/index.ts

closes issue #505 #512
added connection to topics and guests for tweet nodes

feat: add twitt connection to topics and guests

---

src/components/SourcesTableModal/SourcesView/Sources/Search/index.tsx
src/components/SourcesTableModal/SourcesView/Sources/index.tsx

https://www.loom.com/share/381003e4c5dc45e284d277ad2f6851d7?sid=8a3132fa-1321-40d4-87ee-229683237469

Source table improvements

---

src/components/AddContentModal/utils/__tests__/index.ts
src/components/AddContentModal/utils/index.ts

The utility functions responsible for parsing URLs were not correctly identifying YouTube Live links. They were being categorized as YouTube Channel links due to an oversight in the regex pattern.
I've updated the regex patterns in the utilities to correctly distinguish YouTube Live links. The `youtubeLiveRegex` now accurately identifies URLs that contain `/live/` and ensures that they are recognized as individual YouTube video links rather than as YouTube channels.
- Modified `youtubeLiveRegex` to match YouTube Live URLs.
- Updated `getInputType` function to return `LINK` for YouTube Live URLs.
- Added tests to confirm that YouTube Live URLs are handled correctly.
New test cases were added to verify the correct categorization of YouTube Live links. All tests pass with the updated regex, …

fix(utils): fixed Support for youtube /live/ in regex

---

package.json
yarn.lock

Authorize screen not coming up
Changed `sphinx-bridge` version to `0.2.63`
None

chore: updated sphinx bridge package to 0.2.63

---

src/components/Universe/Controls/CameraAnimations/index.ts

When attempting to view the entire graph using the third zoom option from the left, the graph does not fully display. This issue limits the usability of the graph viewing feature, as users are unable to see the complete data representation.
The zoom functionality has been adjusted specifically for the third zoom option. The update ensures that when this option is selected, the graph is scaled appropriately, allowing the entire graph to be viewed without any parts being cut off.
- Modified the zoom scaling factor for the 3rd zoom option in the file `src/components/Universe/Controls/CameraAnimations/index.ts`.
- Adjusted the UI elements to accommodate the change in zoom behavior.
- Enhanced rendering performance for the zoom-out feature to ensure a smooth user experience.
- Attached a video …

fix(zoom out): fixed increase zoom out for 3rd option (sphere)

---

src/components/App/SideBar/Trending/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/index.tsx

With this Pull Request I have addressed the issue #682 
Proper line height has been added , text overflow ellipses has been set
-tested on chrome
-tested with larger strings
closes #682

fix(#682): fixed formatting for trending-topics

---

src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx

Users currently cannot toggle play/pause by tapping on the video in our media player. The acceptance criteria specify that tapping on the video when not playing should play the video, and tapping on the video when it is playing should pause the video.
I implemented a toggle play/pause functionality by attaching an `onClick` event handler to the `ReactPlayer` component. This handler changes the play state based on the current state of the video, allowing users to tap the video to play or pause it.
- **Added `handleVideoClick` Function:** Created a function to toggle the play state between play and pause.
- **Attached `onClick` Handler to ReactPlayer:** The `ReactPlayer` component now has an `onClick` event that triggers the `handleVideoClick` function.
1.  Within MediaPlayerComponent:
- …

fix(tapping-video): tapping the video should play/pause

---

babel.config.js
jest.setup.js
package.json
src/components/SearchBar/__tests__/index.tsx
src/components/SearchBar/index.tsx
src/network/auth/__tests__/index.ts

The current implementation of the `SearchBar` component in our application displays a placeholder text `Search (10 sats)` which is not in line with our desired user interface. The reference to `10 sats` is either outdated or irrelevant and needs to be updated to simply `Search`.
The solution involves updating the placeholder text of the `SearchBar` component to just "Search". This change will make the search bar more intuitive and aligned with standard practices, ensuring a cleaner and more user-friendly interface.
- Updated the placeholder text in the `SearchBar` component from `Search (10 sats)` to `Search`.
- Added a new test case to ensure that the `SearchBar` component correctly displays the updated placeholder text.
To confirm that the changes effectively resolve the issue, a …

fix(update-search-bar): fixed update wording on the search bar and also add unit test Version#2

---

src/constants/index.ts

This is from Jarvis: 740
We want to use same endpoint for Nav and Boltwall
If it's not swarm, the Boltwall URL should be the same with Navfiber URL
getUrlFormEnv
None

fix: added boltwall URL option

---

src/components/SourcesTableModal/SourcesView/Sources/Table/index.tsx
src/components/SourcesTableModal/SourcesView/Sources/Table/tests/test.tsx

Currently, our application allows linking out to `Twitter handles` and `RSS feeds` directly from the source table. However, `YouTube channel` links are not yet implemented, causing inconsistency in user experience and limiting the accessibility of `YouTube channel` sources directly from the application.
All source types, including `Twitter handles`, `YouTube channels`, and `RSS feeds`, should have a clickable link style. Clicking on these links should take the user directly to the respective external pages in a new browser tab. This feature enhances user engagement and simplifies navigation to these external sources.
- **Ticket Number:** [ 759 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/759 ]
Implemented the functionality to allow `YouTube channels` to be linked …

Fix(source-link): Enhance Linking Functionality for All Source Types in Sources Table

---

src/components/AddContentModal/SourceStep/index.tsx
src/components/AddContentModal/SourceStep/utils/__tests__/index.ts
src/components/AddContentModal/SourceStep/utils/index.ts
src/components/AddContentModal/index.tsx

closes #807
The problem was that on the Add Content Modal all urls inputs which are not valid Youtube videos, Twitterspaces or MP3 urls still pass
I have added a check for whether the source passed is valid before you can proceed to the next step
I have added new test in tests file for valid source check
https://www.loom.com/share/567ebb08852c4f5bae313db138a53d3c

fix: url validation on add content modal

---

src/components/SettingsModal/SettingsView/index.tsx
src/components/SettingsModal/SettingsView/utils/__tests__/index.tsx

The issue involves the presence of the `User Permissions` tab in the SettingsView, which should be removed. This discrepancy in the code was causing undesired behavior.
The expected behavior is to hide the `User Permissions` tab for non-admin users and only display it for admin users. This ensures a more intuitive and user-friendly settings view.
- **Ticket Number:** [ 833 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/833 ]
To resolve this issue, I made the necessary changes to the SettingsView component to conditionally render the `User Permissions` tab only for admin users. Non-admin users will no longer see this tab
- Removed the import statement for `UserPermissions` since it's no longer used.
- Removed the `<TabPanel>` component related to `"User Permissions"` …

Fixed(Hide-User): Remove `User Permissions` Tab from SettingsView Component

---

src/components/App/MainToolbar/__test__/index.tsx
src/components/App/MainToolbar/index.tsx
src/stores/useModalStore/index.ts

The Main Toolbar lacked an `Add Item` menu list item, which was needed for extending the toolbar's functionality.
A new menu list item, `Add Item`, should be added to the Main Toolbar. This item should be rendered correctly alongside existing items like `Add Content`, `Source Table`, and `Settings`. Initially, this button will not have any functionality associated with it.
- **Ticket Number:** [ 843 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/843 ]
I introduced a new `ActionButton` component within the `MainToolbar` component. This button uses an existing icon component, `AddItemIcon` (or reuses `AddContentIcon` if a new icon is not available), and follows the existing styling and structure of the toolbar.
- Added a new `ActionButton` to the `MainToolbar` for `'Add …

Add New `Add Item` Menu List Item to Main Toolbar

---

src/utils/getLSat/__tests__/index.ts

test: tests for getLSat

---

src/components/App/SideBar/Dropdown/__tests__/index.tsx
src/components/App/SideBar/Dropdown/index.tsx

closes #850 
Add Unit Test For SideBar Dropdown

Add Unit Test For SideBar Dropdown

---

src/components/App/SideBar/Latest/__test__/index.tsx
src/components/App/SideBar/Latest/index.tsx
src/components/App/SideBar/Relevance/index.tsx
src/components/App/index.tsx
src/network/fetchGraphData/index.ts
src/stores/useDataStore/index.ts

feat: add skip_cache param when tapping `See Latest` button

---

src/components/App/Providers/Socket/index.tsx
src/constants/index.ts
src/network/api/index.ts
src/utils/apiUrlFromSwarmHost/__tests__/index.ts
src/utils/apiUrlFromSwarmHost/index.ts

https://github.com/stakwork/sphinx-nav-fiber/issues/828
closes https://github.com/stakwork/sphinx-nav-fiber/issues/828
apiUrlFromSwarmHost to another file 
created new folder  under /utils/apiUrlFromSwarmHost
yet to be added 

moving apiFromSwarmHost

---

src/components/App/SideBar/Episode/Timestamp/__tests__/index.tsx
src/components/App/SideBar/Episode/Timestamp/index.tsx
src/components/Icons/InfoIcon.tsx

closes #871 
Create tests for `src/components/App/SideBar/Episode/Timestamp/index.tsx`
Testing:

[Tests] Timestamp for episode

---

src/components/AddContentModal/index.tsx

Our current system relies solely on regex for URL validation when adding content. This method, while effective in many cases, lacks the sophistication to differentiate between source types or to validate content more accurately. This limitation can lead to incorrect handling of URLs, affecting user experience and content organization.
The integration of the `/validate_content` endpoint aims to enhance our URL validation process. Upon adding a URL, the system should:
- Call `/validate_content` with the URL to determine if it's a valid `source` or `content`.
- Navigate users to the appropriate step based on the response: source step for sources and location step for content.
- Ensure backward compatibility by falling back on regex validation if the endpoint returns a 400 status, gradually …

Implement /validate_content Endpoint Integration for Enhanced URL Validation

---

src/components/App/SideBar/Relevance/__tests__/index.tsx
src/components/App/SideBar/Relevance/index.tsx

closes #895
-  [x] created component test for `src/components/App/SideBar/Relevance`

fix: Hide Load more if latest array is empty

---

src/components/Booster/__tests__/index.spec.tsx
src/components/Booster/index.tsx

closes #913
Wrote tests for `src/components/Booster/index.tsx`
- Link: https://i.imgur.com/tLvA0pG.png

test(booster): wrote tests for booster component

---

src/components/Auth/__tests__/index.tsx
src/components/Auth/index.tsx

closes #893 
add Test for `src/components/Auth/index.tsx`

[Component Tests] Auth

---

src/components/AddItemModal/index.tsx

Currently, the error message displayed to the user during the AddItem flow does not reflect the message returned from the backend when calling the `/node` endpoint.
The error message displayed to the user should accurately reflect the message returned from the backend when an error occurs during the AddItem flow.
- **Ticket Number:** [ 955 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/955 ]
To address this issue, the error handling logic in the `handleSubmitForm` function has been updated to use the error message passed from the backend when calling the /node endpoint.
- Modified the `handleSubmitForm` function to check for and display the error message from the backend response.
- Updated the error handling to prioritize the backend-provided error message over …

 Display error message returned from the backend when calling `/node` during the AddItem flow

---

src/components/Modal/index.tsx

Tapping ESC on any window/modal should close the window.
Listen for ESC key-down and call onClose each time a modal is visible and ESC has been pressed
https://www.loom.com/share/04c709e239ee4f5ca277d7e68a9155cf?sid=3affb15c-acc7-4604-8c5c-a7998e60a504

Tapping 'ESC' on any window should close the window 

---

src/components/AddItemModal/SourceTypeStep/__tests__/index.tsx
src/components/AddItemModal/SourceTypeStep/constants.ts
src/components/AddItemModal/SourceTypeStep/index.tsx
src/components/common/AutoComplete/index.tsx

closes #976
Automatically focused the input field on the SourceTypeStep of the Add Item Modal
https://www.loom.com/share/0201f8a137be4ea9ac4d97589dd7e565?sid=d74d2caa-3d41-4a28-82fc-3a3cf412eac8

feat: Auto select input field 

---

src/components/Universe/Graph/Cubes/RelevanceBadges/index.tsx

closes #743
large topic name disappers when a node on graph is selected 
https://www.loom.com/share/497580dcf23b42799b0c7594877ccac8?sid=a7668138-6413-4d06-a4db-60e65c8f0678

fix: Topic name disappears when selected

---

src/components/App/ActionsToolbar/PlayerControl/__tests__/index.tsx
src/components/App/ActionsToolbar/PlayerControl/index.tsx

The miniplayer component currently lacks a pause button when media is playing, causing confusion for users who wish to stop the media playback. This issue has been identified in the user interface of the application's miniplayer section.
The expected behavior is for a pause button to appear in place of the play button when the media is playing in the miniplayer. This allows users to clearly see that they can pause the media and provides a standard control mechanism found in most media players.
- **Ticket Number:** [ 1006 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1006 ]
To resolve this issue, a `PauseIcon` component was introduced to toggle with the `PlayIcon` based on the media's playing state. The logic within the `PlayerControl` component was updated to display …

Fix(Pause-button): Add Pause Button to Miniplayer

---

src/components/AddContentModal/utils/__tests__/index.ts
src/components/AddContentModal/utils/index.ts

The current Regex checker for YouTube videos in the `AddContentModal` component does not include support for `youtu.be` URLs. The task is to enhance the Regex checker to recognize youtu.be URLs and treat them as `audio_video` content type.
- The Regex checker should be updated to include youtu.be URLs.
- The `youtu.be` URLs should be treated as `audio_video`, similar to other YouTube video formats.
- **Ticket Number:** [ 1001 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1001 ]
- Updated the Regex checker in `src/components/AddContentModal/utils/index.ts` to include support for `youtu.be` URLs.
- Modified the handling of youtu.be URLs in `src/components/AddContentModal/index.tsx` to push them as `audio_video` content type.
- Manual testing was conducted to verify …

Added Regex to identify `youtu.be` as audio_video content type

---

src/components/App/SideBar/Relevance/Episode/index.tsx

Topics get cut off on the sidebar
closes #991
styling issue
css fix

feat: fix the styling

---

src/components/App/SideBar/Trending/index.tsx

- Center refresh Icon on Trending Topics
closes #1037
- **Ticket Number:** [ 1037 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1037 ]
- Manual testing was conducted to verify that the new integration works as expected.

Fix: Center refresh Icon on Trending Topics

---

src/components/AppNew/ModalsContainer/SourcesTableModal/SourcesView/index.tsx
src/components/Auth/index.tsx
src/components/SourcesTableModal/SourcesView/__tests__/index.tsx
src/components/SourcesTableModal/SourcesView/index.tsx
src/stores/useFeatureFlagStore/index.ts
src/types/index.ts

closes #1030
We want to hide queued sources column when queuedSources is false:

Feature flag queued sources

---

src/components/AddContentModal/LocationStep/index.tsx
src/components/AppNew/ModalsContainer/AddContentModal/LocationStep/index.tsx

closes #1060
Location step for the Add content flow was not responsive for smaller screens sizes

Make Location Step of the Add Content Responsive

---

src/stores/useFeatureFlagStore/index.ts

The frontend cannot dynamically toggle new schema implementations, which is necessary for phased rollouts and testing.
A new feature flag for CustomSchema should be integrated within the useFeatureFlagStore, allowing for the conditional rendering and utilization of new schema features based on the flag's state.
Closes: #1048
- **Ticket Number:** [ 1048 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1048 ]
Implemented a new feature flag CustomSchemaFlag within the useFeatureFlagStore, defaulting to false, and provided a setter function setCustomSchemaFlag for dynamic adjustments.
- Added `FeatureFlag` and `setFeatureFlag` to the `FeatureFlagStore` type.
- Initialized `FeatureFlag` to false in defaultData.
- Implemented `setFeatureFlag` within the store creation logic. …

Add CustomSchema Feature Flag to useFeatureFlagStore

---

src/components/App/SideBar/Show/index.tsx

closes #1059
The Related Episode List should be scrollable to accommodate more Episode Items for smaller screen sizes
https://www.loom.com/share/a57f273f0715401293d0a6439acc858c?sid=78742981-fa5d-4480-a17a-d3f86f73a00f

Make “Related Episode” List Scrollable

---

src/components/AddContentModal/BudgetStep/index.tsx
src/components/AddContentModal/index.tsx
src/components/AddItemModal/BudgetStep/index.tsx
src/components/AddItemModal/index.tsx

closes #1067
Replaced the Error Toast with a modal Error
https://www.loom.com/share/6e5917aa487b4a3facbe200dcd8c8e93?sid=b5f242ab-88d6-41a9-88a2-85a2b624dd5c

Replace Error Toast message with on modal error

---

src/components/SettingsModal/SettingsView/GraphBlueprint/Table/TableRow.tsx
src/components/SettingsModal/SettingsView/GraphBlueprint/Table/index.tsx
src/components/SettingsModal/SettingsView/GraphBlueprint/index.tsx
src/components/SettingsModal/SettingsView/index.tsx
src/components/SettingsModal/index.tsx
src/network/fetchSourcesData/index.ts

The admin section requires a new feature where administrators can view and add new types via a schema table in the Blueprint column, enhancing the data management and customization capabilities.
closes: #1081
Admins should be able to view a list of all types retrieved from the `GET schema/all API` and add new types through a user-friendly interface, following the existing design patterns of the platform.
- **Ticket Number:** [ 1081 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1081 ]
new schema table has been added to the Blueprint column for admins. This includes calling the `GET schema/all` endpoint to list existing types and providing a button to add new types, initiating the custom node type flow as per the existing AddItem workflow.
- Implemented feature flag …

Add Schema Table to Admin `Blueprint` Column

---

src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx

The Topics Table currently lacks a mechanism to handle multiple edges efficiently, leading to UI inconsistency and potential information overload for the users.
The table should provide a clear, concise view of the edges, even when multiple edges are associated with a single topic. This includes displaying an ellipsis ("...") when the edge list exceeds the display limit and revealing additional edges through a hover effect, without affecting the row height.
- **Ticket Number:** [ 1012 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1012 ]
https://github.com/stakwork/sphinx-nav-fiber/issues/1012#issuecomment-2004474761
- Please see the attached Image as evidence.
- Please see the attached Image as evidence.
- Manual testing was conducted to verify that the new …

Implement Hover Effect and Ellipsis for Multiple Edges in Topics Table

---

src/components/Auth/index.tsx
src/types/index.ts

Custom Schema was not showing
Set `customSchema` on page mount

fix: added setCustomSchemaFlag on page mount

---

src/components/SettingsModal/SettingsView/index.tsx

1116
Want to change `graphBluePrintFlag` to `customSchemaFlag`
used `customSchemaFlag` instead of `graphBluePrintFlag`

fix: changed graphBluePrintFlag to customSchemaFlag

---

src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx
src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
src/components/SourcesTableModal/SourcesView/common/index.tsx
src/types/index.ts

Add `type` column in topic curation table
closes: #1134
New type column that uses `node_type` in the response
- **Ticket Number:** [ 1134 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1134 ]
- Manual testing was conducted to verify that the new integration works as expected.

fix(add-node-type): add type column in topic curation table

---

src/components/common/AutoComplete/index.tsx

Labels next to dropdown menus in the Add Item flow were cluttering the UI and potentially confusing users.
Removing the labels will streamline the UI, making the Add Item flow more intuitive and user-friendly.
closes: #1160
- **Ticket Number:** [ 1160 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1160 ]
- Testing should ensure the UI remains intuitive without the labels, checking functionality, user experience, cross-platform consistency, and for any regressions.
https://www.loom.com/share/46a4d08ef8634ffcb7eefc97057d2385

Remove Label from Dropdown in Add Item Flow

---

src/components/AddContentModal/index.tsx
src/components/AddItemModal/index.tsx

Lack of specific error messages from the backend for the Add Item and Add Content flows when errors occur, leading to user confusion.
Display specific backend error messages to users for a clearer understanding of issues encountered during the Add Item and Add Content processes.
closes: #1154
- **Ticket Number:** [ 1154 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1154 ]
Refined the error handling in the handleSubmitForm function to accurately capture and display backend error messages for POST requests in the Add Item and Add Content flows.
- The solution was validated through manual testing, unit tests, integration tests, and end-to-end tests to ensure accurate display of backend error messages across different error scenarios.

Improve Error Handling in Add Item & Add Content Flows

---

src/components/App/SideBar/Dropdown/index.tsx
src/stores/useDataStore/index.ts

Our filter system displayed all options, regardless of actual results, confusing users by allowing selections with no outcomes.
This update ensures only filters with results are shown, each with a count of items (e.g., "Tweet (24)"). It dynamically adjusts based on the dataset, improving user experience by guiding choices with visible data availability.
closes: #1099
- **Ticket Number:** [ 1099 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1099 ]
- Manual tests confirmed functionality, including dynamic display and count accuracy. Compatibility and error handling were rigorously evaluated to ensure a smooth integration.
https://www.loom.com/share/fa81e08c338e403083481f4bf31a491a

fix(filter-options): only display filter options if there is a result

---

src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx

closes #1169 
https://www.loom.com/share/afe290175ef743c0acdccfdb8675ff4f?sid=dec0a57b-b3af-4868-8d6c-e2db18d73d56

 fix:Highlighting name field in Topic Curation table should not execute search

---

src/components/AddItemModal/SourceTypeStep/__tests__/index.tsx
src/components/AddItemModal/SourceTypeStep/index.tsx

closes #1179
Add check for deleted node types
To add a check for deleted nodes while fetching schemas 
Added a test to check check that the dropdown filters out deleted node_types

fix: filter out deleted nodes

---

src/components/AddTypeModal/Body/__tests__/index.spec.tsx
src/components/AddTypeModal/Body/index.tsx

closes #1180
Remove is_deleted options for the parent selector dropdown
https://www.loom.com/share/7699629be9e54d65b192af52d6aa39fd?sid=05aee1a8-6775-45c9-8900-d80218340eb3

Remove is_deleted options for the parent selector dropdown

---

src/components/AddItemModal/SetAttributesStep/index.tsx

The current implementation allows the addition of an item without filling in the required fields. This results in the 'Next' button being enabled prematurely during the Add item flow. Additionally, the positioning of the scrollbar on the "Add Item" modal is incorrect. Also, capitalize the first letters for each: Age, Name, Namez.
The system should prevent the addition of an item until all required fields are filled. Consequently, the 'Next' button should remain disabled until all necessary attributes are set during the Add item flow. Furthermore, the scrollbar positioning within the "Add Item" modal should be corrected to ensure a proper user experience.
closes: #1196
- **Ticket Number:** [ 1196 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1196 ]
- Verify that the …

Ensure Required Fields Are Filled Before Enabling `Next` Button and Correct `Scrollbar` Positioning

---

src/components/App/SideBar/Relevance/Episode/index.tsx
src/components/App/SideBar/TwitData/__tests__/index.tsx
src/components/App/SideBar/TwitData/index.tsx

Currently, the `SideBar` and `SideBarSubView` sources fail to link out to the browser as expected. This means `tweets` and `YouTube` links are not opening in a new tab as intended.
When users click on `tweets` or `YouTube` links within the `SideBar` or `SideBarSubView` sources, they should open in a new browser tab for better user experience and navigation flow.
closes: #1197
- **Ticket Number:** [ 1197 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1197 ]
- Testing has been conducted to ensure that clicking on tweets and YouTube links within the SideBar and SideBarSubView sources correctly opens them in a new browser tab.
https://www.loom.com/share/d478a602523045d4a9aa3ab90c8702ba

Ensure `SideBar` and `SideBarSubView` Sources Link Out to the Browser.

---

src/components/SourcesTableModal/SourcesView/Sources/index.tsx
src/components/SourcesTableModal/SourcesView/constants.ts

The search placeholder in the Sources table currently reads "Find Topic", which is misleading and does not accurately represent the action it performs. Additionally, there are inconsistencies and inaccuracies in the column names of the Sources table that need to be addressed to improve user experience and clarity.
The search placeholder in the Sources table should be updated to "Find Source" to more accurately reflect its functionality. Furthermore, the column names within the Sources table should be reviewed and corrected to ensure they are consistent and accurately describe the data presented.
closes: #1200
- **Ticket Number:** [ 1200 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1200 ]

Fix UI `Search Placeholder` and `Column Names` in Sources Table

---

src/components/SettingsModal/SettingsView/index.tsx

The UI currently experiences an issue where the blue line overflows when tabs are highlighted, affecting both the admin and Sphinx user interfaces.
Tabs should be highlighted without any overflow of the blue line, ensuring a seamless user experience for both admin and Sphinx users.
closes: #1198
- **Ticket Number:** [ 1198 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1198 ]
https://www.loom.com/share/9b26e22166104f848fdfd70feae982e7
Admin Side:
Sphinx User Side:

Resolve UI Display Issue: Blue Line Overflow on Highlighted Tabs for Admin and Sphinx Users

---

src/components/AddItemModal/SetAttributesStep/index.tsx

Add schema is not working
We needed to remove the upper and lower case methods because the backend expects what is given from the GET endpoint and modifying it on the frontend may cause issues
removed upper and lower case methods on schema types
I did not just some manual testing and test coverage on the backend if you need me to add some I can do so
linked to this backend PR
https://github.com/stakwork/jarvis-backend/pull/1099

fix: removed capitalization that was unneeded

---

src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx

The loading icon on the Episode and Youtube [SideBarSubView] is not centered, leading to a discrepancy in the UI presentation.
The loading icon on the Episode and Youtub [SideBarSubView] should be centered, ensuring a visually balanced layout.
closes: #1218
- **Ticket Number:** [ 1218 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1218 ]
- Confirm that the loading icon is centered within the Episode and Youtub [SideBarSubView].
- Verify the centering behavior across different devices and screen resolutions.
https://www.loom.com/share/fd38946e858f4dd8a7e99e0d2c8f2b76

Center `Loading` Icon on `Episode` and `YouTube` [SideBarSubView]

---

src/components/App/SideBar/SidebarSubView/__tests__/index.tsx
src/components/App/SideBar/SidebarSubView/index.tsx

The scrollbar within the `SideBarSubView` component overflows beyond the rounded corners of the `Wrapper` when various options are displayed, leading to a visual inconsistency and a non-contained scrollbar.
The scrollbar should be fully contained within the `Wrapper` component, respecting the `borderRadius` property, regardless of the number of options or content displayed within the `SideBarSubView`.
closes: #1224
- **Ticket Number:** [ 1224 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1224 ]
The proposed fix involves adding overflow: hidden to the Wrapper styled component to ensure that all child components, including the scrollbar, are clipped to the Wrapper's bounds. This change maintains the visual integrity of the SideBarSubView's design by preventing any …

Fix `Scrollbar` Overflow in `SideBarSubView` Component

---

jest.setup.js
src/components/App/SideBar/Episode/index.tsx
src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx
src/components/App/SideBar/SidebarSubView/__tests__/index.tsx
src/stores/usePlayerStore/index.ts

When a user clicks on a timestamp within an episode, the video player seeks to the correct time but then immediately returns to the initial position. This behavior prevents users from navigating to different parts of the video based on the selected timestamp.
Upon clicking a timestamp, the video player should seek to the specified time and remain at that position, allowing the user to view the content from the chosen timestamp.
closes: #1223
- **Ticket Number:** [ 1223 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1223 ]
The pull request addresses the issue by introducing a new state variable isSeeking in the usePlayerStore. This variable is used to determine when a seek operation is initiated by a user action. The MediaPlayer component has been updated to only seek …

Fix Timestamp Seeking Issue in Video Player

---

src/components/AddTypeModal/Body/CustomAttributesStep/FormInput/index.tsx
src/components/AddTypeModal/Body/__tests__/index.spec.tsx
src/components/AddTypeModal/Body/index.tsx

The Setting Modal exhibits two main issues:
- The Select Parent options are not `capitalized` properly.
- The `scrollbar` within the modal is not positioned on the `right side`, leading to misalignment.
- The `Select Parent Options` feature should capitalize the first letters of its options in the Setting Modal.
- The `scrollbar` within the modal should be positioned on the right side, ensuring proper alignment.
closes: #1216
- **Ticket Number:** [ 1216 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1216 ]
- Verify that the Select Parent options are capitalized correctly within the Setting Modal.
- Confirm that the scrollbar is positioned on the right side of the modal, aligning with standard UI conventions. …

Fix: Select Parent Options `Capitalization` and `Scrollbar` Alignment in Setting Modal

---

src/components/SettingsModal/SettingsView/Appearance/index.tsx
src/components/SettingsModal/SettingsView/General/index.tsx
src/components/SettingsModal/SettingsView/index.tsx
src/components/SettingsModal/SettingsView/utils/__tests__/index.tsx

The interface lacked consistency and clarity due to syntax inconsistencies in buttons [General, Appearance] or column [BluePrint], and the Settings Modal experienced scrollbar overflow issues.
- Button labels [General, Appearance] or column label [BluePrint] should have consistent and clear syntax for improved interface readability.
- The Settings Modal should no longer experience scrollbar overflow, ensuring proper display and usability.
closes: #1217
- **Ticket Number:** [ 1217 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1217 ]
- Verify that the syntax of buttons [General, Appearance] or column [BluePrint] is updated for consistency and clarity.
- Confirm that the Settings Modal no longer experiences scrollbar overflow.
- Please see the attached video as …

Fix: Syntax Updates for `Button/Column` Labels and Resolved `Scrollbar Overflow` in Settings Modal

---

src/components/AddTypeModal/Body/CustomAttributesStep/FormInput/index.tsx
src/components/BaseTextInput/WebTextInput/index.tsx
src/components/Booster/__tests__/index.spec.tsx

When editing a custom node via Blueprint in Settings, the attribute name field is currently editable, which may lead to unintended changes.
The attribute name field for custom nodes should be disabled, preventing users from editing it. Users should still be able to modify the type and required status as normal. Additionally, PUT requests should retain the attribute name while allowing changes to type and required status.
closes: #1209
- **Ticket Number:** [ 1209 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1209 ]
- Ensure that users cannot edit the attribute name field when editing a custom node in Blueprint settings.
- Confirm that users can still modify the type and required status of the attribute.
- Verify that making changes to type and required status and …

Disable Attribute Name Field Editing for Custom Node in Blueprint Settings

---

src/components/App/SideBar/Media/__tests__/index.tsx
src/components/App/SideBar/Media/index.tsx

- The Description feature within the Episode [SideBarSubView] fails to display relevant content associated with the episode.
- The Transcript functionality does not render any text or transcript data for the episode within the [SideBarSubView].
- The Booster functionality, intended to display the boost value or count for the episode, is not functioning properly within the [SideBarSubView].
- The Description feature should accurately display relevant content associated with the episode within the [SideBarSubView].
- The Transcript functionality must render the transcript text for the episode within the [SideBarSubView].
- The Booster component should correctly display the boost value or count for the episode within the [SideBarSubView].
closes: #1242
- **Ticket Number:** [ 1242 ]
- …

Fix: `Description`, `Transcript`, and `Booster` Functionality Issues on Episode [SideBarSubView]

---

src/components/AddItemModal/SetAttributesStep/index.tsx

Currently, the frontend does not consistently render required fields first, leading to potential confusion for users.
Required fields should always be displayed first in the frontend, followed by optional fields. This ensures clarity and consistency in the user interface.
closes: #1234
- **Ticket Number:** [ 1234 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1234 ]
- Verify that required fields are displayed before optional fields in all relevant forms or UI components.
- Test various scenarios with different combinations of required and optional fields to ensure consistent behavior.
https://www.loom.com/share/188d6e2c58ee4774bfe6d282b3c6497a

Ensure `Required` Fields Are Displayed First

---

src/components/SourcesTableModal/SourcesView/common/index.tsx

closes #1254
The header of the table of modals is movable with rows, which is not good UX.
https://www.loom.com/share/cd0a69e519e34f878d398ee596f19c66?sid=3f3558ab-1b84-4b26-ad45-2bada1ced739

Source table modal tables must have sticky headers

---

cypress/e2e/admin/signin.cy.ts
src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx

- Currently, tapping on the video or pressing the space button does not trigger the expected play/pause functionality.
- Tapping the video should initiate playback if paused and pause playback if playing.
- Pressing the space button should perform the same actions accordingly.
closes: #1227
- **Ticket Number:** [ 1227 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1227 ]
- Tested tapping the video to ensure it initiates playback if paused and pauses playback if playing.
- Verified that pressing the space button performs the same actions accordingly for video playback.
https://www.loom.com/share/5511d398f21145cba85acf809010fc86

Fix: Enable `Play/Pause` Functionality on `Tapping` and `Space Button` for Video Playback

---

src/components/SettingsModal/SettingsView/GraphBlueprint/__tests__/index.tsx
src/components/SettingsModal/SettingsView/GraphBlueprint/index.tsx

The duplicate Attribute Name field undermines the editing process and may result in unintended consequences.
The Attribute Name field should appear only once when editing a custom node.
closes: #1245
- **Ticket Number:** [ 1245 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1245 ]
https://www.loom.com/share/41c66e58c6b94cb687136c479e085a4f

Fix: Duplicate Attribute Name Field Appears When Editing Custom Node on [BluePrint]

---

src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
src/stores/useDataStore/index.ts

When editing a node, changes made should be immediately reflected on the frontend UI. Currently, changes such as updating the name or image_url of a node are not immediately visible to users on the frontend.
- Changes made to a node's name should be updated in real-time on the frontend UI.
- Similarly, changes made to a node's image_url should also be reflected immediately on the frontend.
closes: #1206
- **Ticket Number:** [ 1206 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1206 ]

Fix: Updating a Node Should Render Changes on the Frontend Immediately

---

src/components/SourcesTableModal/SourcesView/common/index.tsx

closes #1269
when we click on a tab, its background color does not change to white on the first click. On the second click, the background color becomes white.
https://www.loom.com/share/e5dc4cc375e74b7dbb226342b0306015?sid=ab03b301-3f7c-4d12-864f-f91f1b38087d

Background color of tabs should be white on first click at source table modal

---

src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
src/components/ModalsContainer/EditNodeNameModal/Title/index.tsx
src/components/ModalsContainer/EditNodeNameModal/utils/__tests__/index.ts
src/components/ModalsContainer/EditNodeNameModal/utils/index.ts
src/components/common/TextInput/index.tsx

closes #1261
https://www.loom.com/share/61fae927994642a7bf27870dcba26045?sid=add3e382-1579-4a2f-9071-d4a57e9f6731

Update regex checker for images with `.jpeg` extension and made `image_url` optional when editing a node

---

src/components/App/SideBar/Relevance/Episode/index.tsx

closes #1262
-[x] fixed irregular vertical spacing between content for `youtube` and `twitter` node type
-[x] change does not affect styles for other node_types

fix: css layout for youtube and twitter node-types

---

src/components/App/SideBar/Relevance/Episode/index.tsx
src/components/SettingsModal/SettingsView/GraphBlueprint/__tests__/index.tsx

> Small issue:
> 
> * the dot overlaps the content here
> 
> <img alt="Screenshot 2024-04-18 at 14 24 08" width="375" src="https://private-user-images.githubusercontent.com/142233216/323621008-bac30898-2442-4abf-a52a-e370fde7e057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NzQ1MTksIm5iZiI6MTcxMzU3NDIxOSwicGF0aCI6Ii8xNDIyMzMyMTYvMzIzNjIxMDA4LWJhYzMwODk4LTI0NDItNGFiZi1hNTJhLWUzNzBmZGU3ZTA1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQwMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2ViZTdhNzE5NmFiM2FlY2M1MDM4NTNhZGQ3YjY0MjAzOGU3MjNlNmY1NTQwO …

fix: overlapping bullet and text

---

src/components/AddContentModal/SourceStep/utils/__tests__/index.ts
src/components/AddContentModal/SourceStep/utils/index.ts

closes #1335
Refactor topLevelDomains to not explicitly hardcode domains but to allow anything that fits .strring

fix(regex-checker): Regex checker to include any domain dot string

---

src/components/App/SideBar/SelectedNodeView/Default/index.tsx

closes #1341
This pull request enhances the selected view middle section for generic nodes,
1. Test with mock data (exactly as figma)
- With no image_url
- With image_url 
2. Actual data 
- With no image_url 
- With image_url

feat: selected view for generic nodes

---

src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/Title/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/index.tsx
src/network/fetchSourcesData/index.ts

- Add Merge action to Multi-select action bar.
- Icon - Reuse icon that is in the dropdown (see image above for merge)
- Selecting Merge should trigger the current Merge flow but pre-fill From with comma separated list ( add ... if going to overlay)
- POST request should be updated to include an array of ref_id's (same endpoint)
- If in multi-select, disable the switch button.
closes: #1297
- **Ticket Number:** [ 1297 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1297 ]
https://www.loom.com/share/5e12779e086b45c78c85c0b4dc343f2d

Fix(Sources-Table): Resolve multi-select merging of topics

---

src/components/App/SideBar/Media/index.tsx

- The Video `Boost amount` displayed in the sidebar does not accurately reflect the actual boost applied to videos, leading to inconsistencies between the displayed and actual data.
closes: #1349
- **Ticket Number:** [ 1349 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1349 ]
https://www.loom.com/share/45eac7cea2dc461d82182edee2f306ef

Fix Inaccurate Reflection of Video Boost Amount According to Sidebar

---

src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx

- `Loading icon` and `image` aren't centered in full-screen mode across all clips like `YouTube`, `Episode`, and `audio`. 
- In the [SideBarSubView] of YouTube, duplicate loading icons are being displayed, which leads to visual clutter and confusion for users.
- **Ticket Number:** [ 1352 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1352 ]
https://www.loom.com/share/de866f90345040459e2ff04373105bac

Resolved: Duplicate Loading Icon Displayed on YouTube in [SideBarSubView]

---

src/components/Stats/index.tsx
src/components/common/ToolTip/index.tsx

- Add tooltip to stats bar on hover.
closes: #1360
- **Ticket Number:** [ 1360 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1360 ]
https://www.loom.com/share/335c705ba1194158a43f7fc66ab576c6

Added `Tooltip` Functionality to Stats Bar

---

src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
src/components/SourcesTableModal/SourcesView/common/index.tsx

- When multi-selecting an item, the action bar should be overlayed over the table header and not below.
closes: #1357
- **Ticket Number:** [ 1357 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1357 ]
https://www.loom.com/share/b492964834e54269b74110dbcc039032

Update Multi-select Action Bar to Overlay Over Table Header 

---

src/components/App/SideBar/Episode/index.tsx
src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx

When a user clicks on any episode, initially, the video progress bar displays the time according to the Timestamp. However, after some time, the progress bar reverts back to the original video time, creating inconsistency in the displayed time.
closes: #1367
- **Ticket Number:** [ 1367 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1367 ]
https://www.loom.com/share/e001e18cedb44b84a4695b2fcb4b930f

Fix: Correct Display of Video Time on Progress Bar in Episode [SideBarSubView]

---

src/components/App/SideBar/Dropdown/index.tsx
src/stores/useDataStore/index.ts

When following the steps below, the application page resets:
1- Click on any Trending Topic.
2- Then click on any dropdown and select an option.
This results in the loss of current state and a reset of the application page.
- **Ticket Number:** [ 1432 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1432 ]
https://www.loom.com/share/79cccf9f031e490a8b2dd4255f30dfd3

Refresh of Application Page When Selecting Dropdown Option from Trending Topics

---

src/components/Stats/__tests__/index.tsx
src/components/Stats/index.tsx

closes #1409
When we select a node from sidebar then that node details open in second sidebar and that node appear in graph But when we select a new sats tab in the navbar of graph screen then the sidebar and graph refresh but the second sidebar still remains open that is the bug.
https://www.loom.com/share/31f9d53b4f7944c1bf7cb30adbcbfb93?sid=8b8f2467-84ca-4d4e-a74c-af9eec8df9fa

Should close second sidebar when click on stats tab

---

src/components/App/SideBar/SidebarSubView/index.tsx

- The 'Collapse Side Panel' option is disappearing within the [SideBarSubView].
- **Ticket Number:** [ 1417 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1417 ]
https://www.loom.com/share/ad45e896ad2a4b6a84b79ecfa5c771a4

Fixed(side-bar-sub-view): Implement Collapse Functionality

---

src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/index.tsx

closes #1423
'merge topics' button is enable as there is no topic is selected from dropdown for merge

Disable merge topics button if not selectedNode from the dropdown

---

src/components/SourcesTableModal/SourcesView/Topics/index.tsx

closes #1426
- At Source table modal Edit Topic and Add Edge Topic modals are not open When we click from popover of specific topic
- After that if we click on Merge Topic modal then the to modal opens at same time
https://www.loom.com/share/46608e7b32654f9ab4697506d4ff1710?sid=943a918d-e46a-46e4-a9a8-81c492c6f346

At Source table modal Edit Topic and Add Edge Topic modals should be open When we click from popover of specific topic

---

src/components/AddItemModal/SetAttributesStep/index.tsx
src/components/AddItemModal/SourceStep/index.tsx
src/components/AddItemModal/SourceTypeStep/constants.ts

- In the Add item flow, users are able to enable items even when they contain empty spaces, contrary to the intended behavior where enabling items with empty spaces should be disallowed.
- **Ticket Number:** [ 1421 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1421 ]
https://www.loom.com/share/f921ae5c9d144f43a1f87e9fa09b0c19

Fix: Add Item Flow Next Button Should Not Allow Enabling with Empty Spaces

---

src/components/ModalsContainer/AddNodeEdgeModal/Body/index.tsx
src/components/ModalsContainer/AddNodeEdgeModal/Title/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/AddEdgeTopicModal/Title/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/AddEdgeTopicModal/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/Title/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/index.tsx

closes #1466
- Buttons are oversized then input fields
- Background of 'Type' should not be gray

Buttons are oversized then input fields and Background of 'Type' shuold not be gray

---

src/components/App/ActionsToolbar/PlayerControl/index.tsx

- The episode `subtitle text` is overflowing in the ActionTool Bar on the SideBarSubView. This overflow issue causes misalignment with the `playingNode image` and the `progress bar`, affecting the overall layout and visual alignment.
- **Ticket Number:** [ 1475 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1475 ]
- Please see the attached image and video as evidence.
https://www.loom.com/share/e0b09fd19c0d4285895f80bc46531677

Fixed(ActionTool-Bar): Episode Subtitle Text Overflow in ActionTool Bar on SideBarSubView

---

src/components/Modal/index.tsx
src/components/SearchBar/index.tsx
src/components/SettingsModal/SettingsView/index.tsx
src/components/SourcesTableModal/SourcesView/index.tsx

- All modals are not responsive on all desktop screens.
- The search text overlaps with the loader icon in the search box.
- **Ticket Number:** [ 1414,  1431]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1414 and https://github.com/stakwork/sphinx-nav-fiber/issues/1431 ]
https://www.loom.com/share/b0cce17351e547b9b82772df20ff7d4d

Fixed(source-search): Make All `Modals` Responsive And Fix `Search Text Overlap` On Loader

---

src/components/SourcesTableModal/SourcesView/Content/index.tsx

Currently, when the view content table is empty, the 'Load more' button remains visible, which is contrary to the expected behavior.
The "Load More" button should be hidden when the view content table is empty.
closes: #1483
- **Ticket Number:** [ 1483 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1483 ]
- Tested the behavior of the "Load More" button when the content table is empty.
- Verified that the button is hidden in this scenario.
- Please see the attached video and image as evidence.
https://www.loom.com/share/708b3cc59d0849d1a630baf62629a401

Fixed(Source-Table): Hide `Load More` Button in View Content Modal

---

src/components/App/SideBar/Episode/index.tsx

The timestamp is not updated according to the progress bar in the episode. `For example`, when the progress bar shows a timeline of 10:00, the timestamp should change automatically, but it still shows the initial timestamp.
The "Load More" button should be hidden when the view content table is empty.
closes: #1485
- **Ticket Number:** [ 1485 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1485 ]
https://www.loom.com/share/174cdd9d5d5842aaa38ddd620b1d2473

Fixed(Timestamp): `Timestamp` Does Not Update According to `Progress Bar` in Type Episode on [SideBarSubView]

---

src/components/common/TypeBadge/index.tsx

- The topic badge text is white and hard to read.
- **Ticket Number:** [ 1358 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1358 ]

Fixed(update-lable): Update Labels and Box Colors for High-Level Node Types in Graph

---

cypress.config.ts

no ticket
Right now on Jarvis-backend the cypress test suite intemittently fails which makes it difficult if the change has broken the test suite when I didnt
This will rerun the cypress test if it fails up to 5 times 
A single line config change
Tested using this PR which passed easier than earlier
https://github.com/stakwork/jarvis-backend/pull/1250

test: retry tests config setting

---

src/components/AddItemModal/SetAttributesStep/index.tsx
src/components/AddItemModal/SourceStep/index.tsx
src/components/AddItemModal/SourceTypeStep/constants.ts

- Image link and source link are not added in additemflow due to wrong validation
- We should also support special characters
closes: #1521
- **Ticket Number:** [ 1521 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1521 ]
https://www.loom.com/share/3340e3cc979c470db482898560c5f289

Fixed(addItemFlow): Update Regex in addItemFlow

---

src/components/AddItemModal/index.tsx
src/types/index.ts

- When adding an item through the AddItem flow, the success response just shows the label. We should render the name and properties too (image if one is there)
- No name on sidebar
- No name or properties rendered in middle section
closes: #1520
- **Ticket Number:** [ 1520 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1520 ]
https://www.loom.com/share/de29afba42054f9686bed052de210b1e

Fixed(addItemFlow): Item Properties Not Rendering Immediately on Creation

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

closes #1516
- In order to create a new type, a parent node must be selected
- If user tries to press save it should give a warning below the parent input field 'A parent type must be selected'
https://github.com/stakwork/sphinx-nav-fiber/assets/158627439/565fba9a-8dfb-4077-9e35-da5840ea5cd1

Blueprint - Save button should be greyed out until parent is selected

---

src/components/App/SideBar/Show/index.tsx

closes #1502
Useless tooltip at 'show' SidebarSubView heading
https://www.loom.com/share/471197ab779d45ba8e649e168adbcda3?sid=4a61ed4e-87d2-4189-97d3-771d734db742

Remove useless tooltip from show topic heading

---

src/components/App/SideBar/index.tsx

- SidebarSubView is not closing immediately as we clear the search text from the search bar.
closes: #1497
- **Ticket Number:** [ 1497 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1497 ]
https://www.loom.com/share/5bd63800ac324667a59c5dd97fae8b84

Fixed(SidebarSubView): SidebarSubView should close when search text is cleared

---

src/components/App/SideBar/SelectedNodeView/Default/index.tsx

- When an image fails to load, there is no fallback image displayed, resulting in a broken image icon. A fallback image should be displayed if there is an image present but it fails to load.
closes: #1490
- **Ticket Number:** [ 1490 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1490 ]
https://www.loom.com/share/9ffa228d4a0348ee8b733b2f0e31d335

Fixed(sidebarSubView): Display Default Image if Node Image Fails to Load

---

src/components/ModalsContainer/BlueprintModal/Body/Toolbar/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/index.tsx

issue : #1513
Add type modal won't work if parent selected from graph, fixed it

Add Type modal fix

---

src/components/AddItemModal/BudgetStep/index.tsx
src/components/AddItemModal/index.tsx

- The error message is not displayed on the UI during the final step of the "Add Item" process.
closes: #1538
- **Ticket Number:** [ 1538 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1538 ]
https://www.loom.com/share/0e6c06f2afe142c483d9f1149c68afdc

Fixed(AddItemFlow): Error message not displayed on UI in [AddItemFlow]

---

src/components/common/AutoComplete/index.tsx

- Some option labels are not fully visible in dropdown menus across all modals. This issue causes important information to be truncated, making it difficult for users to understand the full context of the options available.
closes: #1602
- **Ticket Number:** [ 1602 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1602 ]
https://www.loom.com/share/94069660dd8f492b8b1e593c535c1b73

Fixed(Modals): Some Option Labels Not Fully Visible in Dropdowns Across All Modals [Merge Topic, AddEdge]

---

src/components/ModalsContainer/MergeTopicModal/index.tsx

- the search state is not reset after closing the Merge Topic modal and then opening a new one. 
- As a result, the search input retains its previous state, causing the `Merge Topic` button to remain enabled when opening a new node merge modal.
closes: #1598
- **Ticket Number:** [ 1598 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1598 ]
https://www.loom.com/share/2aa166a518bf4adcae09a5bdf953bc4f

Fixed:  Search State Not Reset After Closing Merge Topic Modal and Opening New One [Graph Add Modal]

---

src/components/ModalsContainer/AddNodeEdgeModal/Title/ToNode/index.tsx
src/components/ModalsContainer/MergeTopicModal/Title/ToNode/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/AddEdgeTopicModal/Title/ToNode/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/Title/ToNode/index.tsx
src/components/SourcesTableModal/SourcesView/constants.ts

- Cross (X) icon in all modals where it is misaligned and sometimes overflows the text when hovered over.
- The close icon is small and not aligned with the search text.
closes: #1596
- **Ticket Number:** [ 1596 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1596 ]
https://www.loom.com/share/9ac147daa8a4422c8185984ba8006441

Fixed(Close-Icon): Cross (X) Icon Misalignment and Overflow Issue on Hover in All Modals [Merge Topic, AddEdge]

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

closes #1500
- After selecting a node in the blueprint we should render the new display to show the nodes name and parent
- Type new name in the input field
- Confirm change via save
- Call PUT /schema/{ref_id} and pass the new type in the request if Name has changed
https://www.loom.com/share/9a0d0f0f90fd488e83c9942cf649160d?sid=c762d426-3cfe-47d5-8b06-43bec84bbd90

Update top section for blueprint and edit name functionality

---

src/components/SourcesTableModal/SourcesView/Sources/Table/index.tsx

- The edit icon is missing for some RSS links in the sources table due to the links overflowing the column. 
- This makes it difficult to access the edit functionality for those specific links.
closes: #1543
- **Ticket Number:** [ 1543 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1543 ]
https://www.loom.com/share/5955a5198e1448068e534e5e22a31653

Fixed(Source-Table): Edit Icon Missing for Some `RSS Links` Column in [Source Table]

---

src/network/fetchGraphData/helpers/handleNodes/index.ts

- The image is not displayed, but it is retrieved from the backend.
closes: #1613
- **Ticket Number:** [ 1613 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1613 ]
https://www.loom.com/share/e7c3db102eda49979db57097d0a622e3

Fixed(Main-Page): Video Thumbnails Not Display on Main Page

---

src/components/AddContentModal/utils/__tests__/index.ts
src/components/AddContentModal/utils/index.ts

- Add `x.com` as part of twitter/tweet identifier in the Add Content regex checker
closes: #1585
- **Ticket Number:** [ 1585 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1585 ]

Fix(Add-Content-Flow): Add Support for X.com to Identify as Tweets

---

src/components/AddContentModal/BudgetStep/index.tsx

- An unnecessary tooltip appears in the Add Content flow. This tooltip does not provide any useful information and may confuse users.
closes: #1571
- **Ticket Number:** [ 1571 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1571 ]
https://www.loom.com/share/28515a6691244aa9bf80146b9d044500

Fixed(Add-Content-Flow): Remove Useless `Tooltip` in Add Content flow

---

src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx

- All videos in the image below are all starting at the beginning but they should start based on the timestamp:
closes: #1519
- **Ticket Number:** [ 1519 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1519 ]
https://www.loom.com/share/0057f7932e97401ab62f2ad5e93dd44e

Fixed(Video-Player): Not Starting at the Correct Timestamp

---

src/components/ModalsContainer/BlueprintModal/Body/Toolbar/index.tsx

- The left side of the Blueprint modal corner is not rounded.
closes: #1611
- **Ticket Number:** [ 1611 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1611 ]
https://www.loom.com/share/3ddc865834ad4faba6489f309566f485

Fixed(Blueprint): Sidebar corner is not rounded

---

src/components/ModalsContainer/BlueprintModal/Body/Toolbar/index.tsx

- In the Blueprint sidebar, the tooltip for the `Add Type` button `tooltip` appears behind the modal, making it difficult for users to see the tooltip content.
closes: #1590
- **Ticket Number:** [ 1590 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1590 ]
https://www.loom.com/share/adf5a8526f08449faad110f4cb8839bd

Fixed(Tooltip): `Add Type` Tooltip is Behind the Blueprint Modal

---

src/components/ModalsContainer/BlueprintModal/Body/Graph/Links/index.tsx

- Edge is never upside down and edge overlaps over the middle node Thing 
- https://github.com/stakwork/sphinx-nav-fiber/pull/1646#issuecomment-2162525707
- https://github.com/stakwork/sphinx-nav-fiber/pull/1646#issuecomment-2162525707
https://www.loom.com/share/e7d0258d7f3b4b8c9dab1ae9b4a7513f

Fixed(blue-print): Edge is never upside down and edge overlaps over the middle node Thing

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

- When I create a new node in `Add Type`, I receive a 500 error because `selectedSchema.ref_id` is undefined, as shown in the image below.
closes: #1663
- **Ticket Number:** [ 1663 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1663 ]
https://www.loom.com/share/901c629d3f584145aac1f4bea3efcb75

Fixed[Blueprint Modal]: Error Encountered While Creating a New Node Add Type in [Blueprint Modal]

---

src/components/App/MainToolbar/__tests__/index.tsx
src/components/App/MainToolbar/index.tsx

- Enable Feedback feature to only Sphinx users.
closes: #1667
- **Ticket Number:** [ 1667 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1667 ]

Fixed(Feed-Back): Make Feedback feature available to only sphinx users

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/CustomAttributesStep/FormInput/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/Editor/CustomAttributesStep/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/Editor/__tests__/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

- Implemented functionality to add the 'delete' value to attributes when a user removes them while editing a custom node in the blueprint. This ensures that the correct data is sent in the PUT request to the /schema endpoint.
closes: #1247
- **Ticket Number:** [ 1247 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1247 ]
https://www.loom.com/share/4c3b0a4d7f37483da72a72a59cfa027a
Tested the functionality locally by removing attributes and verifying that the correct data is sent in the PUT request.

Fixed(BluePrint): Added `Delete` Value in PUT Request for Editing Node Type via Blueprint

---

src/components/AddContentModal/__tests__/index.tsx
src/components/AddContentModal/index.tsx

- Sending entire URL link for the source when we should only send the tweet_id
closes: #1672
- **Ticket Number:** [ 1672 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1672 ]
https://www.loom.com/share/ca0ccbe0355e4686a1cbe80b161dae57

Fixed(Add_Content_Flow): Sending `tweet_id` for Source Instead of Only Entire URL Link

---

src/components/ModalsContainer/BlueprintModal/Body/index.tsx

- Should be same width/height as the side (yellow).
closes: #1674
- **Ticket Number:** [ 1674 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1674 ]
https://www.loom.com/share/5325735ebb0a481a92c432c046418a2a

Fix: Blueprint Height - Reduce Excessive Border at Bottom

---

src/components/ModalsContainer/BlueprintModal/Body/index.tsx

- When a blueprint only has one node Thing and no other node types (or edges), Thing isn't rendered in the graph.
closes: #1676
- **Ticket Number:** [ 1676 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1676 ]

Ensure single node renders in graph when it's the only one available

---

src/components/ModalsContainer/BlueprintModal/Body/index.tsx

- The "Edit" and "Add Type" forms are touching the right side of the delete icon.
- The corners of the "Edit," "Add Type," and "Add Edge" forms are not rounded.

fix(blueprint): fix form icons overflow and rounded corners issue

---

src/components/App/SideBar/Dropdown/index.tsx
src/components/App/SideBar/Relevance/Episode/index.tsx
src/components/App/SideBar/Relevance/index.tsx
src/components/App/SideBar/SelectedNodeView/index.tsx
src/components/App/SideBar/TwitData/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/Editor/utils/__tests__/index.ts
src/components/ModalsContainer/ChangeNodeTypeModal/SourceTypeStep/index.tsx
src/components/ModalsContainer/RemoveNodeModal/Body/index.tsx
src/components/SettingsModal/SettingsView/General/index.tsx
src/network/fetchGraphData/const.ts
src/network/fetchGraphDataNew/utils/prepareGraphDataForce.ts
src/stores/useGraphStore/index.ts
src/utils/twitterAdapter/index.tsx

- Create an adapter to use the following response format to generate the same UI as we currently have for tweets:
- **Ticket Number:** [ 1689 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1689 ]
https://www.loom.com/share/965b73cc1db748f2976aef2c29562c55

fix(tweet-ui): Update Tweet node UI for new endpoint

---

src/components/ModalsContainer/EditNodeNameModal/Title/index.tsx

Currently, the `changeNodeTypeFeatureFlag` is missing in the `changeNodeType` modal.

Implement `changeNodeTypeFeatureFlag` in changeNodeType 

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

- When deleting a schema, the delete value should be passed with the attributes object for that attribute
- **Ticket Number:** [ 1697 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1697 ]
https://www.loom.com/share/04808c7d4bc848248c139184edc0cac7

Fixed(Blueprint): Pass Attribute and Delete Inside Attributes Object

---

src/components/App/UniverseQuestion/index.tsx
src/network/fetchSourcesData/index.ts

- Render 4 questions below the search bar in new chat interface (bottom right, triggered by the Blue Button):
closes: #1797
- **Ticket Number:** [ 1797 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1797]
https://www.loom.com/share/de0b17016a5a4df69fcf5b71342a9955
- Render questions IF seed_questions is returned in About GET request
- onClick in the new interface, should automatically trigger search with ai summary flow

Add Seed Questions to Search Interface

---

src/components/App/SideBar/SelectedNodeView/Default/index.tsx
src/components/App/SideBar/SidebarSubView/MediaPlayer/ToolBar/__tests__/index.tsx

closes #1773
currently if there is not value of property it is visible on Sidebar SubView

The Node type property on sidebar subview should not be visible if there is no value of that property

---

src/components/App/AppBar/index.tsx

- Add 1 space between the graph title and secondbrain
closes: #1821
- **Ticket Number:** [ 1821 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1821 ]
- Please see the attached Image as evidence.

Spacing between graph {graph_title} and secondbrain

---

src/components/Universe/Graph/Cubes/index.tsx

closes #1787
When we hover over the node in Graph tooltip show but it still show even if we remove cursor from node
https://www.loom.com/share/3edc6f7912ed483ea9d9aadb82931f93?sid=3d34e207-4a13-40b3-9da1-a786e5c64c4b

When we hover over the node in Graph tooltip show but it still show even if we remove cursor from node

---

src/components/AddContentModal/SourceStep/utils/index.ts
src/components/common/TextInput/index.tsx

closes #1707
when we type https://www.youtube/ this is going to be acceptable without extension
https://www.loom.com/share/29c5c8b35a4a4b0e852673aec38289f4?sid=65b1b26c-b18d-4fa7-87ef-bb45cf564cde

Add Content should not allow link without extension needs to update the regex

---

src/components/ModalsContainer/ChangeNodeTypeModal/index.tsx
src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/EditTopicModal/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx
src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/index.tsx
src/network/fetchSourcesData/index.ts
src/types/index.ts

- Update everywhere we use PUT /node (source table (renaming), `changeNodeType` to use new formatting.
closes: #1765
- **Ticket Number:** [ 1765 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1765 ]
{ node_data: {property1: “example”} }

fix(changeNodeType ): PUT `/node` formatting change

---

src/components/App/SideBar/AiSummary/utils/AiSummaryHighlight/index.tsx

- There seems to be padding or spacign before and after the highlighted word. There should but be 1 space as usual
closes: #1837
- **Ticket Number:** [ 1837 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1837 ]

Spacing before and after the highlight

---

src/components/App/Splash/index.tsx
src/components/App/UniverseQuestion/index.tsx
src/components/Universe/index.tsx
src/stores/useDataStore/index.ts

closes #1857
Currently When we open the AI search panel the four questions under AI search bar is Rendered after some delay and change after opening of the panel that should be change before the opening of Ai search Panel
https://www.loom.com/share/ed469a540b5f455d923a8c57e8084628?sid=73ed0090-0d0c-4c6a-8e30-557396a07153

Ai seed Questions under AI search bar Rendered after the AI chat search panel open

---

cypress/e2e/curationTable/curation.cy.ts
src/components/App/index.tsx
src/components/Booster/index.tsx
src/components/ModalsContainer/AddNodeEdgeModal/Body/index.tsx
src/components/ModalsContainer/ChangeNodeTypeModal/index.tsx
src/components/Universe/Graph/Cubes/SelectionDataNodes/index.tsx
src/components/Universe/Graph/Segment/LinkBadge/index.tsx

feat: disable rename a topic test

---

src/components/App/SideBar/AiSummary/AiQuestions/index.tsx

- `More on this` text is not aligned with icon on side bar
closes: #1830
- **Ticket Number:** [ 1830 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1830 ]
- Please see the attached Image as evidence.

'More on this' should be aligned with the icon on side bar [ AI search ] 

---

src/components/ModalsContainer/EditNodeNameModal/Title/index.tsx

closes https://github.com/stakwork/sphinx-nav-fiber/issues/1794

The label and placeholder value of "Image_url" should be "Image Url" instead, just like "Node Name"

---

src/components/App/SideBar/AiSearch/index.tsx
src/components/App/SideBar/AiSummary/index.tsx

- The collapse button is not aligned with the question, and the follow-up search icon is not blue as specified.
- **Ticket Number:** [ 1893 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1893 ]
- Please see the attached video  and Images as evidence.
https://www.loom.com/share/a215d19542514ff796c47cfaa8292345

Fixed(ai-r): Misaligned Collapse Button and Incorrect Follow-Up Search Icon Color

---

src/components/App/SideBar/AiSummary/index.tsx

closes #1911
When we search a lengthy string in AI search bar that text is damage the side bar View
https://www.loom.com/share/3435143efff04668b6e1311bc3bff0a1?sid=7d58cbd6-f59c-4466-b828-6af5c15b6446

When we search a long text in AI search bar due to that text side bar UI damage ( text should be wrapped in side bar)

---

src/components/App/UniverseQuestion/index.tsx

closes #1910
When we enter some text the AI search bar height is going to be change that is not better UI/UX
https://www.loom.com/share/21c389411815458fa4eefdb0936a3ab6?sid=d851167a-bc17-40ad-ac93-611f154b37d1

AI search bar height is going to be change by just writing a some text && text  hide under the search button

---

src/components/App/MainToolbar/index.tsx

- After performing an AI search in the AI Chat interface, clicking the logo does not navigate back to the Home page as expected.
closes: #1895
- **Ticket Number:** [ 1895 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1895 ]
https://www.loom.com/share/eb8a1a617f9d42aaa141c180215c3598

Fixed: AI Chat - Clicking Logo After AI Search Does Not Route to Home Page

---

src/components/App/SideBar/index.tsx

- When the collapse button is clicked, it `overlaps` with the search  Text.
closes: #1951
- **Ticket Number:** [ 1951 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1951 ]
https://www.loom.com/share/6e9996ad5dfb4c9a9316cc96c13fa1e8

`[AI Search]`:  Collapse Button `Overlaps` Search Text When Clicked

---

src/components/App/index.tsx

- Currently, we match the 4 websocket request with the user input e.g "who is satoshi?".
- Update logic to match answer, entities, relevant_questions and sources to use ref_id from query_data from the latest /graph/search request response the user used to render each component.
closes: #1958
- **Ticket Number:** [ 1958 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1958 ]

[AI Chat] - Update logic on matching webSocket request to query

---

src/components/App/ActionsToolbar/UniverseQuestionControl/index.tsx
src/components/App/SideBar/Tab/index.tsx
src/components/App/UniverseQuestion/index.tsx
src/stores/useAppStore/index.ts

- when I click the chat icon, the search bar remains open. However, according to the Figma design, when the chat icon is clicked, the sidebar should be closed, and when the AI search is closed, the sidebar should be open.
- **Ticket Number:** [ 1883 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1883 ]
https://www.loom.com/share/d26444d6677641fe801545e62b27b54f

Chat Icon Click Doesn't Close Sidebar or AI Search Bar as per Figma Design

---

src/components/App/SideBar/FilterSearch/index.tsx

closes #1964
On search filter POP UP clear and Show Results buttons should be aligned and in clear button 'X' should be aligned with clear text

On search filter POP UP clear and Show Results buttons should be aligned and in clear button 'X' should be aligned with clear text

---

src/components/App/SideBar/AiSummary/index.tsx

- Add some space between the query and toggle. The question should wrap earlier:
closes: #1978
- **Ticket Number:** [ 1978 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1978 ]

Fixed(AI-Search): Padding Between Question and Collapse Button

---

.github/workflows/test.yml
cypress/e2e/addContent/addTweet.cy.ts

GitHub deprecated v1, for docker compose

fix: fixed docker compose issue

---

src/components/Universe/Graph/Cubes/index.tsx

feat: added delay for node hover

---

src/components/App/SideBar/AiSearch/index.tsx

closes #1960
Ask follow up question Search bar is not aligned Center

Ask follow up question Search bar is not aligned Center

---

src/components/SettingsModal/SettingsView/index.tsx

feat: added navigator helper

---

src/components/App/SideBar/AiSummary/utils/AiSummaryHighlight/index.tsx

- The tooltip is consistently blanking out during the process of answer generation.
closes: #
- **Ticket Number:** [  ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/ ]

Fixed(AI-Chat): Tooltip is Consistently `Blanking Out` During Answer Generation

---

src/components/Universe/Graph/Cubes/index.tsx

- The tooltip disappears from the screen as soon as the mouse is moved away from the element.
- **Ticket Number:** [ 1897 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1897 ]
https://www.loom.com/share/2e9364491a0c4ca88fb10f0c48577397

Fixed(Graph-Tooltip): Tooltip does not stay on screen after hover

---

src/components/App/SideBar/AiSummary/index.tsx

- When using the "Listen" button feature in the AI chat, only one audio can be played at a time. When a new "Listen" button is pressed, any currently playing audio stops.
- **Ticket Number:** [ 2019 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2019 ]
- Please see the attached video  and Images as evidence.
https://www.loom.com/share/34b243ae9c9744b684349b210b5a80cb

[AI Chat]: `Listen` Button Behavior: Only One Button Plays at a Time

---

src/components/Universe/Graph/Cubes/Cube/components/Tooltip/index.tsx

- The tooltip `scroll bar` is overflowing from the top and bottom of the tooltip
- **Ticket Number:** [ 2025 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2025 ]
- Please see the attached video  and Images as evidence.
https://www.loom.com/share/34f02a71ae3d45c1b2296701201d239a

Fixed [Graph-Tooltip]: Tooltip `scroll bar` is overflow from the `top and bottom` of the tooltip

---

src/components/App/SideBar/AiSearch/index.tsx

- - The follow-up question search bar moves to the left side of the interface after the AI provides an answer.
closes: #2014
- **Ticket Number:** [ 2014 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2014 ]
- Please see the attached video and images as evidence.
https://www.loom.com/share/2241abb3d876469aa7f143fcc8a74ae1
`During Generating answer:`
`After Generating answer:`

[AI Chat]: After AI answers, `follow-up question search bar` moves to the left side

---

src/components/App/SideBar/AiSummary/AiSources/index.tsx

- Bold sources title in AI chat feature and fix padding as per Figma.
closes: #2040
- **Ticket Number:** [ 2040 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2040 ]

Fixed [Ai Sources]: Sources title not bolded and padding is incorrect

---

src/components/App/UniverseQuestion/index.tsx

closes #2041
The padding on the search should match Figma:

 Adjust padding on AI chat box

---

src/components/Universe/Graph/Cubes/Cube/components/Tooltip/index.tsx

closes #2050
Tooltip background is not visible when we hover over the node in graph

Background of Tooltip at graph not visible

---

src/components/App/SideBar/Trending/BriefDescriptionModal/index.tsx
src/components/App/SideBar/Trending/index.tsx

closes #2054
Tapping on a trending topic or the TLDR and tapping Learn more should execute tldr_topic FIRST and if unavailable use name
https://www.loom.com/share/ba8b3321f6aa4e40b1a75f3e1b2801b6?sid=798a46c0-d81a-496f-9321-04a482a04598

Tapping on Trending topics or Learn more should use tldr_topic

---

src/components/App/SideBar/AiSummary/AiAnswer/index.tsx

- The generated answer extends beyond the main content area and overlaps into the sidebar, causing layout issues.
closes: #2057
- **Ticket Number:** [ 2057 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2057 ]
- Please see the attached video and images as evidence.
https://www.loom.com/share/ef98cb87ad914b09b33a8051f4f8dba6

[Ai Chat]: Generated AI Answer `Overflowing` Sidebar

---

src/components/App/SideBar/AiSummary/utils/AiSummaryHighlight/index.tsx
src/utils/colors/index.tsx

- Clicking to highlight text does not change the background to the expected transparent blue, as specified in the Figma design.
**Figma Design:**
https://www.figma.com/design/YuEbi4x32Mm8ZQJdnrs4uc/Second-Brain-Final-Designs?node-id=8664-35066&t=yupg8RsPFpoKO4IR-4
closes: #2081
- **Ticket Number:** [ 2081 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2081 ]
https://www.loom.com/share/24e9847666754b0eb5d022b29dfc3243

Fixed[AI Chat]: Highlighted Text Background Does Not Turn Transparent Blue After Click

---

cypress/support/commands.ts

none
On Jarvis backend we are getting failures for curration and I suspect it is because we are not waiting for the latest call
I just added a cypress wait for
`https://knowledge-graph-test.sphinx.chat/api/prediction/graph/search?skip=0&limit=300&depth=2&sort_by=date_added_to_graph&include_properties=true&top_node_count=50&includeContent=true&ai_summary=false&free=true&sig=&msg=`
I noticed if I tried to load the graph but block this endpoint
`https://knowledge-graph-test.sphinx.chat/api/prediction/graph/search?skip=0&limit=300&depth=2&sort_by=date_added_to_graph&include_properties=true&top_node_count=50&includeContent=true&ai_summary=false&free=true&sig=&msg=`
It wont load so I suspect that this is causing intermittent failures on jarvis-backend because it is taking …

cypress: added wait for @latest because graph will not load otherwise

---

cypress/support/commands.ts

I want to try and increase this timeout to 30 seconds to see if it will help solve the jarvis backend issues we've been seeing

tests: increase timeout to 30 second

---

src/components/ModalsContainer/BlueprintModal/Body/index.tsx

- In the BluePrint graph, both the "Confirm" and "Delete" buttons are not visible in the following scenarios:
- When creating a new node.
- When editing an existing node.
closes: #2099
- **Ticket Number:** [ 2099 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2099 ]
https://www.loom.com/share/b920367233e340c59bfdedaa0a6bfe32

Confirm and Delete Buttons Disappear in "Create Node" and "Edit Node" in BluePrint Modal 

---

src/components/App/SideBar/SelectedNodeView/Default/index.tsx

- The Audio EN section is visible even though the audio is already displayed with the text section.
closes: #2103
- **Ticket Number:** [ 2103 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2103 ]

Hide Audio EN Section: Audio Already Displayed with Text Section

---

src/components/ModalsContainer/BlueprintModal/Body/index.tsx

- The Blueprint Modal in the Ontology section was not fully responsive, causing scrolling issues when trying to create a new node type on smaller screens.
closes: #2105
- **Ticket Number:** [ 2105 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2105 ]
https://www.loom.com/share/6fc042d0a71e49828116b19e0eb1ddcc

 Fixed(BluePrint): Resolve Scrolling Issues for New Node Type Creation

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/MediaOptions/index.tsx

closes #2107
At create new node type sidebar video, image and source link toggles are not aligned with other content of the sidebar

Toggle section should be aligned

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

- When the `Edit Type` modal is opened and then the `Create Type` modal is subsequently opened, the fields in the `Create Type` modal are populated with data from the `Edit Type` modal. Similarly, if the `Edit Type` modal is opened after the `Create Type` modal, some field data is missing in the `Edit Type` modal.
closes: #2130
- **Ticket Number:** [ 2130 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2130 ]
- Please see the attached video and image as evidence.
https://www.loom.com/share/18baa3a4a7784fd797ea86220578d60b

Fixed [BluePrint]: `Create Type` Modal Displays Data from Previously Opened `Edit Type` Modal, and Field Data Is Missing in Reverse Scenario

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
src/network/fetchSourcesData/index.ts

closes  #2122
If user selects new index from the indexes dropdown, we should update the PUT request.
e.g changing index from name to title:
PUT /schema/<ref_id>
{
"attributes": {
"index": "name"
}
}

[Blueprint] - Updating Index dropdown

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

- When adding multiple attribute fields, `Not Selected` labels appear in the `Indexes` for unfilled fields.
- **Ticket Number:** [ 2123 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2123 ]
closes: #2123
https://www.loom.com/share/eeeb12ed20fb4825b842c2e151f9fc2b

Fixed [Blueprint] : `Not Selected` Labels Displayed  In `Indexes` When Adding Multiple Attributes fields

---

package.json
src/components/AddContentModal/index.tsx
src/components/AddItemModal/index.tsx
src/components/App/MainToolbar/index.tsx
src/components/App/SideBar/FilterSearch/__tests__/index.tsx
src/components/App/SideBar/FilterSearch/index.tsx
src/components/App/index.tsx
src/components/Auth/__tests__/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/__tests__/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/Editor/__tests__/index.tsx
src/components/SourcesTableModal/SourcesView/Sources/Table/__tests__/test.tsx
src/components/Stats/__tests__/index.tsx

- Many unit tests are currently failing, affecting the overall test suite stability.
1- `src/components/Stats/__tests__/index.tsx`
2- `src/components/App/SideBar/FilterSearch/__tests__/index.tsx`
3- `src\components\ModalsContainer\BlueprintModal\Body\AddEdgeNode\__tests__\index.tsx`
4- `src\components\ModalsContainer\BlueprintModal\Body\Editor\__tests__\index.tsx`
5- `src\components\Auth\__tests__\index.tsx`
6 - `src\components\SourcesTableModal\SourcesView\Sources\Table\__tests__\test.tsx`

Fixed(Unit-Test): Resolve all Failing `Unit Tests`

---

.github/workflows/test.yml
cypress.config.ts

Fix [Cypress]:  Chromium Renderer crash by optimizing memory management

---

.github/workflows/test.yml

This is to run the cypress tests individually so we can restart the runner for an individual test incase there is a failure

test: run cypress tests individually

---

.github/workflows/test.yml
cypress.config.ts
cypress/e2e/addContent/addWebpage.cy.ts
cypress/e2e/addContent/addYoutube.cy.ts

fix: list content of cypress directory

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

- The `Create Type` modal confirm button is enabled even when no Parent is selected, which allows submission without the necessary input.
closes: #2133
- **Ticket Number:** [ 2133 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2133 ]
https://www.loom.com/share/f39f47346b504b12b1f54f17d97a51a9

Fixed [BluePrint]: `Create Type` Modal `Confirm` Button Enabled Without Selecting `Parent`

---

src/components/App/ActionsToolbar/GraphClear/index.tsx
src/components/App/ActionsToolbar/index.tsx
src/components/Auth/__tests__/index.tsx
src/stores/useDataStore/index.ts

feat: add graph clear button

---

src/stores/useGraphStore/index.ts

feat: add try catch, additional check for incorrect links

---

src/components/App/ActionsToolbar/GraphClear/index.tsx
src/components/App/ActionsToolbar/index.tsx
src/components/common/ToolTip/index.tsx

- The `GraphClear` and `CameraRecenterControl` buttons overlap each other, making it difficult to interact with either button and add `tooltip`.
closes: #1906
- **Ticket Number:** [ 1906 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1906 ]
- Please see the attached video and images as evidence.
https://www.loom.com/share/483d3445233142f98797217753784c86

[Graph]: `GraphClear` and `CameraRecenterControl` Buttons Overlap Each Other

---

src/components/Universe/Graph/Cubes/RelevanceBadges/styles.ts

- The node text overflows the box, causing layout issues.
closes: #2224
- **Ticket Number:** [ 2224 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2224 ]
https://www.loom.com/share/f397463059e84cdbadaa6447e742c770
`etc.`

[Graph]: `Node` Text `Overflowing` the Box

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

- If a previously toggled media attribute is untoggled when editing a node, we should send `delete` in the PUT /schema request.
closes: #2121
- **Ticket Number:** [ 2121 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2121 ]
https://www.loom.com/share/0259aa274e204742b673bfdc96c12ee3

Fixed[Blueprint]: Untoggling a Media Attribute Should Send DELETE in PUT /schema Request

---

src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx

closes #2143
After doing AI search, tapping on a video source from sources or the graph, doesn't start at the correct timestamp:

Videos are not starting at the correct timestamp

---

src/components/App/SideBar/FilterSearch/index.tsx

- Maxing the `source nodes` or `max results` shouldn't cause the bottom slider to appear:
- **Ticket Number:** [ 2163 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2163 ]

Fix[FilterSearch]: Bottom Slider Issue When Maxing Filter 

---

src/components/App/UniverseQuestion/index.tsx

-  Tapping `New Chat` button input field didn't auto-focus for immediate typing.
- **Ticket Number:** [ 2238 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2238 ]
https://www.loom.com/share/0b75979732484993b57bb9102933c3c0

Fixed: [AI-Chat]: Tapping `New Chat` Button Input Field Should Auto-Focus

---

src/components/App/index.tsx

feat: change socket url

---

src/components/App/index.tsx

feat: added message for socket connection

---

src/components/AddContentModal/index.tsx
src/components/App/index.tsx
src/stores/useDataStore/index.ts
src/types/index.ts

feat: added check for running project-id

---

src/components/App/index.tsx
src/components/Stats/Alerts/index.tsx
src/components/Stats/__tests__/index.tsx
src/components/Stats/index.tsx
src/stores/useDataStore/index.ts

feat: added notifications and messages list

---

src/components/App/index.tsx

feat: added json.parse

---

src/components/App/index.tsx

fix: fix graph consistency, chunked nodes

---

src/components/App/index.tsx
src/components/Stats/Alerts/index.tsx

feat: removed notification, adjusted alert messages

---

src/components/App/index.tsx
src/stores/useDataStore/index.ts

feat: fixed graph populating

---

src/components/App/SideBar/AiSummary/AiSources/index.tsx
src/components/App/SideBar/Media/index.tsx
src/components/App/SideBar/Relevance/Episode/Default/index.tsx
src/components/App/SideBar/Relevance/Episode/index.tsx
src/components/App/SideBar/Relevance/index.tsx

feat: add summary to sidebar

---

src/components/App/SideBar/FilterSearch/MaxResults/index.tsx
src/components/App/SideBar/FilterSearch/SourceNodes/index.tsx

closes #2162
Allow user to select minimum value of 0 for source nodes and max results (Current Min = 1)
The right hand side should not change, it should show the limit
Source nodes: right hand side fixed at 100
Max Results: right hand side fixed at 300

Source and node slider update

---

src/components/AddItemModal/SourceTypeStep/constants.ts
src/network/fetchSourcesData/index.ts

- Add support for `boolean` data type:
closes: #2230
- **Ticket Number:** [ 2230 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2230 ]

[Blueprint] Add Boolean Data Type to Schema

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/ColorPickerPopover/index.tsx

- The color modal is overlapping the `Create Type` Modal and the Blueprint `Header`. Additionally, the color modal is `difficult` to close once opened.
- 
We need to make it dynamic dependant on width of the screen
closes: #2299
- **Ticket Number:** [ 2299 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2299 ]
https://www.loom.com/share/94fd4a8fd4114d2fbca5385b5a194aba

[BluePrint]: Color Modal `Overlapping` UI and Difficult to Close

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

closes #2287
At create type and edit type sidebar the Parent and Name fields are not in same order

[ BluePrint ] - At create type and edit type sidebar the Parent and Name fields are not in same order ( UI/UX )

---

src/components/ModalsContainer/BlueprintModal/Body/Graph/Nodes/Node/index.tsx
src/components/common/TypeBadge/index.tsx

closes #2339
Each schema node will have a property primary_color.
We need to render this color for:
https://www.loom.com/share/1f0ff182f79f4a86a4c7fecd3f895498?sid=a6491ffb-36ed-44bf-8bc7-ac0cdcacc5f5

Render shape and label color based on schema primary_color

---

src/components/App/SideBar/Trending/index.tsx

closes #2190
Currently # tag is not in front of first line of lengthy trending topic text means not according to figma

# Tag should be in front of first line for a lengthy trending topics according to Figma

---

src/components/ModalsContainer/BlueprintModal/Body/index.tsx

closes #2182
At Create Type and Edit Type sidebar the bottom left corner is not rounded

[BluePrint] - At Create Type and Edit Type sidebar the bottom left corner is not rounded 

---

src/components/App/SideBar/AiSummary/AiAnswer/__tests__/index.tsx
src/components/App/SideBar/AiSummary/AiAnswer/index.tsx
src/components/App/SideBar/AiSummary/utils/AiSummaryHighlight/index.tsx
src/components/common/ToolTip/index.tsx
src/utils/colors/index.tsx

closes #2116
Ensure the modal doesn't get cut off from the left, right, top or bottom on hover:
https://www.loom.com/share/bc1ffeaead0b44438c28d656aea562ff?sid=e7631865-247a-4d77-b8fd-5f5a9ca2cd36

Ensure hover modal is NOT cut off

---

src/stores/useDataStore/index.ts

feat: added filtering for new coming nodes by node type

---

src/components/Universe/Graph/Cubes/Text/index.tsx

feat: added support for node without text

---

src/components/SourcesTableModal/SourcesView/constants.ts

closes #2384
Add new label to source table for Github Repository:

Add Github Repository to Source Table 

---

src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Title/ToNode/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

closes #2194
Parent , source and destination node types in dropdown showing multiple times that should be only once
https://www.loom.com/share/b5071adec042491584fe8f4ea93d7900?sid=b6280511-335a-4927-937a-5bf31b817257

[BluePrint] - Parent , source and destination node types in dropdown should be unique ( for safety we should put check on frontend side too )

---

src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/index.tsx
src/components/SourcesTableModal/SourcesView/types.ts

closes #2268
At Topics table when we click on the Name to sort table rows on the base of Name then the whole table going to be loading ( Header should be persist while loading for better UI/UX )
https://www.loom.com/share/89c76014ca324adba241540a6fda18d5?sid=f9a34477-04fa-49ea-b6f7-5e495adb80ad

Source table header should be persist

---

src/components/App/SideBar/SelectedNodeView/Default/index.tsx

- If `pubkey` is available, render boost component
- Render `boost` amount that is return for the node
- If user boots, update the boost amount in real-time
- **Ticket Number:** [ 2359 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2359 ]
https://www.loom.com/share/062abc3132084ebbb439093d0b6014d7

[`pubkey`]: Render `boost section` when node has `pubkey` property instead of `pubkey`

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

- When I click the `Add Attribute` button in the `Create Type`, the `color/icon` button located next to the `Enter type name` field moves down or below its original position.
closes: #2356
- **Ticket Number:** [ 2356 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2356 ]
`Without a Name:`
`With a Name:`
https://www.loom.com/share/b778382c9f2e41178f8ddd6bc20aed8e

[Blueprint] UI Bug:  Color/Icon Button Misplacement After Clicking `Add Attribute` Button

---

src/components/ModalsContainer/BlueprintModal/Body/Toolbar/index.tsx

- Remove delete icon from graph view. Delete is already at the bottom of the sidebar
closes: #2367
- **Ticket Number:** [ 2367 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2367 ]

[Blueprint] Remove `Delete Icon` from Graph View

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

closes #2368
This PR prevents the color & icon picker to open when a node is selected in the blueprint section
https://www.loom.com/share/b83740e8277841b395172275bb09f226?sid=6ac0b0ca-ee61-4ca6-b28d-9d6e78cf75b4

fix: prevent color picker from popping up when node is selected

---

src/components/App/SideBar/RegularView/__tests__/index.tsx
src/components/App/SideBar/RegularView/index.tsx
src/components/SearchBar/index.tsx

closes #2369
This PR Synchronizes the search input field value with URL query parameters on page load and adds `tests` for the change
https://www.loom.com/share/a1421f54962548098a2d9c62049cbb74?sid=7e56df5e-3412-4ba9-a52f-ffb454c6b069

feat: display search query in the input field when present

---

src/components/App/SideBar/FilterSearch/index.tsx

This PR ensures that results are reset after the `Clear` filters button is clicked
closes #2370
https://www.loom.com/share/76b287ed8b024c8f980e7f28e5acecd3?sid=a2c3e914-1381-494e-93c1-8382b6f258f8

fix: clear filter button not resetting results when clicked

---

src/components/Universe/Graph/Connections/index.tsx
src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
src/components/Universe/Graph/Cubes/NodePoints/index.tsx
src/components/Universe/Graph/Cubes/index.tsx
src/components/Universe/Graph/index.tsx
src/stores/useGraphStore/index.ts

feat: adjusted split force layout, added size based on nodecount

---

src/components/ModalsContainer/EditNodeNameModal/Title/index.tsx
src/components/ModalsContainer/EditNodeNameModal/utils/__tests__/index.ts
src/components/ModalsContainer/EditNodeNameModal/utils/index.ts

- Labels should have the first letter capitalized, and underscores between words should be removed.
closes: #2294
- **Ticket Number:** [ 2294 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2294 ]

[Edit Node]: Labels' First Letter Should Be `Capitalized` and Remove Underscores(`_`) Between Words

---

src/components/SettingsModal/SettingsView/General/index.tsx

closes #2160
Save Changes button position is not consistent on among all tabs
https://www.loom.com/share/211b8b0fc1094d789b7f6e285ce24b29?sid=cb40bf43-1ca9-497a-8c9c-f1ca6175368c

[Setting modal] - Save Changes button position should be consistent on all tabs

---

src/components/Auth/__tests__/index.tsx
src/components/Auth/index.tsx
src/components/ModalsContainer/OnboardingFlow/GraphDetailsStep/index.tsx
src/components/ModalsContainer/OnboardingFlow/__tests__/index.tsx
src/components/ModalsContainer/OnboardingFlow/index.tsx
src/components/ModalsContainer/index.tsx
src/stores/useModalStore/index.ts
src/types/index.ts

- If you're an admin and you open the graph without a title, we should kick start an onboarding flow.
closes: #2385
- **Ticket Number:** [ 2385 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2385 ]
https://www.loom.com/share/8321482cb43e4f0990aa24412272f9b8

[Admin]: Trigger `Onboarding Flow` for Open Graph without a Title

---

src/components/Universe/Graph/UI/NodeControls/index.tsx

- Add specific actions to the + button for nodes of type Repository as outlined below.
- Generate Tests
- Add Comments
- Review Bugs 
- Find Vulnerabilities
closes: #2403
- **Ticket Number:** [ 2403 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2403 ]

Add Specific Actions to `Repository Node Type`

---

src/components/Universe/Graph/Connections/LineComponent.tsx
src/components/Universe/Graph/Connections/index.tsx
src/components/Universe/Graph/index.tsx
src/components/Universe/constants.ts

feat: fixed links, improved behaviour on hover/select

---

src/components/Universe/Graph/Connections/LineComponent.tsx
src/components/Universe/Graph/Connections/index.tsx
src/components/Universe/Graph/index.tsx

feat: set links in Map

---

src/components/common/TextInput/index.tsx

closes #2357
The blue boundary of the input fields is incorrectly displayed at all times. It should only appear when the user hovers over the field or is actively typing, and should not be visible otherwise.
https://www.loom.com/share/b29041b26d5b4a26b3b83e1647c88b4b?sid=fb5a80ff-4741-4d2c-b58a-b5c3d01527de

The blue boundary on input fields is always visible; it should only appear on hover or while typing

---

src/components/App/SideBar/AiSummary/index.tsx

- The AI Search Listen Button does not change from the Pause state back to the default state after the content is read aloud, causing it to appear stuck.
closes: #2396
- **Ticket Number:** [ 2396 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2396 ]
https://www.loom.com/share/6bcaa22113904e2494129a81cf2d5f28

Fixed[AI Search]:  `Listen` Button Stuck in Pause State After Content is Read Aloud

---

src/components/App/SideBar/SelectedNodeView/Default/index.tsx

closes #2415
We should not render image_url if there is a media player present:
https://www.loom.com/share/f93215ef31fd48d49d64fe5e1414b135?sid=660a28ef-7585-439d-8692-44ba7fcc20d1

Render no image if media is present

---

src/components/Universe/Graph/Cubes/Text/index.tsx

closes #1939
When node text is large then it is going to be behind the Circle node icons

[Main Graph] When node text is large then it is going to be behind the Circle node icons

---

src/components/App/SideBar/FilterSearch/NodeTypes/index.tsx

- Currently, search filter `Type` section does not display `4 rows` by default, and does not according to Figma.
closes: #2420
- **Ticket Number:** [ 2420 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2420 ]
https://www.loom.com/share/c5cf67d52d58407b9436a659da99f0af

[Search Filtering]: `View More` for Node Types Rendering with Default Limit of `4 Rows`

---

src/components/App/index.tsx

feat: disable logs subscription

---

src/modules/mindset/components/MediaPlayer/ToolBar/index.tsx
src/modules/mindset/components/MediaPlayer/index.tsx
src/modules/mindset/components/sidebar/index.tsx
src/modules/mindset/index.tsx

Render Episode on the left hand side panel

---

src/components/App/ActionsToolbar/PlayerControl/index.tsx
src/components/Universe/Graph/Cubes/Text/index.tsx
src/components/mindset/components/MediaPlayer/index.tsx
src/components/mindset/components/PlayerContols/ProgressBar/index.tsx
src/components/mindset/components/PlayerContols/index.tsx
src/components/mindset/components/Sidebar/Transcript/index.tsx
src/components/mindset/components/Sidebar/index.tsx
src/components/mindset/index.tsx
src/network/fetchGraphData/index.ts
src/types/index.ts

feat: updated mindset layout

---

src/components/mindset/components/MediaPlayer/index.tsx
src/components/mindset/components/PlayerContols/index.tsx

feat: updates autoplay and icons

---

src/components/mindset/components/Scene/Board/Edges/index.tsx
src/components/mindset/components/Scene/Board/index.tsx

feat: add edge type

---

src/components/mindset/components/Scene/Board/index.tsx
src/components/mindset/components/Scene/index.tsx
src/components/mindset/components/Sidebar/Transcript/Viewer/index.tsx
src/components/mindset/components/Sidebar/Transcript/index.tsx

feat: add transcript

---

src/components/mindset/components/MediaPlayer/index.tsx
src/components/mindset/components/Sidebar/Transcript/Viewer/index.tsx
src/components/mindset/components/Sidebar/Transcript/index.tsx

feat: updated timestamps ui

---

src/components/Universe/CursorTooltip/index.tsx
src/components/Universe/Graph/Cubes/RelevanceBadges/index.tsx
src/components/Universe/Graph/Cubes/Text/index.tsx
src/components/Universe/Graph/index.tsx
src/components/mindset/components/Marker/index.tsx
src/components/mindset/components/MediaPlayer/index.tsx
src/components/mindset/components/PlayerContols/ProgressBar/index.tsx
src/components/mindset/components/PlayerContols/index.tsx
src/components/mindset/index.tsx
src/stores/useSchemaStore/index.ts

feat: live update of 3d graph

---

src/components/App/ActionsToolbar/PlayerControl/index.tsx
src/components/AppContainer/index.tsx
src/components/Universe/Graph/Connections/LineComponent.tsx
src/components/Universe/Graph/Connections/index.tsx
src/components/Universe/Graph/Cubes/Text/hooks/useTexture/index.ts
src/components/Universe/Graph/Cubes/Text/index.tsx
src/components/Universe/constants.ts
src/components/mindset/index.tsx

feat: updated links

---

src/components/mindset/components/HoverCard/index.tsx
src/components/mindset/components/Scene/Board/Node/index.tsx
src/components/mindset/components/Scene/Board/index.tsx
src/utils/colors/index.tsx

- Create a new NodeHoverCard component that displays a hover UI when hovering over a node.
closes: #2474
- **Ticket Number:** [ 2474 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2474 ]

[Graph Mindset] Implement Hover Component

---

src/components/mindset/components/Sidebar/Transcript/Viewer/index.tsx
src/components/mindset/components/Sidebar/Transcript/index.tsx

closes #2503
The transcript viewer was displaying all lines at once, making it difficult to read and follow along with the video content. The requirement was to implement gradual appearance of lines synchronized with playback.
Implemented conditional rendering of transcript lines:
- Only the first line is shown at start
- Subsequently, lines appear with a small lead time (5 seconds) relative to current playback time
- During seek/rewind, only relevant lines are displayed
- Modified Viewer component for conditional line rendering
- Added first fragment start time check to show initial line
- Implemented line filtering based on start time relative to current playback time
- Optimized logic for active/inactive line display
Manual testing was performed for the following scenarios:
- Playback …

feat: update transcript logic for improved playback experience

---

src/components/App/ActionsToolbar/GraphViewControl/index.tsx
src/components/Universe/Graph/Connections/LineComponent.tsx
src/components/Universe/Graph/Connections/index.tsx
src/components/Universe/Graph/Cubes/Text/index.tsx
src/components/Universe/Graph/index.tsx
src/components/Universe/Overlay/index.tsx
src/components/common/Avatar/index.tsx
src/components/common/GraphViewControl/index.tsx
src/components/mindset/components/Sidebar/Transcript/index.tsx
src/components/mindset/components/Sidebar/index.tsx
src/components/mindset/components/VideoCard/index.tsx
src/stores/useDataStore/index.ts
src/stores/useGraphStore/index.ts
src/stores/useSchemaStore/index.ts

feat: added link

---

src/components/mindset/components/LandingPage/index.tsx

feat: hardcoded episodes for landing page

---

src/components/AppContainer/index.tsx

closes 2523
Cypress tests are failing
The issue was with a variable added to confirm if it was a mindset graph or not and all localhost defaulted to the mindset graph. I ensured when it's E2E we don't display the mindset component
Ensured mindset graph is loaded only when it's when it's localhost and not e2e

fix: failing cypress test due to mindset graph

---

src/components/App/index.tsx
src/components/Universe/Graph/Connections/LineComponent.tsx
src/components/Universe/Graph/Connections/index.tsx
src/components/Universe/Graph/Cubes/SelectionDataNodes/index.tsx
src/components/Universe/Graph/Cubes/Text/index.tsx
src/components/Universe/Graph/Cubes/index.tsx
src/components/Universe/Graph/index.tsx
src/components/Universe/Lights/index.tsx
src/components/Universe/index.tsx
src/components/mindset/components/PlayerContols/Controls/index.tsx
src/components/mindset/components/PlayerContols/ProgressBar/Markers/Marker/index.tsx
src/components/mindset/components/PlayerContols/ProgressBar/Markers/index.tsx
src/components/mindset/index.tsx
src/stores/useDataStore/index.ts
src/stores/useGraphStore/index.ts
src/types/index.ts

feat: add normalized nodes, reduce rerenders, add particles

---

src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/EditTopicModal/index.tsx
src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx
src/types/index.ts

Update PUT /node request format

---

src/components/App/ActionsToolbar/GraphClear/index.tsx
src/components/App/SideBar/FilterSearch/__tests__/index.tsx
src/components/App/SideBar/FilterSearch/index.tsx
src/components/App/index.tsx
src/components/Auth/__tests__/index.tsx
src/components/Universe/Graph/index.tsx
src/stores/useDataStore/index.ts
src/stores/useGraphStore/index.ts

feat: fix search

---

src/components/App/SideBar/SelectedNodeView/Default/index.tsx

Add Sequenced Nodes View to Sidebar

---

src/components/App/SideBar/SelectedNodeView/Default/index.tsx
src/components/Universe/index.tsx

fix: update edges handler

---

src/components/App/SideBar/SelectedNodeView/Default/index.tsx

Fix: Reduce Line Height Between Sequenced Nodes in Sidebar

---

src/components/mindset/components/MediaPlayer/index.tsx
src/components/mindset/components/PlayerContols/Controls/index.tsx

fix: moved playing player state to store

---

src/components/mindset/components/MediaPlayer/index.tsx
src/components/mindset/components/PlayerContols/Controls/index.tsx
src/stores/usePlayerStore/index.ts

[Graph mindset] Add mute and playback speed button

---

src/components/Universe/CursorTooltip/index.tsx

feat: add custom cursor

---

src/components/Universe/Graph/Cubes/SelectionDataNodes/Node/index.tsx

closes ##2579
Bring back the edit icon (for admins only):

SelectedView Close button and edit

---

src/stores/useDataStore/index.ts

closes #2566
sort to date_added_to_graph when no search params is provided

fix: sort to date_added_to_graph when no search params is provided

---

src/components/Universe/Graph/Cubes/SelectionDataNodes/Node/index.tsx
src/components/Universe/Graph/index.tsx

feat: update selected node ui

---

src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
src/stores/useDataStore/index.ts

closes #2593
https://www.loom.com/share/152eaeb867a44eef87c878dc50c12435

Fix: Node Update API Payload Structure and Data Handling

---

src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
src/network/fetchSourcesData/index.ts
src/types/index.ts

feat: node edition update

---

src/components/Universe/GraphSearch/index.tsx

feat: added clear for graph search

---

src/components/AppContainer/index.tsx
src/components/Universe/Graph/Cubes/Text/index.tsx
src/components/mindset/components/LandingPage/index.tsx
src/components/mindset/index.tsx

closes #2625
Currently, the application lacks direct routing to specific episodes via URL. Users cannot directly access episodes through URLs or share links to specific episodes, as the episode selection is handled through store state rather than URL routing.
Implemented new routing logic that allows direct access to episodes via URL parameters. Episodes can now be accessed through mainroute/episode_ref_id where ref_id is the unique identifier for each episode.
- Added new route pattern: mainroute/episode_ref_id
- Modified LandingPage component (src/components/mindset/components/LandingPage/index.tsx) to: load landing page on mainroute, replace store state management with URL-based navigation, implement navigation to mainroute/episode_ref_id when episode is selected
- Updated mindset to: …

feat: added routing for selected episode

---

src/components/App/SideBar/AiSummary/AiAnswer/index.tsx
src/components/App/SideBar/AiSummary/index.tsx
src/network/fetchSourcesData/index.ts

closes #2655
We need to connect our two feedback buttons (“helpful” and “unhelpful”) to the backend so that whenever a user selects either button, it will send a POST request to the /answer/feedback endpoint with the correct parameters.
https://www.loom.com/share/e0d00e0c04274d07ae416ac4915a945a?sid=bad409ba-a89e-41c0-b9ed-7b2d08ecee7b

[AI Chat] Allow user to provide feedback 

---

src/components/App/SideBar/AiSearch/index.tsx
src/components/App/SideBar/SidebarSubView/__tests__/index.tsx
src/components/App/SideBar/SidebarSubView/index.tsx
src/components/App/SideBar/__tests__/index.tsx
src/stores/useAiSummaryStore/index.ts

feat: context ai search

---

cypress/e2e/addNode/addNodeType.cy.ts

This removes the addNodeType test because it ittermittently fails on jarvis-backend PR's quite often

test: removed addNodeType test as it fails on jarvis

---

cypress/e2e/seeLatest/latest.cy.ts
cypress/e2e/trendingTopics/trendingTopics.cy.ts
cypress/support/commands.ts
src/components/mindset/components/LandingPage/fetchNodes/index.ts
src/network/fetchGraphData/index.ts

https://github.com/stakwork/sphinx-nav-fiber/issues/2826
The `/prediction/graph/search` and `/prediction/graph/search/latest` endpoints were being deprecated in favor of cleaner, more concise URLs. We needed to update all references to these endpoints across the codebase before removing the old ones.  
Updated all instances of `/prediction/graph/search` to `/graph/search` and `/prediction/graph/search/latest` to `/graph/search/latest`. Ensured that all calls to these endpoints reflect the new paths, and verified that the new endpoints are functional.  
- Updated API calls from `/prediction/graph/search` → `/graph/search`  
- Updated API calls from `/prediction/graph/search/latest` → `/graph/search/latest`  
- Checked and modified any helper functions that referenced the old paths  
- …

fix: refactor graph search endpoint

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/ColorPickerPopover/ColorPickerPopoverView/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/Editor/ColorPickerPopover/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

- We should probably add a close button to ensure we can at least close if the original button is hidden.
https://www.loom.com/share/861c1fac6d2c4945849993ccaa13f859

[BluePrint]: Add `Close` Button Functionality to Color Modal

---

src/components/App/SideBar/Dropdown/index.tsx

-  Update what is rendered in the sidebar (left) using the schema store `index` property. Fallback to `node_key` property if index isn't available.
closes: #2436
- **Ticket Number:** [ 2436 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2436 ]

Fixed[SideBar]: Display schema `index` in sidebar with `node_key` fallback

---

src/components/AddContentModal/BudgetStep/index.tsx

I want to be able to see the full error since sometimes I get an error but only seeing the partial error doesnt give me much info
not totally sure how to make the background still cover the error message since it now will bleed off of the modal

fix: remove overflow so I can see full error in frontend

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
src/components/ModalsContainer/BlueprintModal/Body/Graph/Nodes/Node/index.tsx

- The Confirm button remains enabled without any changes in the Edit Type or Created Type Modal.
- Node color is not reflected in the color picker button when a node is selected in the blueprint graph.
closes: #2556
- **Ticket Number:** [ 2556 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2556]
https://www.loom.com/share/c5f0930b8c544209a7e16bd19308cce1

Fixed[BluePrint]: Confirm Button Enabled Without Changes & Node Color Not Reflected in Color Picker

---

src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx

- When a user adds multiple attributes with the same name, the indexes section displays duplicate index.
closes: #2346
- **Ticket Number:** [ 2346 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2346 ]
https://www.loom.com/share/9f0aea199a57476bab7ebf84a1163af3

[BluePrint]: `Duplicate Indexes` When Adding `Attributes` with Same Name

---

src/components/mindset/components/Sidebar/Transcript/index.tsx
src/components/mindset/components/Sidebar/index.tsx
src/stores/useMindsetStore/index.ts

closes #2895
Users needed a way to automatically skip advertisement segments. The application had Chapter nodes with node_type: "Chapter" and is_ad: "True"/"False" properties, but there was no functionality to automatically jump from ad chapters to the next non-ad content when ads were detected.
Implemented automatic ad skipping functionality that monitors playback time and when skip ads is enabled, automatically jumps from advertisement chapters to the beginning of the next non-advertisement chapter, providing seamless content consumption.
- UI: Added custom checkbox "Skip adds" in the sidebar that matches application design system
- Store: Enhanced MindsetStore with skipAds: boolean state and setSkipAds method
- Logic: Created isAdChapter() function to identify advertisement chapters …

feat: skip adds for graphmindset
