stakwork/sphinx-nav-fiber

- .eslintrc.js
- package.json
- src/components/Stats/index.tsx
- src/components/Universe/Controls/CameraControls/index.tsx
- src/components/Universe/Controls/index.tsx
- src/components/Universe/Controls/useControlsEvents/index.ts
- src/components/Universe/Graph/index.tsx
- src/components/Universe/Graph/useGraphMouseEvents/index.tsx
- src/components/Universe/Tooltip/index.tsx
- src/stores/useDataStore/index.ts
- yarn.lock
> feat: add node highlight with camera

- src/components/Stats/index.tsx
- Adds twitter spaces number to stats display, reduce comment count
> Twitter spaces stat

- src/components/App/SideBar/Actions/index.tsx
- src/components/App/SideBar/Creator/index.tsx
- src/components/App/SideBar/index.tsx
- src/stores/useAppStore/index.ts
Adds an error section for users to submit information and feedback is provided to the user.
- reference: https://github.com/stakwork/sphinx-nav-fiber/issues/32
https://user-images.githubusercontent.com/61718801/193950535-05453fe2-e7c2-419f-b9b6-712bf932c367.mp4
> Issue 32/user flag errors

- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/Booster/index.tsx
- src/components/Stats/index.tsx
closes issue#64, closes issue#63, closes issue#62
> feat: closes issue#64, closes issue#63, closes issue#62

- src/components/App/SideBar/Transcript/index.tsx
> feat: transcript close button

- package-lock.json
Reverts stakwork/sphinx-nav-fiber#90
> Revert "fix: removed lock file"

- src/components/SearchBar/index.tsx
> fix: add autocorrect off for search input

- src/components/Universe/Graph/Cubes/Cube/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
Changed highlight logic for nodes, if user searches for guest name and surname, only searched guest is highlighted, if there is not such guest, nodes with name and surname will be highlighted
> feat: add highlight for full query

- src/components/AddNodeModal/TagInput/index.tsx
- src/components/AddNodeModal/index.tsx
- src/components/BaseTextArea/WebTextArea/index.tsx
- src/components/BaseTextInput/index.tsx
- limits on character count and tag count
- resizes Description
- limits timestamp values
- Updates corresponding tooltips to include count
- references #116
> Update/form validation/jx

- src/utils/getLSat/index.ts
changed hardcoded "https://knowledge-graph.sphinx.chat" url to API_URL variable
> fix: changed hardcodedurl to api_url

- src/components/Universe/Tooltip/index.tsx
- src/network/fetchGraphData/index.ts
- src/types/index.ts
profile pictures for guests with same names was messed up, to fix that, we added ref_id to guests.
> add ref_id for guest nodes, add twitter handle to tooltip

- src/components/App/SideBar/CategorySelect/index.tsx
- src/components/App/SideBar/Transcript/index.tsx
- src/components/App/SideBar/index.tsx
- src/components/Universe/Graph/Cubes/Cube/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
- src/components/Universe/index.tsx
- src/components/common/Text/index.tsx
- src/stores/useDataStore/index.ts
- src/types/index.ts
> feat: add node category filter

- package.json
- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/App/SideBar/Relevance/index.tsx
- src/components/DataRetriever/index.tsx
- src/components/Universe/Controls/CameraControls/index.tsx
- src/components/Universe/Controls/index.tsx
- src/components/Universe/Graph/Cubes/Cube/PathwayBadge/index.tsx
- src/components/Universe/Graph/Cubes/Cube/index.tsx
- src/components/Universe/Graph/Cubes/Cube/useMaterial/index.ts
- src/components/Universe/Graph/index.tsx
- src/components/Universe/index.tsx
- yarn.lock
https://github.com/stakwork/sphinx-nav-fiber/issues/164
> feat: add graph pathway layout

- package.json
- src/components/App/SideBar/TwitData/index.tsx
- src/components/App/SideBar/View/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
- src/constants/index.ts
- src/network/fetchGraphData/index.ts
- src/types/index.ts
added twitter type node, for embedded twits
> feat: add twitter node

- src/components/App/SecondarySidebar/Sources/index.tsx
added filters to sources table
> feat: add filters to table

- .gitignore
- cypress/e2e/addNode.cy.ts
- src/components/AddNodeModal/index.tsx
- src/components/App/AppBar/index.tsx
- src/components/App/FooterMenu/index.tsx
- src/stores/useModalStore/index.ts
tests will fail for now, will fix that after final approve from Sam
> feat: move add content to menu action, seperate content and source

- package.json
- src/components/AddNodeModal/index.tsx
- src/components/App/SecondarySidebar/SourcesView/QueuedSources/Table/index.tsx
- src/components/App/SecondarySidebar/SourcesView/QueuedSources/index.tsx
- src/components/App/SecondarySidebar/SourcesView/Sources/Table/index.tsx
- src/components/App/SecondarySidebar/SourcesView/Sources/index.tsx
- src/components/App/SecondarySidebar/SourcesView/constants.ts
- src/components/App/SecondarySidebar/SourcesView/index.tsx
- src/components/App/SecondarySidebar/SourcesView/types.ts
- src/components/App/SecondarySidebar/index.tsx
- src/constants/index.ts
- src/network/fetchGraphData/index.ts
- src/network/fetchSourcesData/index.ts
- src/stores/useDataStore/index.ts
add queued sources table, closes issue#229
> feat: add queued sources table

- src/components/App/SecondarySidebar/SourcesView/QueuedSources/Table/index.tsx
- src/components/App/SecondarySidebar/SourcesView/Sources/Table/index.tsx
- src/constants/index.ts
fixed layout of table for sources
> fix: change table to material ui table in sources

- src/components/App/SecondarySidebar/About/index.tsx
- src/components/App/SecondarySidebar/SourcesView/Sources/Table/index.tsx
changed about page text, fixed permission for edit
> feat: changed about page text, fixed permission for edit

- src/components/App/SideBar/Messages/index.tsx
- src/components/App/SideBar/View/index.tsx
- src/types/index.ts
- src/utils/stringToChatMessage/index.ts
added new node type "tribe_message"
> feat: add tribe_message nodes

- src/network/fetchGraphData/index.ts
added id for nodes, because otherwise an error occurred with selected node
> fix: added ids to nodes, to prevent falsy popup with node content

- src/stores/useDataStore/index.ts
> fix: stop rotation after node select

- cypress/e2e/addNode/addNode.cy.ts
- cypress/e2e/addNode/const.ts
- cypress/e2e/graph/initialRender.cy.ts
- cypress/e2e/graph/searchAndRender.cy.ts
- cypress/e2e/sentimentChart/sentimentAnalysis.cy.ts
- cypress/e2e/sentimentChart/sentimentChart.cy.ts
- package.json
- src/components/AddNodeModal/index.tsx
- yarn.lock
> fix: e2e tests

- src/components/App/SideBar/AudioClip/index.tsx
- src/components/App/SideBar/Creator/Heading/index.tsx
- src/components/App/SideBar/Person/index.tsx
- src/components/App/SideBar/Show/index.tsx
- src/components/App/SideBar/Transcript/index.tsx
- src/components/Universe/Graph/Cubes/Cube/components/HtmlPanel/constants.ts
- src/components/Universe/Graph/Cubes/Cube/components/HtmlPanel/index.tsx
- src/components/Universe/Graph/Cubes/Cube/index.tsx
- src/components/Universe/Graph/Cubes/Highlights/animated.tsx
- src/components/Universe/Graph/Cubes/RelevanceBadges/index.tsx
- src/components/Universe/Graph/UI/NodeControls/constants.ts
- src/components/Universe/Graph/UI/NodeControls/index.tsx
- src/components/Universe/Graph/UI/index.tsx
- src/components/common/Avatar/index.tsx
- src/stores/useDataStore/index.ts
closes #309 
what's new?
- close button for the floating node details panel (changes in node controls component)
- smaller node details panel
- shrunk content within details panel
https://www.loom.com/share/6142816bd3464587979fb94cbcea50df
> feature: Closeable node details panel

- src/components/Universe/Graph/UI/index.tsx
> feat: add closer to window

- src/index.css
styled the scroll bar to add a touch of polish
> feat: styled scroll bar

- src/components/App/SideBar/AudioClip/index.tsx
- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/App/SideBar/Relevance/index.tsx
- src/components/App/SideBar/View/index.tsx
- src/components/AudioPlayer/index.tsx
- src/stores/usePlayerStore/index.ts
also fixed a bug with resetting the audio timestamp when opening the sidebar
> feat: add audio controls to the selected search result item

- .github/workflows/build.yml
going to try and see if this works
> ci: now after building we will create a new release

- src/transformers/earthGraph.ts
- src/types/index.ts
Frontend was not expecting values as it coming from backend, so I changed earth graph data transformer
> feat: added latitude longitude to graph

- src/components/Universe/Graph/Cubes/RelevanceBadges/PathwayBadge.tsx
- src/components/Universe/Graph/Cubes/RelevanceBadges/index.tsx
- src/components/Universe/Graph/Cubes/RelevanceBadges/styles.ts
- src/components/Universe/Graph/Cubes/RelevanceBadges/types.ts
- src/components/Universe/Graph/index.tsx
> fix: remove the highlighted nodes #374

- src/components/App/Helper/BoostAmt.tsx
- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/App/SideBar/YouTube/index.tsx
- src/components/Booster/index.tsx
- src/components/Icons/BoostIcon.tsx
- src/utils/boost/index.tsx
also fixed boost functionality as we were getting 500 error response from for inputting incorrect inputs
This is for this issue https://github.com/stakwork/sphinx-nav-fiber/issues/391 but does not finish it yet will need to add a few more PR's since this is only for youtube
> feat: added boost button to youtube

- src/transformers/earthGraph.ts
node positions used to be calculated not correctly, fixed that
> fix: fixes node position calculation for earth graph

- src/components/AddNodeModal/RSSFeed/index.tsx
closes #445 
Chahnged max length for rss feed input from 50 to 200
> fix: change max length to 200

- src/components/Booster/index.tsx
resolves this comment
https://github.com/stakwork/sphinx-nav-fiber/issues/391#issuecomment-1743339770
> feat: make boost button not go away

- src/components/App/SideBar/YouTube/index.tsx
Swapped episode title for show title on youtube videos.
closes #400
> Show title 

- src/components/SourcesTableModal/SourcesView/Topics/Filter/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/index.tsx
- src/components/SourcesTableModal/SourcesView/common/index.tsx
- src/constants/index.ts
- src/types/index.ts
added new fields, added sort, changed layout
closes issue#519
> feat: add edge count, date, nodes to topics table

- .github/workflows/test.yml
- .github/workflows/unit-test.yml
- package.json
I'm adding a new git action seperatly for unit tests
relates to this issue https://github.com/stakwork/sphinx-nav-fiber/issues/535
> test: added unit test to their own git action

- src/components/common/ConfirmPopover/index.tsx
> feat: change popover z-index

- src/components/AddContentModal/SourceStep/__tests__/index.ts
- src/components/AddContentModal/SourceStep/index.tsx
- src/components/AddContentModal/SourceStep/utils/index.ts
I noticed there was an issue with a twitter URL that should have worked
> test: added test for twitter youtube and mp3 regex

- .github/workflows/test.yml
- README.md
- package.json
- src/components/App/SideBar/Relevance/Episode/TypeTweet/TypeTweet.cy.tsx
- yarn.lock
closes #559 
- adds git workflow for component test
> Git action component test

- src/components/App/MainToolbar/index.tsx
> Added Settings cog

- src/components/App/MainToolbar/index.tsx
Update text to 'Settings'
Hide Sentiment Analysis button as per #539
> Update menu item for Settings and Sentiment

- src/components/App/SideBar/index.tsx
> fix: hid details section for Person view

- package.json
- src/network/fetchGraphData/__tests__/index.ts
- src/network/fetchGraphData/index.ts
- src/stores/useDataStore/index.ts
Adding test for how we generate our graph, will need to add more scenarios
@tomsmith8 if you can think of scenarios to test that would be helpful and then we can add new things to the response and try to get our tests working
> [test] graph gen

- src/components/App/MainToolbar/index.tsx
- src/components/App/SideBar/Relevance/Episode/index.tsx
> feat: hide link icon, if link is not there

- src/components/App/SideBar/Trending/BriefDescriptionModal/index.tsx
[✅ ]If text is too large for pop up modal, add a scroll functionality
> Added scroll functionality to TLDR pop up #629

- src/components/common/TextInput/index.tsx
cursor to focus on the input field is set by default
> fix(issue #644): resolves the issue

- src/components/AddContentModal/index.tsx
- src/network/fetchSourcesData/index.ts
- src/utils/getSignedMessage/index.ts
- src/utils/index.ts
Boltwall expects message and signature for admin endpoints
Admin needs to pass a message and signature as a query 
I added message and Signature to all admin endpoints we have currently
None
None
> feat: added signature and message to all admin routes as query

- src/components/App/ActionsToolbar/PlayerControl/index.tsx
implemented expanded functionality for mini-player
https://www.loom.com/share/2fffd02c201e45f3962ea1be2a1cbbe6?sid=28c96afe-5565-4445-b8bb-994a88a42088
> feat: implemented expand functionality for miniplayer

- package.json
- yarn.lock
changed sphinx bridge version to 0.2.62
None
> chore: changed sphinx bridge version to 0.2.62

- src/components/App/ActionsToolbar/PlayerControl/index.tsx
- src/components/SourcesTableModal/SourcesView/Sources/index.tsx
Fixed unexpected behaviour where table flips when data is deleted 
https://www.loom.com/share/0558225bfb114863ac04a733a9d78412?sid=f99ba814-c505-4dce-aa59-70da64b45018
> Fix table flips after delete

- src/components/AddContentModal/index.tsx
- src/components/AddContentModal/utils/__tests__/index.ts
- src/components/AddContentModal/utils/index.ts
- src/constants/index.ts
- src/utils/getLSat/index.ts
Added Twitter broadcast #718
Added Twitter broadcast regex
> feat: added twitter broadcast regex #718

- src/components/Universe/Controls/CameraAnimations/index.ts
Into animation plays on any move
Into animation plays only on graph style change
Moved intro animation to separate useeffect
no
no
> feat: fix zoom

- src/components/AddContentModal/index.tsx
- src/components/AddContentModal/utils/index.ts
Add support for RSS feed
Added 1 more else if condition for RSS feed 
Solves #728
> Update Add Content form to support RSS feed

- src/components/AddContentModal/utils/__tests__/index.ts
- src/components/AddContentModal/utils/index.ts
Add RSS feed to regex check #727
Added RSS regex checker
Yes
> Added RSS feed to regex check #727

- src/components/App/SideBar/Trending/index.tsx
- src/utils/index.ts
- src/utils/trending/__tests__/index.spec.ts
- src/utils/trending/index.ts
closes #730 
Show tldr topic if present
> feat: show tldr topic if present

- src/components/SearchBar/index.tsx
closes #739
Update wording on search bar #739
Update wording on search bar
Changed the placeholder value 
I changed placeholder value 
No
> fixed the search bar placeholder #739 

- src/components/SearchBar/__tests__/index.tsx
closes #ticket_number #754
Added component tests for the SearchBar component to ensure the following functionality:
> test: added comprehensive tests for searchBar

- public/svg-icons/ExitFullScreen.svg
- public/svg-icons/FullScreenIcon.svg
- src/components/App/SideBar/SidebarSubView/MediaPlayer/ToolBar/index.tsx
- src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx
- src/components/App/SideBar/YouTube/index.tsx
- src/components/Icons/ExitFullScreen.tsx
- src/components/Icons/FullScreenIcon.tsx
@tomsmith8 mentioned how the icons for full screen were not visible and how the Youtube video would not correctly show on full Screen , this PR will fix that
> fix(screen): resolve fullscreen display issues

- src/constants/index.ts
We need to append `/api` to our boltwall base_url
We append `/api` to our boltwall base_url
appended `/api` to our boltwall base_url
none
none
> refactor: added /api as prefix to API_URL

- src/constants/index.ts
hotfix, none
backend for localhost does not work
add valid endpoint when on localhost
apiUrlFromSwarmHost is updated
not
> feat: fix endpoint for backend while on localhost

- src/components/App/SideBar/Dropdown/index.tsx
Closes #776 
Update wording and order for Filters
> chore: update wording and order for filters

- src/components/AddContentModal/BudgetStep/__tests__/index.tsx
- src/components/AddContentModal/BudgetStep/index.tsx
closes #784
Wrote Component Test for BudgetSteps
> test: unit tests for budget steps

- src/components/App/index.tsx
-
Sometimes auth window appears instanly
fix flow for auth
updated useEffect array
-
> fix: fix auth on initial load

- src/components/App/SideBar/Trending/BriefDescriptionModal/index.tsx
- src/components/App/SideBar/Trending/index.tsx
closes #775
Added Load More button
Added Load More button
https://github.com/stakwork/sphinx-nav-fiber/assets/20900042/92ec18e1-b5e8-42ca-aff3-c10789d880e1
> feat: load more button added

- src/components/App/Helper/SentimentAnalysis/index.tsx
- src/components/App/SecondarySidebar/Sentiment/index.tsx
- src/components/App/index.tsx
- src/components/Auth/index.tsx
- src/components/Universe/Graph/index.tsx
- src/utils/getLSat/index.ts
- src/utils/getSignedMessage/index.ts
- src/utils/isSphinx/__tests__/index.ts
- src/utils/isSphinx/index.ts
- src/utils/logger/logger.ts
- src/utils/payLsat/index.ts
-
App was showing black screen due to sphinx bridge handling only on request at a time
decrease sphinx bridge calls,
moved constant values to sessionStorage, created queue for sphinx calls
added test for isSphinx util
> feat: moved is sphix to sessionstorage, added queue for sphinx requests

- src/components/App/ActionsToolbar/GraphViewControl/index.tsx
- src/components/Button/index.tsx
- src/components/SettingsModal/SettingsView/Appearance/__test__/index.tsx
- src/components/SettingsModal/SettingsView/Appearance/index.tsx
The `Appearance` component within the `SettingsView` of the Sphinx Nav Fiber project lacked specific unit tests to ensure its correct rendering and functionality. These tests are crucial to maintain the reliability and stability of the user interface, especially when changes are made to the component in the future.
The tests aim to verify two main aspects of the `Appearance` component:
1 **Correct Rendering:** The component should render correctly, displaying all its elements as intended.
2 **Functionality on Save Button Click:** When the 'Save changes' button is clicked, the component should perform two actions:
- Call `localStorage.setItem` to persist the selected graph style setting.
- Trigger the `onClose` callback to close the component or modal.
- **Ticket Number:** [ 789 ]
- …
> Add [UNIT TEST ]: Add Unit Test For Appearance (Settings)

- src/components/App/MainToolbar/__test__/index.tsx
- src/components/App/MainToolbar/index.tsx
closes #785 
Wrote unit tests for Maintoolbar
> test: unit tests for maintoolbar

- src/components/App/MainToolbar/__test__/index.tsx
- src/components/App/SideBar/Trending/BriefDescriptionModal/__tests__/index.tsx
- src/components/App/SideBar/Trending/BriefDescriptionModal/index.tsx
> fix: fix build

- babel.config.js
- src/components/SettingsModal/SettingsView/utils/__tests__/index.tsx
closes #787 
Written tests for SettingsView
> #787 tests/SettingView Component in SettingsModal

- src/components/App/SideBar/YouTube/index.tsx
closes #825 
scrolling on videos was not working 
scroll is working I tried several different things but the only solution that was working was wrapping the div around the whole wrapper
wrapping the div around the whole wrapper
[screen-capture.webm](https://github.com/stakwork/sphinx-nav-fiber/assets/20900042/7e8af763-82ed-41ed-9e13-d7fccdabcb0a)
> feat: scrolling fixed on videos

- src/components/AddContentModal/BudgetStep/__tests__/index.tsx
- src/components/AddContentModal/BudgetStep/index.tsx
closes #836 
Written tests for BudgetStep
> test: add test case -> getPriceData response is free

- src/components/App/SideBar/Relevance/Episode/TypeTweet/TypeTweet.cy.tsx
> feat: removed some test cases, added reasoning in todo

- src/components/App/Helper/AskQuestion/index.tsx
- src/components/App/Helper/TeachMe/index.tsx
- src/components/App/Providers/Socket/SocketContext.ts
- src/components/App/Providers/Socket/index.tsx
- src/components/App/Providers/index.tsx
- src/components/App/index.tsx
- src/components/AppContainer/index.tsx
- src/hooks/useSockets/index.ts
> feat: update websocket

- src/components/App/SideBar/Description/index.tsx
- src/components/App/SideBar/Relevance/Episode/TypeTweet/index.tsx
- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/App/SideBar/Transcript/index.tsx
- src/components/App/SideBar/Trending/index.tsx
Font improvements #842
closes #842
Some UI Improvements 
styling tweaks
> feat: font improved

- src/components/SourcesTableModal/SourcesView/constants.ts
Remove "TOPICS" and all its imports from source_table
> fix: removed column from source table

- src/components/AddItemModal/BudgetStep/__tests__/index.tsx
- src/components/AddItemModal/BudgetStep/index.tsx
- src/components/AddItemModal/SourceStep/index.tsx
- src/components/AddItemModal/SourceStep/utils/__tests__/index.ts
- src/components/AddItemModal/SourceStep/utils/index.ts
- src/components/AddItemModal/SourceTypeStep/Component/dropdown.tsx
- src/components/AddItemModal/SourceTypeStep/index.tsx
- src/components/AddItemModal/index.tsx
- src/components/AddItemModal/utils/__tests__/index.ts
- src/components/AddItemModal/utils/index.ts
- src/components/App/MainToolbar/index.tsx
- src/components/App/index.tsx
Add Item flow UI has been implemented with this PR , addressing issue #845
Loom video : https://www.loom.com/share/7375111aa15649858a891deaef32c53b
> Added Add Item Flow to SideBar

- src/utils/payLsat/__tests__/index.ts
closes #766 
add unit test for [https://github.com/stakwork/sphinx-nav-fiber/blob/master/src/utils/payLsat/index.ts](https://github.com/stakwork/sphinx-nav-fiber/blob/master/src/utils/payLsat/index.ts)
> Test pay lsat

- src/components/App/SideBar/SelectedNodeView/index.tsx
- src/components/App/index.tsx
> fix: fix podcast selected view

- src/components/AddItemModal/SourceStep/index.tsx
- src/components/AddItemModal/SourceTypeStep/Dropdown/index.tsx
- src/components/AddItemModal/SourceTypeStep/index.tsx
- src/components/App/MainToolbar/index.tsx
> feat: replace add item icon

- src/components/App/SideBar/Person/__tests__/index.tsx
- src/components/App/SideBar/Person/index.tsx
closes: #869
Wrote test for selected Person Node
> [Component Tests] Person Node in sidebar

- src/components/App/SideBar/Episode/Heading/__tests__/index.tsx
closes: #870
Wrote test for Episode Heading in sidebar
> [Component Tests] Episode Heading in sidebar

- src/components/App/Helper/BoostAmt.tsx
- src/components/App/SideBar/TwitData/__tests__/index.tsx
- src/components/Booster/index.tsx
closes #873 
Add unit test for `src/components/App/SideBar/TwitData/index.tsx`
> [Component Tests] Twitdata - sidebar

- src/components/AddItemModal/SourceTypeStep/Dropdown/index.tsx
> feat: remove show from dropdown

- src/components/App/SideBar/Media/__tests__/index.tsx
closes: #872
Wrote unit tests for `src/components/App/SideBar/Media/index.tsx`
> [Component Tests] Media - Sidebar

- src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/EditTopicModal/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx
- src/network/fetchSourcesData/index.ts
- src/types/index.ts
modified the delete topic flow and the update node flow
associated jarvis-backend change
https://github.com/stakwork/jarvis-backend/pull/862
associated boltwall change
https://github.com/stakwork/jarvis-boltwall/pull/143
> feat: Update node

- src/components/App/SideBar/Transcript/index.tsx
Add More button on transcript section 
closes #841
Added button ...more
Added button ...more
No
> feat: added more button

- src/components/App/DeviceCompatibilityNotification/__tests__/index.tsx
closes #909 
Wrote unit tests for `src/components/App/DeviceCompatibilityNotification/index.tsx`
> [Component Tests] Device Compatibility

- src/components/Stats/__tests__/index.tsx
- src/components/Stats/index.tsx
closes #892 
Wrote test for `src/components/Stats/index.tsx`
> [Component Tests] Stats

- src/components/App/SideBar/Trending/__tests__/index.tsx
- src/components/App/SideBar/Trending/index.tsx
closes #874
Wrote tests for `src/components/App/SideBar/Trending/index.tsx`
> [Component Tests] Trending - Sidebar

- src/components/SettingsModal/SettingsView/General/index.tsx
- src/components/SettingsModal/SettingsView/General/utils/__tests__/index.tsx
> Remove Requirements from General Settings form

- src/components/AddItemModal/index.tsx
- src/components/App/MainToolbar/index.tsx
- src/components/App/SideBar/Relevance/__tests__/index.tsx
- src/components/App/SideBar/Trending/__tests__/index.tsx
- src/components/ModalsContainer/EditNodeNameModal/Title/index.tsx
- src/components/ModalsContainer/RemoveNodeModal/Body/index.tsx
- src/components/SettingsModal/SettingsView/General/utils/__tests__/index.tsx
- src/components/Stats/__tests__/index.tsx
- src/components/Universe/Graph/UI/NodeControls/index.tsx
- src/utils/formatBudget/index.ts
> feat: fix bullets for node ticket 899

- src/components/App/SideBar/SelectedNodeView/Document/index.tsx
- src/components/App/SideBar/SelectedNodeView/index.tsx
- src/types/index.ts
> feat: add play for document

- src/components/Stats/__tests__/index.tsx
- src/components/Stats/index.tsx
- src/stores/useDataStore/index.ts
- src/types/index.ts
closes #930
https://www.loom.com/share/836ca5013f0b46519667142ad2120f33?sid=b74fab84-db03-4f02-8362-5ead4d15bd5b
> onClick button for each item in the stats bar calls `/latest` with the appropriate `media_type`

- src/components/Stats/index.tsx
set skip_cache param as true onClick of each stat
> feat: added skip_cache param as true onClick of each stat

- src/components/App/SideBar/Relevance/index.tsx
- src/components/ModalsContainer/RemoveNodeModal/Body/index.tsx
- src/stores/useDataStore/index.ts
This is some enhancements to removeNode 
We now close the screen, have a toast that we removed the node, delete node from our local list, unselect the node
related PR I would not merge this till this is merged
https://github.com/stakwork/jarvis-backend/pull/878
> feat: removeNodesEnhanced

- src/components/AddItemModal/SourceTypeStep/constants.ts
> feat: removed extra type

- src/components/App/SideBar/Trending/__tests__/index.tsx
> Test trending

- src/components/Stats/index.tsx
closes #943
Update stats pill bar to use total nodes 
changed from audio to node as required 
Tests were present no updates required
> feat: changes added no changes required in tests

- src/components/App/SideBar/Trending/__tests__/index.tsx
- src/components/App/SideBar/Trending/index.tsx
> fix: fix add item button jumping around

- src/components/App/SideBar/SelectedNodeView/__tests__/index.spec.tsx
Add tests for the `SelectedNodeView` component.
- `src/components/App/SideBar/SelectedNodeView/___tests__/index.spec.tsx`
- **Ticket Number:** [ 866 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/866 ]
> Add Test[SelectedNodeView]:  Write tests for the SelectedNodeView component

- package.json
- src/components/App/SideBar/Media/__tests__/index.tsx
- src/components/App/SideBar/SidebarSubView/__tests__/index.tsx
- src/components/App/SideBar/SidebarSubView/index.tsx
- src/components/App/SideBar/Trending/__tests__/index.tsx
closes #952 
Added unit tests for `src/components/App/SideBar/SidebarSubView/index.tsx`
> [Component Tests] SidebarSubview - Sidebar

- src/components/ModalsContainer/AddNodeEdgeModal/Body/index.tsx
- src/components/ModalsContainer/RemoveNodeModal/Body/index.tsx
- src/components/common/Toast/toastMessage.tsx
- src/stores/useDataStore/index.ts
> feat: add message on close modal

- src/components/common/AutoComplete/index.tsx
- src/utils/colors/index.tsx
> style: Update dropdown style over all dropdowns

- src/components/App/SideBar/Relevance/__tests__/index.tsx
- src/components/App/SideBar/Relevance/index.tsx
> feat: add sort for topics

- src/components/App/SideBar/Description/index.tsx
- src/components/App/SideBar/Episode/Heading/index.tsx
- src/components/App/SideBar/Media/index.tsx
- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/App/SideBar/SelectedNodeView/Document/index.tsx
- src/components/App/SideBar/TwitData/index.tsx
- src/components/common/Highlight/Highlight.tsx
- src/components/common/Highlight/__tests__/index.tsx
closes: Highlight keyword if found in text or description
#944
[x] episode 
[x] document 
[x] tweet
[x] twitterSpaces 
[x] Video
add search highlight episode document tweet twitterSpaces 
https://github.com/stakwork/sphinx-nav-fiber/assets/20900042/3b38f91b-8c3f-4ecd-bdc6-8e1b738d6180
Added
> feat: added search highlight episode document tweet

- src/components/App/SideBar/Dropdown/__tests__/index.tsx
- src/components/App/SideBar/Dropdown/index.tsx
- src/components/App/SideBar/Latest/__test__/index.tsx
- src/components/App/SideBar/Latest/index.tsx
- src/components/App/SideBar/Relevance/index.tsx
- src/components/App/SideBar/SelectedNodeView/__tests__/index.tsx
- src/components/App/SideBar/SelectedNodeView/index.tsx
- src/components/App/SideBar/SidebarSubView/__tests__/index.tsx
- src/components/App/SideBar/SidebarSubView/index.tsx
- src/components/App/SideBar/Trending/__tests__/index.tsx
- src/components/App/SideBar/Trending/index.tsx
- src/components/App/SideBar/__tests__/index.tsx
- src/components/App/SideBar/index.tsx
- src/stores/useAppStore/index.ts
closes #912
Wrote unit tests for this file `src/components/App/SideBar`
> [Component Tests] Sidebar

- src/components/App/SideBar/__tests__/index.tsx
- src/components/Universe/Graph/Cubes/SelectionDataNodes/index.tsx
> feat: removed console.log

- src/components/AddContentModal/BudgetStep/index.tsx
- src/components/AddItemModal/BudgetStep/index.tsx
issue:#887
added loader to button while loading state is true
loom video:https://www.loom.com/share/5a46b88a911a496a97ac036937d03914
> loader on button while cost is being approved

- src/components/AppContainer/index.tsx
- src/network/fetchGraphDataNew/index.ts
> feat: set default view to old view

- src/components/App/ActionsToolbar/GraphViewControl/index.tsx
- src/components/App/SideBar/index.tsx
- src/components/AppContainer/index.tsx
- src/components/AppNew/SideBar/index.tsx
- src/components/Auth/index.tsx
- src/components/Universe/Graph/Cubes/RelevanceBadges/index.tsx
- src/stores/useFeatureFlagStore/index.ts
> feat: revert pr 972, move new graph to feature toggle

- src/components/AppNew/ActionsToolbar/index.tsx
> feat: fix graph view control

- src/components/App/SideBar/SidebarSubView/MediaPlayer/ToolBar/index.tsx
- src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx
closes #1027
Fix fullscreen button on Media player
https://www.loom.com/share/3176c37a610a467e801baef4e9fe1504?sid=198c3c0c-df3c-4c48-be68-b04f93254e25
> fix: Full screen button is broken

- src/components/App/SideBar/Transcript/__tests__/index.tsx
- src/components/App/SideBar/Transcript/index.tsx
closes: #1028
https://www.loom.com/share/4210f1f9e05345038abeebb5c648c4d3?sid=bb0dc9a5-47ee-4425-910e-ea3bec41734f
> Revert copy button after click

- .github/workflows/test.yml
Added steps to download machine learning neo4j data into neo4j in our CI/CD pipeline
> feat: download neo4j data and import

- src/components/App/SideBar/Relevance/index.tsx
- src/components/App/SideBar/__tests__/index.tsx
- src/components/App/index.tsx
closes #949 
For an exact keyword match, the node whose label matches the search is automatically selected on the graph
https://www.loom.com/share/23fa8ca4e8584b449b39d201d3eed61c?sid=a2840149-7475-466e-ab02-86179ebc2c98
> feat: Exact match keyword should take the user to the selectedview of the topic

- src/components/App/SideBar/Relevance/index.tsx
> fix: revert selection first node

- src/components/SettingsModal/SettingsView/General/index.tsx
increased character limit for graph description
> Increased character limit for graph description

- src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
- src/stores/useTopicsStore/index.ts
> feat: fix sort for table

- .vscode/settings.json
- package.json
- src/components/AddContentModal/index.tsx
- src/components/App/Helper/AskQuestion/index.tsx
- src/components/App/Helper/TeachMe/index.tsx
- src/components/AppNew/Helper/AskQuestion/index.tsx
- src/components/AppNew/Helper/TeachMe/index.tsx
- src/components/Booster/index.tsx
- src/components/ModalsContainer/RemoveNodeModal/Body/index.tsx
- src/components/common/SuccessToast/index.tsx
- src/components/common/Toast/toastMessage.tsx
- yarn.lock
issue:#989
This PR will implement new design for Success Toast
> Success toast

- src/components/AddContentModal/index.tsx
- src/network/api/index.ts
- src/network/fetchSourcesData/index.ts
Added Signature and Message to the `node/content` endpoint
> feat: added signature and message to node/content endpoint

- src/components/AddItemModal/BudgetStep/__tests__/index.tsx
- src/components/App/MainToolbar/index.tsx
- src/components/App/Toasts/index.tsx
- src/components/AppNew/Universe/GraphNew/Cubes/SelectionDataNodes/index.tsx
- src/components/AppNew/Universe/GraphNew/Cubes/SelectionDataNodes/simulation/index.ts
- src/components/common/SuccessToast/index.tsx
- src/network/fetchGraphDataNew/index.ts
- src/network/fetchGraphDataNew/utils/prepareGraphDataCircle.ts
> feat: fix toast color

- src/components/SourcesTableModal/SourcesView/Content/Table/TableRow.tsx
- src/components/SourcesTableModal/SourcesView/constants.ts
closes: #1092
- **Ticket Number:** [ 1092 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1092 ]
- Manual testing was conducted to verify that the new integration works as expected.
https://www.loom.com/share/abce119abad94ae99985553785f5d0d3
> Enhanced External Linking for View Content Source

- src/components/AppContainer/index.tsx
- src/components/AppNew/SideBar/index.tsx
- src/components/AppNew/Universe/GraphNew/index.tsx
- src/components/AppNew/Universe/Overlay/Search/index.tsx
- src/components/AppNew/Universe/Overlay/TypesNavigation/index.tsx
- src/components/AppNew/Universe/Overlay/index.tsx
- src/components/AppNew/index.tsx
- src/network/fetchGraphDataNew/index.ts
> feat: added search for v2 graph

- src/components/AppContainer/index.tsx
> fix: revert default view

- src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx
- src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
> feat: fixed icons, and table layout

- src/components/App/MainToolbar/index.tsx
> Tapping the top left triggers success message

- src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx
- src/components/SourcesTableModal/SourcesView/Topics/Table/__tests__/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
- src/components/SourcesTableModal/SourcesView/common/index.tsx
closes: #1082
- **Ticket Number:** [ 1082 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1082 ]
- Manual testing was conducted to verify that the new integration works as expected.
https://www.loom.com/share/cc968235cb8f4042ab994d27d131a222
> Fix(table-topic): Implement multi-select functionality

- src/components/AddTypeModal/CustomAttributesStep/FormInput/index.tsx
- src/components/AddTypeModal/index.tsx
- src/components/SettingsModal/SettingsView/GraphBlueprint/index.tsx
> feat: auto update, remove notification

- src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
> feat: update edit node name to work with any node

- src/components/AddItemModal/index.tsx
closes #1153
Remove bottom success message in add item flow
> Duplicate success msg

- src/components/AddItemModal/SourceTypeStep/index.tsx
Remove certain node_types during AddItem flow
closes #1159
https://www.loom.com/share/bc441d1e87884e1396f55cc4221e4b74?sid=6a759fa6-3dcb-4b2c-8865-4c53d25bedee
> Remove certain node_types during AddItem flow

- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/App/SideBar/Relevance/__tests__/index.tsx
- src/components/App/SideBar/Relevance/index.tsx
- src/components/App/SideBar/SelectedNodeView/Document/index.tsx
- src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
- src/components/SettingsModal/SettingsView/index.tsx
> feat: fix image

- src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx
- Link: https://github.com/stakwork/sphinx-nav-fiber/issues/1120
closes #1120
Loading icon is not in the same place as mute icon
https://www.loom.com/share/db7fc64e0b424225aec69f8941f944d5?sid=c9851bdc-de82-40ed-8fa0-0212b1310b73
> Fixed loading icon position

- src/components/SourcesTableModal/SourcesView/Topics/Table/__tests__/index.spec.tsx
- src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/index.tsx
- src/components/SourcesTableModal/SourcesView/types.ts
https://github.com/stakwork/sphinx-nav-fiber/pull/1119#issuecomment-2024783327
https://github.com/stakwork/sphinx-nav-fiber/pull/1119#issuecomment-2025175925
> fix(add-multi-topic): add multi-select to topic table

- src/components/AddItemModal/SetAttributesStep/index.tsx
- src/components/AddItemModal/index.tsx
> fix: enable input fields and post node data

- src/components/AddTypeModal/Body/CustomAttributesStep/FormInput/index.tsx
- src/components/App/index.tsx
- src/components/SettingsModal/SettingsView/index.tsx
- src/network/fetchGraphData/index.ts
> feat: test unit run

- src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx
- src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
- src/network/fetchGraphData/index.ts
- src/types/index.ts
> feat: update image for generic nodes

- src/components/ModalsContainer/AddNodeEdgeModal/Body/index.tsx
> feat: fix add edge to node

- src/components/SourcesTableModal/SourcesView/Content/index.tsx
> Style Changes For Load More Button [ Add Content ]

- src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
https://github.com/stakwork/sphinx-nav-fiber/pull/1170#issuecomment-2038016447
> fix(add-multi-topic): Mute and Unmute the selected fields

- src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
- src/components/ModalsContainer/EditNodeNameModal/Title/index.tsx
- src/components/ModalsContainer/EditNodeNameModal/utils/__tests__/index.ts
- src/components/ModalsContainer/EditNodeNameModal/utils/index.ts
- src/types/index.ts
closes: #1176 
Edit node add image to any node
https://www.loom.com/share/81cc832b0f8945a5b9065b678681d7d3?sid=5f154438-ec88-4f8d-b674-f4950ac8d0cc
> Edit node add image to any node

- src/components/SettingsModal/SettingsView/index.tsx
- src/components/SourcesTableModal/SourcesView/index.tsx
closes #1193
The top left and top right corner of modals are not rounded correctly.
- Source Table
- Settings
- Setting:
- Source Table:
> UI display issue with rounding and background

- src/components/ModalsContainer/AddNodeEdgeModal/Title/ToNode/index.tsx
- src/components/ModalsContainer/AddNodeEdgeModal/Title/index.tsx
> feat: improve layout for add edge

- src/components/common/TextInput/index.tsx
Space needed between label and input field at Add Location step
closes #1202
As a Proof:
> Space needed between label and input field at Add Location step

- src/components/ModalsContainer/AddNodeEdgeModal/Title/index.tsx
> feat: small icon fix

- src/components/AddItemModal/SourceTypeStep/__tests__/index.tsx
- src/components/App/SideBar/TwitData/index.tsx
- src/components/Booster/__tests__/index.spec.tsx
closes #1225
changed profile_picture to image_url to display image properly in selectedNode subview
> fix: image_url not showing in middle section

- src/components/App/SideBar/Media/__tests__/index.tsx
- src/components/App/SideBar/Media/index.tsx
closes  #1229
The transcript section is displaying even though there is no transcript text
https://www.loom.com/share/05619ddeecd64672b724541a9d245577?sid=6e7467fa-c64a-4de8-b754-1af9195853b4
> Display transcript only when available

- src/components/AddTypeModal/Body/index.tsx
> feat: add type instead of parent for edit schema

- src/components/AddItemModal/SourceTypeStep/__tests__/index.tsx
- src/components/AddItemModal/SourceTypeStep/index.tsx
- src/components/SettingsModal/SettingsView/GraphBlueprint/index.tsx
> fix: filter out invalid schema options

- .github/workflows/test.yml
- cypress/e2e/trendingTopics/trendingTopics.cy.ts
- cypress/fixtures/trendingTopics.json
- cypress/support/e2e.ts
Cypress test for trending topics
> test: added trending topics test

- src/components/AddItemModal/SetAttributesStep/index.tsx
- src/components/AddItemModal/index.tsx
closes #1263
Next button active even when type is not selected
https://www.loom.com/share/ae813f4b557c473984ddf3a053765d2a?sid=c3d5cae0-4507-47bc-bd88-2d2f9be267a7
> Next button active even when type is not selected

- src/components/App/Splash/index.tsx
This pr fixes the issue where the app displays a dark screen for offline users
> hotfix: app does not display offline

- jest.setup.js
- package.json
- src/components/AddItemModal/SetAttributesStep/index.tsx
- src/components/SettingsModal/SettingsView/GraphBlueprint/BlueprintModal/Body/Nodes/index.tsx
- src/components/SettingsModal/SettingsView/GraphBlueprint/BlueprintModal/Body/index.tsx
- src/components/SettingsModal/SettingsView/GraphBlueprint/BlueprintModal/types/index.ts
- src/components/SettingsModal/SettingsView/GraphBlueprint/BlueprintModal/utils/__tests__/index.ts
- src/components/SettingsModal/SettingsView/GraphBlueprint/BlueprintModal/utils/index.ts
- yarn.lock
> feat: update length

- src/components/SourcesTableModal/SourcesView/Topics/Search/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/index.tsx
- src/network/api/index.ts
- src/network/fetchSourcesData/index.ts
- src/stores/useTopicsStore/index.ts
> feat: add debounce and cancel to curation table

- src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
> fix: fix multiple mute unmute not working

- src/components/SettingsModal/SettingsView/GraphBlueprint/Table/TableRow.tsx
- src/components/SettingsModal/SettingsView/GraphBlueprint/Table/index.tsx
issue: #1207
https://www.loom.com/share/98ca61de152f4b2f9c97b9b7d7a56f5b
> Menu Item for Blueprint

- src/components/AddItemModal/SourceTypeStep/index.tsx
- src/components/ModalsContainer/AddNodeEdgeModal/Title/index.tsx
- src/components/common/AutoComplete/index.tsx
> feat: add labels to search dropdown

- src/components/AddItemModal/SourceTypeStep/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/AddEdgeTopicModal/Title/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/Title/ToNode/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/Title/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/index.tsx
> feat: add labels to merge topic moda

- docs/setupCypressTest.md
Added Documentation on how to setup `Sphinx Stack` for cypress test
> docs: setup documentation for running cypress e2e test

- src/components/SourcesTableModal/SourcesView/Topics/AddEdgeTopicModal/Title/ToNode/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/AddEdgeTopicModal/Title/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/AddEdgeTopicModal/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/Title/ToNode/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/Title/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/index.tsx
closes #1344
Remove the same node from search results - Add Edge and Merge
https://www.loom.com/share/851f380eb23943c593055f32ef587da0?sid=2bd33a80-f561-4258-b3f9-c469956291b8
> fix(remove-the-same-node): from search results add edge and merge

- src/components/common/ConfirmPopover/index.tsx
closes: #1281
Delete source popup is not gray
> Delete source popup is not gray

- src/components/App/Toasts/index.tsx
> fix: repositioned success notification and updated styles

- src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
> feat: check rename

- cypress/e2e/seeLatest/latest.cy.ts
- src/components/App/SideBar/index.tsx
- src/stores/useDataStore/index.ts
> hotfix: e2e cypress tests

- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/__tests__/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/index.tsx
- After I merge, the count is 0 but stays in the table
- We should remove this row
closes: #1272
- **Ticket Number:** [ 1272 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1272 ]
> Fixed: Merge Topic - Removal of Node from Table

- src/components/App/SideBar/__tests__/index.tsx
- src/components/App/SideBar/index.tsx
- src/components/SearchBar/index.tsx
closes #1391
The search bar  allow searches with empty spaces
https://www.loom.com/share/3b5e2c9b8bc1404498e48faddbb63e5a?sid=417721ab-d576-49ad-8530-315d1830b6a8
> Should not search with empty spaces in search bar

- src/components/common/TypeBadge/index.tsx
> fix: fix badge for custom node

- src/components/ModalsContainer/ChangeNodeTypeModal/index.tsx
- src/components/ModalsContainer/EditNodeNameModal/Title/index.tsx
- src/network/fetchSourcesData/index.ts
closes: #1378
- **Ticket Number:** [ 1378 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1378 ]
https://www.loom.com/share/b1f7b82a5e3548f7add6f9b9e3fdac89
> Fixed(Edit-Node): Confirm changing type (Bounty 6 of 6)

- cypress/e2e/addContent/addWebpage.cy.ts
closes: #1407
- **Ticket Number:** [ 1407 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1407 ]
> Fixed(Cypress-Test): Intermittent Failure on addContent/addWebpage.cy.ts

- src/components/App/SideBar/Show/EpisodePanel/index.tsx
- src/components/App/SideBar/Show/index.tsx
- Please observe that the content exhibits irregular vertical spacing, detracting from its visual appeal.
closes: #1416
- **Ticket Number:** [ 1416 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1416 ]
https://www.loom.com/share/d8e75d4ed13b4ddaacaf600c36fbb2a9
> Resolve Styling Issue in `Show` Type Display within [SideBarSubView]

- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/App/SideBar/SelectedNodeView/__tests__/index.tsx
- src/components/App/SideBar/SelectedNodeView/index.tsx
- src/components/common/Avatar/index.tsx
- src/components/common/Loader/index.tsx
- src/components/common/TypeBadge/index.tsx
- src/network/fetchGraphData/index.ts
> feat: updated node type

- src/components/SearchBar/index.tsx
closes https://github.com/stakwork/sphinx-nav-fiber/issues/1414
https://www.loom.com/share/ebee21bef8324a29a3c147a3aa45f715
> The search text is appearing behind the search icon in the search box, which should not happen

- src/components/Modal/index.tsx
- src/components/SourcesTableModal/SourcesView/index.tsx
closes https://github.com/stakwork/sphinx-nav-fiber/issues/1431
Demo:
https://www.loom.com/share/6cbd35517d484b9bb5c8a15c317ef098
> The Source Table modal is not responsive for all desktop screens

- cypress/e2e/sourcesTable/sourcesTable.cy.ts
closes ##1442
Intermittent test failure in cypress sourcesTable/sourcesTable.cy.ts
> Fix(intermittent-test-failure): In cypress sourcesTable file

- src/components/Stats/__tests__/index.tsx
- src/components/Stats/index.tsx
closes https://github.com/stakwork/sphinx-nav-fiber/issues/1359
> Fix processing button responsiveness

- src/components/AddContentModal/index.tsx
> feat: add error message for add content

- src/components/SettingsModal/SettingsView/index.tsx
- Scroll Overflow on the Settings table
> Fixed(Settings-Table): Scroll Overflow Issue in Normal Screen Size

- src/utils/secondsToMediaTime/__tests__/index.ts
- src/utils/secondsToMediaTime/index.ts
closes #1489
- Modified secondsToMediaTime function to format hours, minutes, and seconds properly.
- Added logic to display h:mm:ss for durations longer than an hour.
- Updated test cases to validate the new formatting requirements.
> Format Video Player Timestamp for Accurate Display

- src/components/App/MainToolbar/index.tsx
> fix: hide blueprint for non admins

- cypress/e2e/curationTable/curation.cy.ts
Updated Curation Table test to properly assert add_edge
> test: updated curation test to aseert edge is added correctly

- src/components/AddContentModal/BudgetStep/index.tsx
- src/components/AddItemModal/BudgetStep/index.tsx
> Center icon and error message

- src/components/ModalsContainer/BlueprintModal/Body/Editor/CustomAttributesStep/FormInput/index.tsx
> Update "name" attribute on blueprint to be disabled

- src/components/common/TextInput/index.tsx
closes #1540
Required error message is not being display under required input fields on clearing the text of input field and there is no border color red and blue
https://www.loom.com/share/4e1f1e201fc64235b08fe0a525abfc53?sid=dbfa681c-3bbc-4192-b5c4-a649f8a91a53
> Required error message and set the border colors

- src/components/ModalsContainer/BlueprintModal/Body/Editor/CustomAttributesStep/FormInput/index.tsx
closes #1574,  #1518
hide node_key from blue print graph attributes
https://www.loom.com/share/d3b7149cd198403aaf8414fc38f10dc2?sid=473401a3-3839-4c78-9087-78e0d5c69787
> Hide node_key from blue print graph attributes

- src/components/AddItemModal/BudgetStep/__tests__/index.tsx
- src/components/AddItemModal/index.tsx
- src/network/addItemRequest/addItemRequests.ts
- src/network/fetchSourcesData/index.ts
- Refactor add item flow submit handler
closes: #1564
- **Ticket Number:** [ 1564 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1564 ]
https://www.loom.com/share/eb68c6e716104b8c9c2c5e5c83a8c8c5
> Fixed(addItem): Refactor AddItemModal handleSubmitForm Function

- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/index.tsx
closes #1616
- Save button loading state
- Update the node name in the blueprint graph if changed
https://www.loom.com/share/9134cdf8ceeb4a64b589de2875a82cd9?sid=1964e33f-c81b-4788-b10f-1dd6a065f386
> Save button loading state, Update the node name in the blueprint graph if changed

- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Body/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Title/ToNode/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Title/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/__tests__/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Graph/ForceGraph/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Graph/Nodes/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Graph/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Toolbar/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/__tests__/index.tsx
- src/components/common/AutoComplete/index.tsx
- src/network/fetchSourcesData/index.ts
- Create an edge between custom nodes in the Blueprint.
closes: #1581
- **Ticket Number:** [ 1581 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1581 ]
https://www.loom.com/share/60cf812620fe4d7c867837b1e6507deb
> Fixed(Blueprint ): Implemented Custom Edge Addition Functionality in Blueprint Area for Admins

- src/components/ModalsContainer/BlueprintModal/Body/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/__tests__/index.tsx
closes #1573
Scrollbar is overflowing at blueprint sidebar
https://www.loom.com/share/0dc21f4cd9e04cbbb9e642187d6846f6?sid=ffb5f144-6a34-430b-808a-f3d41bd202f7
> Scrollbar should not be overflow on blue print sidebar

- src/components/ModalsContainer/ChangeNodeTypeModal/index.tsx
closes #1612
Change Type flow - add type_to_be_deleted to the payload
> Fix(change-type-flow):  Add type to be deleted to the payload

- src/components/SourcesTableModal/SourcesView/Topics/Table/TableRow.tsx
- src/components/SourcesTableModal/SourcesView/Topics/Table/__tests__/index.spec.tsx
- src/components/SourcesTableModal/SourcesView/Topics/Table/index.tsx
closes #1650
Merge button in topic table is cut off
> Merge button in topic table is cut off

- src/components/ModalsContainer/BlueprintModal/Body/Graph/index.tsx
closes #1606
- Added support for panning using the middle mouse button
https://www.loom.com/share/1e27c61edf404e398375c009e5405c28?sid=3a90c63b-91be-478e-9d17-ddb19b7d14a7
> Support Panning graphical interface in Blueprint 

- src/components/AddItemModal/index.tsx
- src/network/addItemRequest/addItemRequests.ts
> feat: remove pubkey from node_data

- src/components/ModalsContainer/BlueprintModal/Body/Graph/ForceGraph/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Graph/Links/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Graph/Nodes/Node/index.tsx
> feat: added overlapping noes distance

- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Body/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Title/ToNode/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Title/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Graph/ForceGraph/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Graph/Links/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Graph/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/index.tsx
- src/network/fetchSourcesData/index.ts
closes #1708
[Blueprint] Edit and Delete Edge - Tapping on an edge should pop the sidebar
> Blueprint edit and delete edge tapping on an edge should pop the sidebar

- src/components/ModalsContainer/BlueprintModal/Body/Graph/Links/index.tsx
> fix: fix for links name

- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/Universe/Graph/Cubes/Cube/components/Tooltip/index.tsx
closes #1691
If node has no image_url then do not display image icon
https://www.loom.com/share/a6709f0ca5ec4c1c8e4f4ced5f7b8787?sid=a560958e-7bd6-4ff5-bb03-50be016fecd2
> If node has no image_url then do not display image icon

- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Body/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Title/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/index.tsx
closes #1726
- edit node delete and save buttons
- additionally correct the disable button logic in edit node 
https://www.loom.com/share/a389efecc4734aa39d270d78b0d5133b?sid=bcba64dd-6588-4a30-b652-f66b7ecd7eac
> Edit node delete and save buttons Also additionally correct the disable button logic in edit node 

- src/components/AppNew/Universe/GraphNew/Cubes/Cube/components/Tooltip/index.tsx
- src/components/AppNew/Universe/GraphNew/Cubes/SelectionDataNodes/Text/index.tsx
- src/components/AppNew/Universe/GraphNew/Cubes/Text/index.tsx
> fix: text node length

- src/components/SourcesTableModal/SourcesView/common/search/index.tsx
> feat: fix search with space

- src/components/App/SideBar/SelectedNodeView/Default/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- Extend the check to include link property
- If link or media_url is present, display media player.
- If link or media_url is present, don't return in middle section
- If both are present, pick media_url
closes: #1641
- **Ticket Number:** [ 1641 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1641 ]
> Fix(media-player): Media Player - Generic Nodes with link

- src/components/App/SideBar/Relevance/Episode/TypeCustom/index.tsx
- src/components/App/SideBar/Relevance/Episode/TypeDocument/index.tsx
- src/components/App/SideBar/Relevance/Episode/TypePerson/index.tsx
- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Body/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Editor/utils/index.ts
closes  #1735
Handling disability of confirm button on edit node sidebar AND Generic nodes - Date property
https://www.loom.com/share/69069d30c8d64ee0aeb9cdda51a634a6?sid=b62ae1f0-8666-4b4d-b8ed-4a83164a2d99
https://www.loom.com/share/9cb35ff106e64dd496e3096ba9a914f6?sid=e437d3bc-f23e-4fd0-af9f-ca08a93fa652
> Handling disability of confirm button on edit node sidebar (Handle disability related attributes ) AND Generic nodes - Date property

- src/stores/useFeatureFlagStore/index.ts
closes https://github.com/stakwork/sphinx-nav-fiber/issues/1746
> Create feature flag for chatInterface

- src/components/App/SideBar/SelectedNodeView/Default/index.tsx
- src/components/App/SideBar/SelectedNodeView/index.tsx
- src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx
- src/stores/useDataStore/index.ts
> feat: added player

- src/components/App/SideBar/index.tsx
- src/stores/useFeatureFlagStore/index.ts
> feat: enable filters

- src/components/App/SideBar/Dropdown/index.tsx
closes #1716
If no options then there should not be icon and dropdown popover
https://www.loom.com/share/3293036d52e24c018a8e46299e1445ef?sid=e68c06ba-55aa-41e4-a285-e75544e677bb
> If no options then there should not be icon and dropdown popover

- src/components/App/SideBar/index.tsx
- src/components/App/index.tsx
- src/components/Auth/index.tsx
- src/stores/useDataStore/index.ts
- src/types/index.ts
> fix: ai_summary query to search

- src/network/fetchSourcesData/index.ts
- src/stores/useSchemaStore/index.ts
> feat: fix for blueprint

- src/components/App/SideBar/AiSummary/AiSummaryDetail/AiQuestions/index.tsx
- src/components/App/SideBar/AiSummary/AiSummaryDetail/AiSources/index.tsx
- src/components/App/SideBar/AiSummary/AiSummaryDetail/index.tsx
- src/components/App/SideBar/Relevance/EpisodeSkeleton/index.tsx
- src/components/App/index.tsx
- src/types/index.ts
> feat: add questions

- src/components/App/AppBar/index.tsx
- src/components/App/SideBar/AiSearch/index.tsx
- src/components/App/SideBar/index.tsx
- src/components/App/UniverseQuestion/index.tsx
- src/components/SearchBar/index.tsx
- src/stores/useAiSummaryStore/index.ts
> feat: add follow up question

- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/App/SideBar/SelectedNodeView/Default/index.tsx
- Highlight the searched word or phrase if matched in the results.
- **Ticket Number:** [ 1739 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1739 ]
https://www.loom.com/share/ee1f091bcb7542049b79c7d23be61b60
> `Highlight` term in new version

- src/stores/useSchemaStore/index.ts
> feat: update schema ref-id

- src/components/App/SideBar/SidebarSubView/MediaPlayer/ToolBar/index.tsx
- src/components/App/SideBar/SidebarSubView/MediaPlayer/index.tsx
closes  #1775
When we expand sidebar subview video then progress bar showing at height
> When we expand sidebar Sub view video then on large screen progress bar shown at height

- src/stores/useAiSummaryStore/index.ts
- src/stores/useDataStore/index.ts
- src/types/index.ts
> feat: add query param

- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- Currently, the Blueprint modal Confirm button is not disabled immediately after being clicked edit modal.
- **Ticket Number:** [ 1751 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1751 ]
https://www.loom.com/share/ee53f9fc773a4693aacd3723b9d7d61f
> Fixed(BluePrint): Confirm button not disabled immediately in Blueprint

- src/components/App/UniverseQuestion/index.tsx
- https://github.com/stakwork/sphinx-nav-fiber/pull/1800#issuecomment-2228484184
> Inconsistent Padding: Ensure Equal Padding on All Sides (Left, Top, Right, Bottom)

- src/components/App/SideBar/AiSummary/index.tsx
> feat: add auto scroll for ai summary

- src/components/App/SideBar/AiSummary/AiQuestions/index.tsx
> feat: replace handler

- src/components/App/SideBar/AiSummary/AiAnswer/index.tsx
- src/components/App/SideBar/AiSummary/AiQuestions/index.tsx
- src/components/App/SideBar/AiSummary/index.tsx
- src/types/index.ts
> feat: disabled animation on rerender

- src/components/App/UniverseQuestion/index.tsx
closes #1848
Currently we are able to search on AI search bar with just empty space that is not a better User Experience
https://www.loom.com/share/b9d902ba860c4bd7b27346fe12132df7?sid=5f09a934-725f-46ad-ac03-5d99a23a1fb0
> AI search is going to make with just empty space in AI search bar( BUG )

- src/components/App/SideBar/AiSummary/AiAnswer/index.tsx
- src/components/App/SideBar/AiSummary/index.tsx
- src/components/App/SideBar/AiSummary/utils/AiSummaryHighlight/index.tsx
- src/components/App/index.tsx
- src/types/index.ts
closes https://github.com/stakwork/sphinx-nav-fiber/issues/1843
https://www.loom.com/share/babfe3cbe6fb40dc955d0ea663428733
> Update logic to render highlighted terms

- cypress/e2e/admin/signin.cy.ts
- cypress/e2e/admin/topics.cy.ts
- cypress/e2e/curationTable/curation.cy.ts
- cypress/e2e/trendingTopics/trendingTopics.cy.ts
> feat: disable failing test temporarely

- src/components/App/SideBar/AiSearch/index.tsx
closes #1851
Ask Follow-up question search bar allow search with empty space
https://www.loom.com/share/50cdae82fa8944188c2ee80b47089e9c?sid=8cfd0c9a-054a-46c0-ab97-dcf59216bcc2
> Ask Follow-Up question search bar allow search with empty space ( BUG )

- src/components/App/SideBar/AiSearch/index.tsx
- src/components/SearchBar/index.tsx
- src/stores/useAiSummaryStore/index.ts
closes #1849
Currently we are able to ask follow up question without completing the first one
https://www.loom.com/share/ad73811ea03640dea63691b8f5817bda?sid=c862ab89-fb88-4780-810a-03ec2c4b5b01
> update changes in follow-up search bar

- src/components/App/SideBar/AiSummary/utils/AiSummaryHighlight/index.tsx
closes https://github.com/stakwork/sphinx-nav-fiber/issues/1874
https://www.loom.com/share/bf30579be98f4651b974d652a0cafce8
> Issue with hover state layer

- src/components/App/UniverseQuestion/index.tsx
- Typing in search bar changes question
- **Ticket Number:** [ 1881 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1881 ]
https://www.loom.com/share/2e53616134784935a35ab9fdc3966bb9
> [Fixed] AI Chat - Typing in Search Bar Changes Question

- src/components/Universe/Graph/Cubes/Cube/components/Tooltip/index.tsx
- src/components/Universe/Overlay/index.tsx
- Make the tooltip scrollable:
closes: #1897
- **Ticket Number:** [ 1897 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1897 ]
> Fixed(Graph-Tooltip): Make the tool tip scrollable

- src/components/App/SideBar/index.tsx
closes  #1888
Currently after AI search the search bar and dropdown in side are useless
https://www.loom.com/share/79ff759eff134e709d7d41ca0c2412f5?sid=206c4769-0c7f-49ed-b7c1-98d161a7121e
> After AI search search bar and dropdown on sidebar should be hide (useless after ai search)

- src/components/ModalsContainer/MergeTopicModal/Title/index.tsx
- src/components/ModalsContainer/MergeTopicModal/index.tsx
> fix: replaced topic with selected node

- src/components/App/SideBar/SelectedNodeView/Default/index.tsx
closes https://github.com/stakwork/sphinx-nav-fiber/issues/1901
https://www.loom.com/share/5da661499def43e09a691afcd1db92bb
> AI Chat - UI Issue - Remove the underscore ("_") from labels, replace it with a space, and capitalize the first letter of each word.

- src/components/App/SideBar/AiSummary/index.tsx
- src/components/App/SideBar/index.tsx
- src/components/App/index.tsx
- src/stores/useDataStore/index.ts
- src/types/index.ts
> fix: fix loading of ai question

- src/components/App/index.tsx
- src/components/Auth/index.tsx
> feat: enable feature flag

- cypress/e2e/trendingTopics/trendingTopics.cy.ts
- src/components/Auth/index.tsx
> feat: disable auth for browser

- src/components/ModalsContainer/AddNodeEdgeModal/Title/ToNode/index.tsx
- src/components/ModalsContainer/MergeTopicModal/Title/ToNode/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/AddEdgeTopicModal/Title/ToNode/index.tsx
- src/components/SourcesTableModal/SourcesView/Topics/MergeTopicModal/Title/ToNode/index.tsx
closes #1954
When we enter 3 spaces in To input field node types start loading
https://www.loom.com/share/1d6a7cd81a964790a3c502f25393fc0b?sid=d69ad5fd-23ba-4ecd-ac8c-3a9e16adcebd
> When we enter 3 spaces in To input field node types start loading

- .github/workflows/test.yml
- cypress/e2e/addContent/addTweet.cy.ts
- cypress/e2e/addContent/addWebpage.cy.ts
- cypress/e2e/addContent/addYoutube.cy.ts
- Failing test addContent
- **Ticket Number:** [ 1753 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/1753 ]
closes: #1753
> Fixed(Cypress-Test): Failing test addContent

- .github/workflows/test.yml
- cypress/e2e/addContent/addTweet.cy.ts
- cypress/e2e/addContent/addWebpage.cy.ts
- cypress/e2e/addContent/addYoutube.cy.ts
This reverts commit 864d5837aff33aa1943cbb57e9fcef261fd3b092, reversing changes made to e9da16ccc0bcb970e80813ac27df6598467546e8.
> Revert "Merge pull request #1993 from saithsab877/cyress-test"

- src/components/App/SideBar/index.tsx
- src/stores/useDataStore/index.ts
- src/types/index.ts
> feat: added uniqnues for ai questions

- src/components/App/SideBar/AiSummary/index.tsx
- https://github.com/stakwork/sphinx-nav-fiber/pull/2001#issuecomment-2273185663
> Fixed(Add-Button): `Remove Exclamation Mark`

- cypress/e2e/seeLatest/latest.cy.ts
- src/components/App/ActionsToolbar/index.tsx
- src/components/App/SideBar/AiSearch/index.tsx
- src/components/App/SideBar/AiSummary/AiQuestions/index.tsx
- src/components/App/SideBar/AiSummary/AiSources/index.tsx
- src/components/App/SideBar/AiView/index.tsx
- src/components/App/SideBar/Latest/__test__/index.tsx
- src/components/App/SideBar/Latest/index.tsx
- src/components/App/SideBar/RegularView/index.tsx
- src/components/App/SideBar/Relevance/index.tsx
- src/components/App/SideBar/index.tsx
- src/stores/useAiSummaryStore/index.ts
- src/stores/useDataStore/index.ts
> feat: improvements for ai flow, bug fixes

- src/components/App/SideBar/AiSummary/AiQuestions/index.tsx
- src/stores/useAiSummaryStore/index.ts
> feat: fixed issue with epty answers, disabled follow questions on load

- src/components/App/index.tsx
- src/types/index.ts
> feat: fix audio for ai

- src/components/Auth/index.tsx
- src/components/SettingsModal/SettingsView/index.tsx
- src/utils/isWebView/index.ts
> feat: enabled login for anroid

- src/components/App/MainToolbar/index.tsx
- src/components/App/SideBar/AiView/index.tsx
- src/stores/useDataStore/index.ts
- The `Home` Button and `Logo Icon` Button is intermittently unavailable, preventing users from navigating back to the home page.
closes: #2009
- **Ticket Number:** [ 2009 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2009 ]
https://www.loom.com/share/f202eeb85a2c43a9b764771e8ce0b228
> [AI Chat]: Ensure `Home Button` and `LOGO` is Always Clickable for Navigation

- src/components/App/SideBar/AiSummary/AiQuestions/index.tsx
> feat: remove loader from questions

- src/components/App/SideBar/AiSummary/utils/AiSummaryHighlight/index.tsx
- Highlighted Entities Starts Duplicating
closes: #
- **Ticket Number:** [ ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/]
> Fixed(Entities): Highlighted Entities Starts Duplicating

- src/components/App/SideBar/AiSummary/AiAnswer/index.tsx
- src/components/App/SideBar/AiSummary/utils/AiSummaryHighlight/index.tsx
- src/components/common/ToolTip/index.tsx
closes #1909
When we hover over the entity in AI search answer in sidebar the tooltip is cutting off from left side
https://www.loom.com/share/cb1d07645ce54ec997f4d0dff888ec1b?sid=2d092a97-4d05-4390-a077-e5dcc546a315
> On hover over the entity in AI search answer is cutting off form left side

- src/components/Universe/Graph/Cubes/Cube/components/Tooltip/index.tsx
> feat: added node type badge to tooltip

- src/components/App/AppBar/index.tsx
closes #2037
We are not be able to go back after search by clicking on logo text that is not better UX
https://www.loom.com/share/222106dea5fa4e7ba851077a2cea5c8f?sid=4b1efd31-7cdd-4fb1-afc8-7b744fdfeb54
> We are not be able to go back after search by clicking on logo text that is not better UX

- src/components/App/SideBar/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
> feat: removed subview for nodes with only name prop

- src/stores/useDataStore/index.ts
> feat: decrease nodes limit

- src/components/Universe/Graph/Cubes/Text/index.tsx
closes https://github.com/stakwork/sphinx-nav-fiber/issues/1999
https://www.loom.com/share/43832f83df324ec181242299bd3be8b5
> Render emojis on graph view

- src/components/App/SideBar/AiSummary/AiSources/index.tsx
- src/components/App/SideBar/Media/index.tsx
- src/components/App/SideBar/Relevance/Episode/Default/index.tsx
- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/App/SideBar/Relevance/index.tsx
- src/network/fetchSourcesData/index.ts
- src/stores/useSchemaStore/index.ts
> feat: show node data based on node key

- src/components/Stats/index.tsx
- src/types/index.ts
closes #2086
Update the total node count:
> Update the total node count:

- src/components/App/SideBar/FilterSearch/index.tsx
- Tapping Show Results doesn't do anything:
closes: #2058
- **Ticket Number:** [ 2058 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2058 ]
https://www.loom.com/share/eb619a9d0a5d44d7b6f81fc63c234b96
> Fixed(Show-Results): Show Results button doesn't do anything

- src/components/ModalsContainer/BlueprintModal/Body/Editor/MediaOptions/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- Below attributes in Ontology node type creation add 3 media options:
- **Ticket Number:** [ 2071 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2071 ]
closes: #2071
https://www.loom.com/share/7811e6a5c7ce449ca1fd3dfcb63b6866
> Implement(Blueprint): Add `Media Options` Below Attributes

- src/components/App/SideBar/SelectedNodeView/Default/index.tsx
> For selected view show play button and enable playing audio, if node has audio_en properties

- cypress/e2e/curationTable/curation.cy.ts
The curration tests are still failing on jarvis after adding more wait time so I am just skipping them for now
> ci: skipping curation tests

- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
closes https://github.com/stakwork/sphinx-nav-fiber/issues/2070
https://www.loom.com/share/4919b0f16525447c82280245c8311f64
> Add Index to node type creation in Ontology

- cypress/support/commands.ts
- src/components/App/SideBar/FilterSearch/index.tsx
- src/network/fetchGraphData/index.ts
- src/stores/useDataStore/index.ts
- src/types/index.ts
> feat: added latest endpoint for initial load

- .github/workflows/build.yml
- .github/workflows/docker-build-master.yml
Creating a new release process where the branch closest to master will be tagged master and to get a new latest and release tag we do the manual release process
> ci: new release process

- src/components/App/SideBar/SelectedNodeView/Default/index.tsx
> feat: fix rendering for default view

- src/components/SourcesTableModal/SourcesView/QueuedSources/Table/index.tsx
closes #2069
Source Queued tick and cross are not according to figma
> Source Queued tick and cross icons are not according to figma

- src/components/Universe/Graph/Cubes/SelectionDataNodes/index.tsx
> feat: fixed selection view for single node

- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
> feat: fixed schema update handler

- src/components/SourcesTableModal/SourcesView/index.tsx
> feat: hide sources table

- src/components/ModalsContainer/CreateBountyModal/Body/index.tsx
> feat: added jwt token

- src/components/ModalsContainer/CreateBountyModal/Body/index.tsx
- src/network/postBounty/index.ts
> feat: passed properties for bountie create

- cypress/e2e/addContent/addTweet.cy.ts
- cypress/e2e/addContent/addWebpage.cy.ts
- cypress/e2e/addContent/addYoutube.cy.ts
- src/components/AddContentModal/index.tsx
- During Add Content flow, hide the location step
closes: #2165
- **Ticket Number:** [ 2165 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2165 ]
https://github.com/user-attachments/assets/b6a452f6-7110-43da-bd13-5a9602c0edb0
> Fixed: Hide `Location` Step during `Add Content` Flow

- src/components/ModalsContainer/BlueprintModal/Body/Editor/CustomAttributesStep/FormInput/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Editor/MediaOptions/index.tsx
- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- src/utils/colors/index.tsx
closes #2113
There is no consistency in toggle buttons design at blueprint modal and add attribute button not according to figma
> There is no consistency in toggle buttons design at blueprint modal and add attribute button not according to figma

- src/components/App/index.tsx
> feat: add stack socket connect

- .github/workflows/test.yml
This may cause some tests to fail I will disable them in the final commit on this PR
> ci: we removed the neo4j machine learning graph pull since it was causeing large usage in s3

- src/components/App/index.tsx
> feat: destructure message

- src/components/Stats/Alerts/index.tsx
- src/stores/useDataStore/index.ts
> feat: remove messages bar, when there is not messages

- src/components/App/SideBar/SelectedNodeView/Default/index.tsx
> fix: added condition for text prop

- src/stores/useGraphStore/index.ts
> feat: improved spash graph layout

- Dockerfile
- deploy/nginx.conf
closes this issue https://github.com/stakwork/jarvis-backend/issues/1774
This should make it so that navfiber just reroutes to the main page if there is a value in its url path
> feat: added a nginx.config file to help with routing

- src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
- src/components/ModalsContainer/EditNodeNameModal/Title/index.tsx
- Currently Editing node is hardcoded to Node Name and image_url.
- Render Required properties and optional properties (optional use ?string)
closes: #2198
- **Ticket Number:** [ 2198 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2198 ]
> Fixed(Edit Node): Render Properties

- src/components/Universe/Graph/Cubes/Text/index.tsx
> feat: moved icons from clickable eria

- .github/workflows/test.yml
- cypress/e2e/createGeneratedEdges/createGeneratedEdges.cy.ts
This is because we are having issues with TEXT_MODEL for create_generated_edges on jarvis
> test: added new test for node edge

- src/components/ModalsContainer/BlueprintModal/Body/AddEdgeNode/Body/index.tsx
closes #2135
there is no consistency in create type and add adge sidebar width
https://www.loom.com/share/8fd358e2cb4a4608bae9dae865fa37a7?sid=709b6ccd-0e6e-41b6-abf7-9e0cd9f2e676
> Create type and Add Adge sidebar width should be same ( Currently there is no consistency ) 

- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- src/network/fetchSourcesData/index.ts
> update color picker request

- src/components/App/SideBar/Relevance/Episode/Default/index.tsx
> feat: remove limitation for summary

- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/index.tsx
> feat: improve camera movement on load, improved icons perfomance

- src/components/App/SideBar/SelectedNodeView/Default/index.tsx
> feat: extended code viewer for frame and code types

- src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
- src/components/ModalsContainer/EditNodeNameModal/index.tsx
closes #2332
Edit node not looks good in large size and not according to figma
> [Edit Node] - UI looks not good in large size and not according to figma

- src/components/ModalsContainer/BlueprintModal/Body/index.tsx
closes #2149
When the Add Edge sidebar already open and then if we select a particular edge name then the source and destination are not auto selected
https://www.loom.com/share/fb7494e8144c48e3bd73fcfc22c89a03?sid=4a39ff05-4a06-4a61-a7d5-dd87a728f898
> When the Add Edge sidebar already open and then if we select a particular edge name then the source and destination are not auto selected

- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- Currently, on hover the mouseover does not appear:
closes: #2341
- **Ticket Number:** [ 2341 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2341 ]
> [Blueprint]:  Add hover state to color/icon button

- src/components/App/Splash/index.tsx
> feat: changed loading logic for schema, refactored splash page

- src/components/App/SideBar/FilterSearch/FastFilters/index.tsx
> feat: renamed favorites

- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
Here i have noticed that as Hexa color coming without # due to that is not going to be reflect on Graph Node where it looks like White
> Hash tag should be present with hexa color value

- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
> feat: update colors for nodes

- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
- src/stores/useDataStore/index.ts
> feat: normalized node scales

- src/components/Universe/Graph/index.tsx
- src/components/common/TypeBadge/index.tsx
> feat: updated icon and color for label

- src/components/App/SecondarySidebar/index.tsx
> fix: fixed sidebar z-index

- src/components/App/SideBar/index.tsx
> fix: update sidebar-zindex

- src/components/App/index.tsx
> feat: hide ask quesiont, if feautureflag is false

- src/components/App/index.tsx
> feat: added command for cockets to pass projectid

- src/components/Universe/Graph/Cubes/SelectionDataNodes/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
> fix: fixed selection view overlap issue

- src/stores/useDataStore/index.ts
> feat: change default sort to score

- src/components/mindset/components/Sidebar/Transcript/Viewer/index.tsx
> fix: fix duplicate

- src/components/mindset/components/LandingPage/index.tsx
- src/components/mindset/components/VideoCard/index.tsx
- src/network/fetchSourcesData/index.ts
> [Graph Mindset] Add Seed Episodes logic to landing page 

- src/components/mindset/components/LandingPage/index.tsx
- src/components/mindset/components/VideoCard/index.tsx
- src/network/fetchSourcesData/index.ts
closes  #2492
https://www.loom.com/share/a07786edf0724c4dbd280401ed810539?sid=0e58351f-c3e8-481e-9482-49d160ebe773
> [Graph Mindset] Render seed episodes on the landing page

- src/components/mindset/components/PlayerContols/Controls/index.tsx
- src/components/mindset/components/Sidebar/index.tsx
- src/components/mindset/index.tsx
- Ensure all borders, paddings, and margins around UI components (transcript card, video player, and timeline) are consistent with the 20px design standard.
closes: #2508
- **Ticket Number:** [ 2508 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2508 ]
> [Graph Mindset] Border and Padding

- src/components/Universe/Graph/Cubes/Text/index.tsx
> Render images for all types

- src/components/Universe/Graph/Cubes/NodeWrapper/index.tsx
- src/components/Universe/Graph/Cubes/SelectionDataNodes/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
> feat: update hoverednode

- src/components/AddItemModal/SourceTypeStep/index.tsx
closes  #2533
https://www.loom.com/share/38e25ac290404d48861aa89212f6fadd?sid=0cd96014-fc37-4bb0-b491-a9e527817d57
> [Add Item] Incorrect Rendering of properties

- src/components/mindset/components/MediaPlayer/index.tsx
- Pressing the the space key should play and pause the media.
- **Ticket Number:** [ 2516 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2516 ]
https://www.loom.com/share/fde9d2169d6b46848051c4ce20359017
> [Graph Mindset]: Media Player Add spacebar play/pause control

- src/components/mindset/components/Sidebar/Transcript/index.tsx
> feat: changes mls to sec for transcript clips

- src/components/mindset/components/PlayerContols/index.tsx
- src/components/mindset/components/Sidebar/Transcript/index.tsx
- src/components/mindset/components/Sidebar/index.tsx
- src/components/mindset/index.tsx
> [Graph Mindset] Extend timeline component to the left hand side

- src/components/App/SideBar/Relevance/Episode/index.tsx
- src/components/Universe/CursorTooltip/index.tsx
- src/components/Universe/index.tsx
> feat: get tooptip back

- src/components/mindset/index.tsx
> feat: speeded up nodes appearence

- src/components/Universe/Graph/Cubes/SelectionDataNodes/index.tsx
> feat: fixed nodes alignment

- src/components/Universe/Graph/Cubes/NodeWrapper/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
- src/components/Universe/Graph/index.tsx
- src/components/mindset/index.tsx
- src/stores/useGraphStore/index.ts
> feat: disable node appearence from left, graph rotation

- src/components/Universe/Controls/CameraAnimations/index.ts
- src/stores/useGraphStore/index.ts
> feat: disable rotation

- src/components/mindset/components/Sidebar/Transcript/index.tsx
- src/components/mindset/components/Sidebar/index.tsx
- src/components/mindset/index.tsx
closes #2583
closes: #2573
https://www.loom.com/share/7db65f4830824f0e93792bf607e2d87e
> fix(mindset): improve layout responsiveness

- src/components/ModalsContainer/CreateBountyModal/Body/index.tsx
closes #2559
- POST /bounty should also send pubkey
> Fixed: POST /bounty to send pubkey 

- src/components/Universe/Graph/Cubes/SelectionDataNodes/Node/index.tsx
> feat: update layout for selected node

- src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
closes #ticket_number:
https://www.loom.com/share/02e3de705ef744a3a469773875aeb402
> PUT /node request sending incorrect data

- src/components/Universe/Graph/Connections/LineComponent.tsx
- src/components/Universe/Graph/Connections/LineInstance.tsx/index.tsx
- src/components/Universe/Graph/Connections/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
- src/components/Universe/Graph/index.tsx
- src/components/Universe/GraphSearch/index.tsx
- src/components/Universe/index.tsx
- src/components/mindset/components/MediaPlayer/index.tsx
- src/stores/useGraphStore/index.ts
> feat: add search for graph

- src/components/Universe/Graph/Connections/LineComponent.tsx
- src/components/Universe/Graph/Cubes/Candidates/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/Graph/Cubes/NodeWrapper/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
- src/components/Universe/Graph/index.tsx
- src/components/Universe/index.tsx
- src/components/mindset/components/Sidebar/Transcript/index.tsx
> feat: fixed search hover

- src/components/Universe/Controls/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/index.tsx
> feat: removed search

- src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
> Fix: Real-time Node State Update After Editing Properties

- src/components/App/SideBar/Person/index.tsx
- src/components/ModalsContainer/EditNodeNameModal/Body/index.tsx
- src/stores/useDataStore/index.ts
> feat: add selector for normalized node

- src/components/Universe/Graph/Connections/LineComponent.tsx
- src/components/Universe/Graph/Connections/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
- src/components/Universe/GraphSearch/NodeTypes/index.tsx
- src/components/Universe/GraphSearch/index.tsx
- src/stores/useGraphStore/index.ts
> feat: added filters for graph highlight

- src/stores/useGraphStore/index.ts
> fix: changed statenode to selectednode

- src/components/mindset/components/PlayerContols/ProgressBar/Markers/index.tsx
- src/components/mindset/components/Sidebar/Transcript/index.tsx
- src/components/mindset/index.tsx
- src/stores/useMindsetStore/index.ts
> feat: update mindset to by clip load

- src/components/App/SideBar/AiSearch/index.tsx
- src/components/App/SideBar/AiSummary/AiQuestions/index.tsx
- src/components/App/SideBar/AiSummary/AiSources/index.tsx
- src/components/App/SideBar/AiSummary/index.tsx
- src/components/App/UniverseQuestion/index.tsx
- src/components/Universe/Graph/Connections/index.tsx
- src/components/Universe/Graph/Cubes/SelectionDataNodes/Node/index.tsx
- src/components/Universe/Graph/Cubes/SelectionDataNodes/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/index.tsx
- src/components/Universe/index.tsx
- src/stores/useAiSummaryStore/index.ts
- src/stores/useDataStore/index.ts
- src/stores/useGraphStore/index.ts
- src/types/index.ts
> feat: show only sources for ai search

- src/components/Universe/Graph/Cubes/SelectionDataNodes/Node/index.tsx
closes #2618
https://www.loom.com/share/75594e1d9ce74096b6ae0e730e7792f7?sid=213a2992-c4be-4ebb-8a17-73f337674ea4
> Add 'Generate Unit Test' for Function nodes to new selection view

- src/components/mindset/components/LandingPage/index.tsx
- src/components/mindset/components/Sidebar/index.tsx
- src/components/mindset/index.tsx
> feat: updated link for episode by source link

- src/components/Universe/Graph/index.tsx
closes https://github.com/stakwork/sphinx-nav-fiber/pull/2623#issuecomment-2615786090
> Remove old component from background

- src/components/App/index.tsx
> feat: enabled logs

- src/components/App/AppBar/index.tsx
- src/components/Universe/GraphSearch/index.tsx
- src/components/Universe/index.tsx
> feat: added filters for graph

- src/components/App/SideBar/AiSummary/index.tsx
> feat: replaced fetchdata with fetchAidData

- src/components/App/SideBar/AiSummary/AiSummarySkeleton/index.tsx
- src/components/App/SideBar/AiSummary/index.tsx
- src/components/App/SideBar/AiSummary/utils/AiSummaryHighlight/markdown/index.tsx
closes #2635 
https://www.loom.com/share/beb1429f535e4b328d485d84653b1d66
> [AI Chat] Fix Heading Formatting

- src/components/mindset/components/PlayerContols/ProgressBar/Markers/Marker/index.tsx
- src/components/mindset/components/PlayerContols/ProgressBar/Markers/index.tsx
> fix: changed position calc

- src/components/Universe/GraphSearch/index.tsx
- src/stores/useAiSummaryStore/index.ts
> feat: add z-index to search, update fetchAiData params

- src/components/App/SideBar/AiSummary/AiAnswer/__tests__/index.tsx
- src/components/App/SideBar/AiSummary/AiAnswer/index.tsx
> feat: disabled enteties

- src/components/Universe/Controls/CameraAnimations/useAutoNavigate.ts
- src/components/Universe/Graph/Connections/LineComponent.tsx
- src/components/Universe/Graph/Connections/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
- src/components/Universe/index.tsx
- src/stores/useGraphStore/index.ts
> feat: moved selection view to 3d

- src/components/Universe/Controls/CameraAnimations/useAutoNavigate.ts
- src/components/Universe/Graph/UI/NodeControls/index.tsx
- src/components/Universe/Graph/index.tsx
- src/components/Universe/index.tsx
- src/stores/useGraphStore/index.ts
> feat: added 2d support for selection view

- src/stores/useDataStore/index.ts
> feat: remove extra filter for nodes

- src/components/Universe/CursorTooltip/HoverCard/index.tsx
closes #2648
https://www.loom.com/share/e76ff79df3cb4922afcd21a3f8c49227
> Display question text in hover card for Question nodes

- src/components/App/SideBar/SelectedNodeView/Default/index.tsx
> feat: added support for body tag

- src/components/SettingsModal/SettingsView/General/index.tsx
> Fix: Settings Modal Save Button Spacing

- cypress/e2e/trendingTopics/trendingTopics.cy.ts
- cypress/support/commands.ts
- src/components/App/index.tsx
closes #2669
https://www.loom.com/share/a82e2058c6b0477290c43474732f3b2f
> Set graph view as default instead of AI chat interface

- src/components/Universe/GraphSearch/index.tsx
closes #2666
https://www.loom.com/share/7119fccef62641f29b1270a74a134e1a
> Fix: Hide Graph Search UI During Splash Screen

- src/components/App/SideBar/SelectedNodeView/Default/index.tsx
> feat: fixed code layout

- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/Graph/Cubes/Text/TextWithBackgound/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/utils/palleteGenerator/index.tsx
> feat: added new desing for nodes, added pallete generator

- .github/workflows/docker-build.yml
> feat: increase actions/cache: v2 to v3

- src/components/App/index.tsx
- src/hooks/useRetrieveData/index.ts
- src/stores/useDataStore/index.ts
> feat: add fetch data for selected node on initial load

- src/stores/useSchemaStore/index.ts
> feat: added cycling for colors

- src/components/mindset/components/LandingPage/fetchNodes/index.ts
- src/components/mindset/components/LandingPage/index.tsx
- src/network/fetchSourcesData/index.ts
- src/types/index.ts
> feat: replace hardcoded episodes

- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- src/network/fetchSourcesData/index.ts
closes #2662
https://www.loom.com/share/e4b69108ab79498bbfafc7db5ec11b7e
> Add new `type_description` to Blueprint 

- src/components/Universe/Graph/UI/NodeControls/index.tsx
- src/network/analyzeGithubRepo/index.ts
> Update git analyze endpoint

- src/components/common/TypeBadge/index.tsx
> fix: add slash to icon path

- src/components/Universe/Graph/UI/NodeControls/index.tsx
> fix(update-analyze): git analyse endpoint should be callable

- src/components/mindset/components/LandingPage/index.tsx
> Add `Graph Mindset` Logo Landing Page

- src/stores/useAiSummaryStore/index.ts
> Update params for AI Chat (when ai_summary=true)

- src/components/mindset/tweet/components/Sidebar/Stats/index.tsx
- src/utils/colors/index.tsx
> Render Tweet analytics component

- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/utils/removeLeadingMentions/__tests__/index.ts
- src/utils/removeLeadingMentions/index.tsx
closes #2729
[Link](https://github.com/stakwork/sphinx-nav-fiber/issues/2729)
https://www.loom.com/share/7bb0071e25984144aee7fce2c7def472?sid=af2eaf5d-0af7-4205-9371-cbf252bbb48e
> Remove User Mentions at Beginning of Text Using Regex 

- src/components/mindset/tweet/components/PlayerContols/ProgressBar/Markers/Marker/index.tsx
- src/components/mindset/tweet/components/PlayerContols/ProgressBar/Markers/index.tsx
- src/components/mindset/tweet/components/PlayerContols/ProgressBar/index.tsx
closes #2725
https://www.loom.com/share/65870caa230d4d0eba37a84bc2fb96ba
> Timeline Scrubber UI Redesign

- src/components/Universe/Graph/Cubes/Text/index.tsx
> feat: fix filters, image blink, wrong svg path

- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
- src/components/Universe/Graph/index.tsx
- src/components/Universe/Graph/utils/calculateGroupRadius/index.ts
- src/components/mindset/tweet/components/LandingPage/index.tsx
- src/components/mindset/tweet/components/PlayerContols/index.tsx
- src/components/mindset/tweet/constant.ts
- src/components/mindset/tweet/index.tsx
- src/network/fetchSourcesData/index.ts
- src/stores/useGraphStore/index.ts
> feat: added real time update

- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/Graph/Cubes/NodeWrapper/index.tsx
- src/components/Universe/Graph/Cubes/Text/TextWithBackgound/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/Cubes/constants.ts
- src/components/Universe/Graph/Cubes/index.tsx
> feat: added node scale based on weight

- src/components/Universe/CursorTooltip/HoverCard/index.tsx
> Remove Link from HoverCard component ToolTip

- src/components/mindset/tweet/components/PlayerContols/Controls/index.tsx
- src/components/mindset/tweet/components/PlayerContols/ProgressBar/index.tsx
- src/components/mindset/tweet/components/PlayerContols/index.tsx
closes #2734
https://www.loom.com/share/7345962d98ea4b3f8e4d67b7b1c518ce
> Fix Timeline Scrubber Alignment and Playback Issues

- src/components/mindset/tweet/components/Sidebar/Stats/index.tsx
> [Analytics] Enhance Tweet Analytics Box with Sentiment and User Data

- src/components/mindset/tweet/components/PlayerContols/index.tsx
> feat: add check for initial timing

- src/components/mindset/components/PlayerContols/ProgressBar/Chapters/index.tsx
> feat: added support for properties.name

- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
> feat: change cubic normalization to square

- src/components/mindset/components/Header/index.tsx
closes #2752
https://www.loom.com/share/d5f3fc251885423aab62fc25a0547392
>  Implement Navigation to Home on Logo and Text Click in Graphmindset 

- src/hooks/useRetrieveData/index.ts
> feat: try1

- src/components/Universe/Graph/Neighborhoods/index.tsx
> fix: changed name to prop.name

- src/network/fetchSourcesData/index.ts
> feat: increased pathway limit

- src/components/Universe/CursorTooltip/HoverCard/User/index.tsx
- src/components/Universe/CursorTooltip/HoverCard/index.tsx
- src/components/Universe/CursorTooltip/index.tsx
> feat: updated tooltip design

- src/components/App/SideBar/AiSummary/AiSources/index.tsx
- src/stores/useDataStore/index.ts
closes #2755
https://www.loom.com/share/70cc76dc2c264a01947ead1f04ee271f
> [Enhancement] Implement real-time node data fetching for WebSocket sources

- src/components/Universe/CursorTooltip/HoverCard/index.tsx
> feat: add text for tweet tooltip

- src/components/Universe/CursorTooltip/HoverCard/General/index.tsx
- src/components/Universe/CursorTooltip/HoverCard/Tweet/index.tsx
- src/components/Universe/CursorTooltip/HoverCard/User/index.tsx
- src/components/Universe/CursorTooltip/HoverCard/index.tsx
> feat: update tooltip

- src/components/mindset/tweet/components/PlayerContols/ProgressBar/index.tsx
> feat: hidden scrubber

- src/components/mindset/tweet/components/Sidebar/Stats/index.tsx
> Add followers and follower to view ration

- src/components/App/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/Text/TextWithBackgound/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/Cubes/constants.ts
> feat: add node iteraction effects

- src/components/Universe/Graph/Connections/LineComponent.tsx
> feat: add animation to edges

- src/components/Universe/Graph/Cubes/Text/TextWithBackgound/index.tsx
> feat: add additional check

- src/components/mindset/tweet/components/PlayerContols/ProgressBar/index.tsx
closes : https://community.sphinx.chat/p/csb4dj2tu2rqjmn086qg/assigned/3892/3
https://www.loom.com/share/6fed342c50cf420e8e8a206f80566785
> Fix: Implement Fixed Width for Tweet Graph Scrubber to Prevent Jitter

- src/components/App/SideBar/AiSummary/AiSources/index.tsx
closes #2755
https://github.com/stakwork/sphinx-nav-fiber/pull/2763#issuecomment-2687485000
https://www.loom.com/share/daa44bb951ce4dfda915b618d556b7c9
> [Bug Fix] Fix source nodes not rendering in Sources Side Bar 

- src/components/common/TypeBadge/index.tsx
> Fix: Type badge colors match graph icon colors

- src/components/App/SideBar/AiSummary/AiAnswer/index.tsx
- src/components/App/index.tsx
- src/components/Universe/HtmlContent/index.tsx
- src/components/Universe/index.tsx
- src/stores/useAppStore/index.ts
https://www.loom.com/share/592350441d4648cdad85713c07c44180
Bounty: https://community.sphinx.chat/bounty/3910
> Feature: Add HTML Content Renderer for Steiner GA Workflow Responses

- src/components/Universe/Graph/Cubes/Text/TextWithBackgound/index.tsx
> feat: update node width

- src/network/fetchSourcesData/index.ts
> feat: update pathway edge type

- src/components/DataRetriever/index.tsx
- src/components/Universe/Graph/Cubes/Candidates/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/RelevanceBadges/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
- src/components/Universe/Graph/Neighborhoods/index.tsx
- src/components/Universe/Graph/index.tsx
- src/components/Universe/useSelectedNodeFromUrl.tsx
- src/components/mindset/components/Sidebar/Transcript/index.tsx
- src/stores/useGraphStore/index.ts
- src/stores/useSimulationStore/index.ts
- src/stores/useSimulationStore/utils/distributeNodesOnSphere/index.ts
> feat: split simulation and graph store

- src/network/fetchSourcesData/index.ts
> feat: increase query limit

- src/components/App/SideBar/AiSummary/AiAnswer/index.tsx
> Feature: Instant Rendering for HTML Chat Responses

- src/components/mindset/tweet/components/PlayerContols/ProgressBar/ProgressChart/index.tsx
- src/components/mindset/tweet/components/PlayerContols/ProgressBar/index.tsx
> feat: add chart for player

- src/components/Universe/CursorTooltip/HoverCard/Tweet/index.tsx
closes #2792
https://www.loom.com/share/fbbee33660184a81807474f3c9ea5123
> Fix Tweet tooltip width adjustment for large metric values

- src/components/ModalsContainer/TweetAnalyze/Body/index.tsx
- src/network/fetchSourcesData/index.ts
> feat: update sort, and showed tweets

- src/components/Modal/index.tsx
- src/components/ModalsContainer/TweetAnalyze/Body/index.tsx
- src/components/ModalsContainer/TweetAnalyze/index.tsx
> Feature/tweet UI fix

- src/components/ModalsContainer/TweetAnalyze/Body/index.tsx
- src/components/mindset/tweet/components/LandingPage/index.tsx
> feat: added link to tweet, fixed landing page

- src/components/ModalsContainer/TweetAnalyze/Body/index.tsx
- src/components/Universe/Graph/index.tsx
- src/components/mindset/index.tsx
- src/network/fetchSourcesData/index.ts
- src/stores/useMindsetStore/index.ts
- src/stores/useSimulationStore/index.ts
> feat: add claims load, add extra filter to graph links

- src/stores/useSimulationStore/index.ts
> fix: add additional filter

- src/stores/useAiSummaryStore/index.ts
- src/stores/useDataStore/index.ts
> Update default search method and ai_summary depth

- src/components/mindset/components/LandingPage/index.tsx
> Hide YouTube link submission for unauthenticated Sphinx users

- src/components/Universe/CursorTooltip/HoverCard/General/index.tsx
> feat: replace name with description for claim node

- src/components/mindset/components/LandingPage/index.tsx
> feat: enable sphinx check

- src/components/App/SideBar/AiSummary/AiSummarySkeleton/index.tsx
> Add dynamic title and status indicators to Answer component

- src/components/App/SideBar/AiSummary/AiAnswer/index.tsx
- src/components/App/SideBar/AiSummary/AiSummarySkeleton/index.tsx
- src/components/Universe/Controls/CameraAnimations/index.ts
- src/components/Universe/Graph/Connections/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/stores/useAiSummaryStore/index.ts
- src/stores/useSimulationStore/index.ts
- src/types/index.ts
> feat: reposition graph, add project id for ai

- src/components/Universe/Graph/Cubes/Text/TextWithBackgound/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
> feat: fix hover dragging on node

- src/components/App/ActionsToolbar/index.tsx
- src/components/Universe/Graph/Connections/index.tsx
- src/components/common/GraphViewControl/index.tsx
- src/stores/useSimulationStore/index.ts
> feat: added split layout view

- src/components/mindset/components/LandingPage/fetchNodes/index.ts
- src/components/mindset/components/LandingPage/index.tsx
> feat: increase limit for mindset episodes

- cypress/e2e/addContent/addSource.cy.ts
- cypress/e2e/addContent/addTweet.cy.ts
- cypress/e2e/addContent/addWebpage.cy.ts
- cypress/e2e/addContent/addYoutube.cy.ts
- cypress/e2e/admin/signin.cy.ts
- cypress/e2e/seeLatest/latest.cy.ts
none
These cypress tests on jarvis-backend constantly fail so we are disabling them till we can get better tests in
commented out the tests
commented out the tests
This just disables tests that are breaking
> test: disable cypress tests

- src/components/mindset/components/Sidebar/index.tsx
> feat: add new media-url

- .github/workflows/docker-build-master.yml
- .github/workflows/docker-build.yml
> feat: update ubuntu runner version

- src/components/ModalsContainer/ClaimsModal/Body/index.tsx
> feat: positioned isolated nodes

- src/components/Universe/Graph/Cubes/Text/TextWithBackgound/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
> feat: decrease font-size, limit size for node

- src/components/Universe/Graph/Connections/index.tsx
> feat: change edge size

- src/components/ModalsContainer/TweetAnalyze/Body/Engagement/index.tsx
- src/components/ModalsContainer/TweetAnalyze/Body/Retweets/index.tsx
- src/components/ModalsContainer/TweetAnalyze/Body/index.tsx
- src/components/mindset/components/LandingPage/fetchNodes/index.ts
> feat: add top reposters for tweet analyze

- src/components/ModalsContainer/ClaimsModal/Body/index.tsx
> feat: update claims view

- src/components/ModalsContainer/TweetAnalyze/Body/Engagement/index.tsx
- src/components/ModalsContainer/TweetAnalyze/Body/Retweets/index.tsx
- src/components/ModalsContainer/TweetAnalyze/Body/Sentiment/index.tsx
- src/components/common/CsvDownloader/index.tsx
> feat: add download for tweet reports

- src/components/ModalsContainer/TweetAnalyze/Body/Engagement/index.tsx
- src/components/ModalsContainer/TweetAnalyze/Body/Sentiment/index.tsx
> feat: add followers to report

- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
- Add multi-select support for node keys
- **Ticket Number:** [ 2521 ]
- **Link:** [ https://github.com/stakwork/sphinx-nav-fiber/issues/2521 ]
https://www.loom.com/share/2d814e8832df4ef287db838434454dbf
> Add multi-select support for Node Keys in Blueprint Editor

- src/components/ModalsContainer/ClaimsModal/Body/Graph/index.tsx
> feat: updated claims modal

- src/components/Universe/Graph/Cubes/index.tsx
> feat: prevent selection on rotate

- src/components/Universe/Graph/Cubes/index.tsx
> fix: followes condtion

- src/components/mindset/components/Sidebar/Transcript/index.tsx
- src/components/mindset/index.tsx
- src/stores/useMindsetStore/index.ts
> feat: make nodes load in chunks

- src/components/Universe/Controls/CameraAnimations/useAutoNavigate.ts
> feat: improved zoom on select

- src/components/ModalsContainer/TweetAnalyze/Body/Engagement/index.tsx
- src/components/ModalsContainer/TweetAnalyze/Body/index.tsx
- src/network/tweetAnalyze/index.ts
> feat: change endpoint for followers/engagement

- cypress/e2e/trendingTopics/trendingTopics.cy.ts
Disables the trendingTopics test since it has failures when running on jarvis-backend
> test: disalbed trendingtopics test

- src/components/mindset/tweet/components/LandingPage/TopicCard/index.tsx
- src/components/mindset/tweet/components/LandingPage/index.tsx
> feat: add hardcoded topic value

- src/components/Universe/Graph/Cubes/index.tsx
- src/components/Universe/Graph/Cubes/utils/nodesMatchesDateRangeFilter /index.ts
- src/components/Universe/Graph/Cubes/utils/nodesMatchsFollowesFilter/index.ts
- src/components/Universe/GraphSearch/GraphFilter/index.tsx
- src/components/Universe/SelectionContent/Controls/index.tsx
- src/stores/useGraphStore/index.ts
- src/types/index.ts
> feat: add date filter for nodes

- src/components/mindset/topic/index.tsx
> feat: change topics request

- src/components/mindset/components/MediaPlayer/index.tsx
> feat: add start timestamp

- src/components/mindset/components/PlayerContols/Controls/index.tsx
- src/components/mindset/components/PlayerContols/ProgressBar/index.tsx
- src/components/mindset/components/Sidebar/Transcript/index.tsx
- src/components/mindset/components/Sidebar/index.tsx
- src/components/mindset/index.tsx
> feat: add mobile layout for mindset

- src/components/ModalsContainer/BlueprintModal/Body/Editor/index.tsx
> feat: update node key on init

- src/components/Universe/Graph/Connections/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/Point/index.tsx
- src/components/Universe/Graph/Cubes/NodePoints/index.tsx
- src/components/Universe/Graph/Cubes/Text/TextWithBackgound/index.tsx
- src/components/Universe/Graph/Cubes/Text/index.tsx
- src/components/Universe/Graph/Cubes/constants.ts
- src/components/Universe/Graph/Cubes/index.tsx
- src/stores/useFeatureFlagStore/index.ts
> feat: add scale feature, change hover behaviour

- src/components/Universe/Graph/Cubes/RelevanceGroups/index.tsx
- src/components/Universe/Graph/Cubes/RelevanceGroups/styles.ts
- src/components/Universe/Graph/Cubes/RelevanceList/indes.tsx
- src/stores/useDataStore/index.ts
> feat: update selection view

- src/components/Universe/Graph/Connections/LineComponent.tsx
- src/components/Universe/Graph/Cubes/RelevanceGroups/index.tsx
- src/components/Universe/Graph/Cubes/RelevanceGroups/styles.ts
- src/components/Universe/Graph/Cubes/RelevanceList/indes.tsx
- src/components/Universe/Graph/Cubes/Text/TextWithBackgound/index.tsx
- src/components/Universe/Graph/Cubes/index.tsx
> feat: update selection view ui

- src/components/mindset/components/LandingPage/fetchNodes/index.ts
- src/components/mindset/components/LandingPage/index.tsx
> feat: improve loading time

- src/stores/useDataStore/index.ts
> feat: update depth param

- src/components/App/SideBar/FilterSearch/Hops/index.tsx
- src/components/App/SideBar/FilterSearch/MaxResults/index.tsx
- src/stores/useDataStore/index.ts
This should fix the limit param for `/graph/search` and also increases some values
@Rassl let me know if I did this correctly I don't contribute to this repo too much
> fix: increase the search limits and also fix the limit query param

- src/utils/apiUrlFromSwarmHost/index.ts
> chore: navfiber codespaces

- src/stores/useMindsetStore/index.ts
> feat: extract guests and host for mindset

- src/components/Universe/Graph/index.tsx
- src/components/mindset/components/PodcastLayout/Claim/index.tsx
- src/components/mindset/components/PodcastLayout/Clip/index.tsx
- src/components/mindset/components/PodcastLayout/Speaker/index.tsx
- src/components/mindset/components/PodcastLayout/index.tsx
- src/components/mindset/index.tsx
> feat: add podcast layout for episode

- src/components/mindset/components/Sidebar/index.tsx
> fix: fixed typo

- src/components/mindset/components/MediaPlayer/index.tsx
- src/components/mindset/components/PlayerContols/ProgressBar/index.tsx
- src/components/mindset/components/PlayerContols/index.tsx
closes #2901
Users spent a lot of time navigating through videos due to inefficient controls:
- Lack of visual feedback about what time position they would jump to
- Users couldn't see current progress and total video duration
- The process of finding the needed moment was frustrating and time-consuming
Implemented a precise video navigation system with visual hints:
- Tooltip with time preview for accurate positioning
- Display of current time and total duration
- Interactive feedback when hovering over the video
ProgressBar.tsx:
- Added interactive tooltip showing time on cursor hover
MediaPlayer.tsx:
- Added overlay displaying "current time / total time" on hover
- Implemented using CSS classes for smooth appearance and reduced load
Conducted user scenario testing:
- Verified accurate …
> feat: interactive video progress bar improvements

- src/components/App/index.tsx
> fixed linting
